import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const frameworks=['vue','svelte','solid'];
test('complete examples install production tarballs without source aliases',async()=>{for(const framework of frameworks){const pkg=JSON.parse(await readFile(`examples/${framework}/package.json`,'utf8'));assert.equal(pkg.dependencies[`@cloudflare/kumo-${framework}`],`https://kumo-compiler.coey.dev/packages/kumo-${framework}-0.0.1.tgz`);const source=await readFile(framework==='vue'?`examples/${framework}/src/App.vue`:framework==='svelte'?`examples/${framework}/src/App.svelte`:`examples/${framework}/src/main.jsx`,'utf8');assert.match(source,new RegExp(`@cloudflare/kumo-${framework}`));assert.match(source,/Button/);assert.match(source,/Field/);assert.doesNotMatch(source,/alias|dx\/packages|placeholder/i)}});
test('Diataxis docs expose tutorial, how-to, reference, and explanation routes',async()=>{for(const file of ['astro/src/pages/docs/tutorials/first-library/index.astro','astro/src/pages/docs/how-to/install/index.astro','astro/src/pages/docs/how-to/github/index.astro','astro/src/pages/docs/how-to/svelte-playground/index.astro','astro/src/pages/docs/reference/packages/index.astro','astro/src/pages/docs/reference/button/index.astro','astro/src/pages/docs/reference/field/index.astro','astro/src/pages/docs/reference/styles/index.astro','astro/src/pages/docs/explanation/distribution/index.astro','astro/src/pages/docs/explanation/evidence/index.astro'])assert.ok((await readFile(file,'utf8')).length>500,file)});
test('docs and examples use build-time Shiki syntax highlighting',async()=>{const component=await readFile('astro/src/components/SyntaxCode.astro','utf8');assert.match(component,/astro:components/);assert.match(component,/github-dark-default/);for(const file of ['astro/src/pages/docs/tutorials/first-library/index.astro','astro/src/pages/docs/how-to/install/index.astro','astro/src/pages/docs/how-to/svelte-playground/index.astro','astro/src/pages/docs/how-to/forms/index.astro','astro/src/pages/docs/how-to/github/index.astro','astro/src/pages/docs/reference/button/index.astro','astro/src/pages/docs/reference/styles/index.astro','astro/src/pages/examples/vue/index.astro','astro/src/pages/examples/svelte/index.astro','astro/src/pages/examples/solid/index.astro'])assert.match(await readFile(file,'utf8'),/SyntaxCode/,file)});
test('homepage pairs every package import with the current install URL',async()=>{const home=await readFile('astro/src/pages/index.astro','utf8');for(const framework of ['vue','svelte','solid']){assert.match(home,new RegExp(`npm install https://kumo-compiler\\.coey\\.dev/packages/kumo-${framework}-0\\.0\\.1\\.tgz`));assert.match(home,new RegExp(`@cloudflare/kumo-${framework}`))}assert.doesNotMatch(home,/github\.com\/<|npm install @cloudflare/)});
test('shared navigation and PWA SEO are present on product, docs, and examples',async()=>{for(const layout of ['astro/src/layouts/Layout.astro','astro/src/layouts/DocsLayout.astro','astro/src/layouts/ExampleLayout.astro']){const source=await readFile(layout,'utf8');assert.match(source,/SiteNav/);assert.match(source,/SeoHead/)}const nav=await readFile('astro/src/components/SiteNav.astro','utf8');assert.match(nav,/site-nav__drawer/);assert.match(nav,/aria-expanded/);assert.doesNotMatch(nav,/overflow:auto/);const seo=await readFile('astro/src/components/SeoHead.astro','utf8');for(const token of ['canonical','og:title','twitter:card','manifest.webmanifest','application/ld+json','serviceWorker'])assert.match(seo,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));for(const asset of ['astro/public/manifest.webmanifest','astro/public/sw.js','astro/public/robots.txt','astro/public/favicon.svg','astro/public/icon-192.png','astro/public/icon-512.png'])assert.ok((await readFile(asset)).length>20,asset)});
test('single-repository distribution prepares GitHub assets and npm dry-run only',async()=>{const github=await readFile('scripts/github-release.mjs','utf8'),npm=await readFile('scripts/npm-publish-preflight.mjs','utf8');assert.match(github,/releases\/download\/\$\{tag\}/);assert.match(github,/SHA256SUMS/);assert.doesNotMatch(github,/gh release create|git push/);assert.match(npm,/--dry-run/);assert.doesNotMatch(npm,/--provenance|npm login/)});
test('svelte.dev receipt records the actual registry-only failure',async()=>{const receipt=JSON.parse(await readFile('proof/playgrounds/svelte-dev.json','utf8'));assert.equal(receipt.status,'blocked');assert.equal(receipt.sourceLoaded,true);assert.equal(receipt.resolverEvidence.jsdelivrStatus,404);assert.equal(receipt.resolverEvidence.npmStatus,404);assert.equal(receipt.componentImplementationBlocked,false);assert.match(receipt.observedError,/Failed to import @cloudflare\/kumo-svelte/)});
