import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calendarGrid,createSelection,deriveDateRange,isDateDisabled,loadDateRange,parseISODate,resetRange,selectRange,selectSingle,validateDateRange} from '../src/kumo/library/date-range.mjs';
const contracts=['date-picker','date-range-picker'].map(n=>JSON.parse(fs.readFileSync(`contracts/kumo.observable/v1/components/${n}.json`)));

test('capability is derived exactly from canonical contracts and stable twice',()=>{const a=deriveDateRange(contracts),b=deriveDateRange(contracts);assert.deepEqual(loadDateRange(),a);assert.deepEqual(a,b);assert.equal(JSON.stringify(a),JSON.stringify(b));assert.deepEqual(a.provenance.map(x=>x.vectorIds),contracts.map(x=>x.vectors.map(v=>v.id)));});
test('strict ISO parsing rejects rollover, timestamps, and year zero',()=>{assert.deepEqual(parseISODate('2024-02-29'),{year:2024,month:2,day:29,iso:'2024-02-29',epochDay:19782});for(const bad of ['2023-02-29','2025-13-01','2025-1-01','0000-01-01','2025-01-01T00:00:00Z'])assert.throws(()=>parseISODate(bad),/invalid ISO date/);});
test('calendar grid is fixed, deterministic, and independent of Intl',()=>{const a=calendarGrid('2025-01-01'),b=calendarGrid('2025-01-01');assert.deepEqual(a,b);assert.equal(a.length,42);assert.deepEqual([a[0].iso,a[0].column,a[3].iso,a[41].iso],['2024-12-29',0,'2025-01-01','2025-02-08']);assert.equal(calendarGrid('2025-01-01',{weekStartsOn:1})[0].iso,'2024-12-30');});
test('inclusive boundaries and exact disabled dates block selection',()=>{const o={min:'2025-01-10',max:'2025-01-20',disabled:['2025-01-15']};assert.equal(isDateDisabled('2025-01-09',o),true);assert.equal(isDateDisabled('2025-01-10',o),false);assert.equal(isDateDisabled('2025-01-15',o),true);assert.equal(isDateDisabled('2025-01-20',o),false);assert.equal(isDateDisabled('2025-01-21',o),true);assert.deepEqual(selectSingle(null,'2025-01-09',o),{value:null,proposal:null,committed:false});assert.deepEqual(selectSingle(null,'2025-01-10',o),{value:'2025-01-10',proposal:'2025-01-10',committed:true});});
test('range start, end, restart, and reset are explicit',()=>{const start=selectRange(null,'2025-01-10');assert.equal(start.phase,'start');assert.deepEqual(selectRange(start.value,'2025-01-12').value,{start:'2025-01-10',end:'2025-01-12'});assert.deepEqual(selectRange(start.value,'2025-01-08'),{value:{start:'2025-01-08',end:null},proposal:{start:'2025-01-08',end:null},committed:true,phase:'restart'});assert.deepEqual(resetRange().value,{start:null,end:null});});
test('controlled state proposes while uncontrolled state commits',()=>{const u=createSelection();assert.equal(u.propose('2025-01-10').committed,true);assert.equal(u.read(),'2025-01-10');const c=createSelection({controlled:true,value:'2025-01-01'});assert.deepEqual(c.propose('2025-01-10'),{previous:'2025-01-01',proposal:'2025-01-10',value:'2025-01-01',committed:false,ownership:'controlled'});assert.equal(c.read('2025-01-11'),'2025-01-11');});
test('keyboard and unknown locale/timezone/vendor behavior stay explicit without observations',()=>{const c=loadDateRange();assert.deepEqual(c.keyboard['date-picker'],['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter','Space']);assert.deepEqual(c.keyboard['date-range-picker'],['Enter','Space']);assert.deepEqual(c.unknowns.map(x=>x.field),['localizedLabelsAndCalendarText','calendarMonthAndLocalizedDayLabels','timezoneConversion','vendorCalendarInternals']);assert.equal(JSON.stringify(c).includes('formattedLabel'),false);});
test('validator fails closed for digest and provenance mutations',()=>{for(const mutate of [v=>v.calendar.grid.cells=35,v=>delete v.provenance[0].contractDigest,v=>v.provenance=[]]){const v=structuredClone(loadDateRange());mutate(v);assert.throws(()=>validateDateRange(v),/invalid|provenance|digest/);}});
