import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {clampPage,commitPageInput,derivePaginationState,legacySSRState,loadPaginationState,maxPage,nextPage,paginationState,parsePageInput,previousPage,proposePage,proposePageSize,validatePaginationState} from '../src/kumo/library/pagination-state.mjs';
const contract=JSON.parse(fs.readFileSync('contracts/kumo.observable/v1/components/pagination.json'));

test('artifact is canonical, deterministic, and binds all vectors twice',()=>{const a=derivePaginationState(contract),b=derivePaginationState(contract);assert.deepEqual(loadPaginationState(),a);assert.deepEqual(a,b);assert.equal(JSON.stringify(a),JSON.stringify(b));assert.deepEqual(a.provenance.vectorIds,contract.vectors.map(x=>x.id));});
test('maximum and boundary state are inclusive',()=>{assert.equal(maxPage(35,10),4);assert.equal(maxPage(0,10),1);assert.deepEqual(paginationState({page:1,perPage:10,totalCount:35}),{page:1,perPage:10,totalCount:35,maxPage:4,previousDisabled:true,nextDisabled:false,firstDisabled:true,lastDisabled:false});assert.equal(paginationState({page:4,perPage:10,totalCount:35}).nextDisabled,true);for(const args of [[-1,10],[10,0]])assert.throws(()=>maxPage(...args),/invalid/);});
test('previous, next, and arbitrary targets clamp and controlled calls only propose',()=>{assert.deepEqual(nextPage(2,4),{previous:2,proposal:3,value:2,committed:false,changed:true,ownership:'controlled'});assert.equal(nextPage(4,4).proposal,4);assert.equal(previousPage(1,4).proposal,1);assert.deepEqual(proposePage(2,99,4,{controlled:false}),{previous:2,proposal:4,value:4,committed:true,changed:true,ownership:'uncontrolled'});assert.equal(clampPage(9,4),4);});
test('input parser is strict and Enter/blur commit with clamping',()=>{for(const value of ['99',' 0 ','0003'])assert.notEqual(parsePageInput(value),null);for(const value of ['','1.5','-1','1x',null])assert.equal(parsePageInput(value),null);assert.deepEqual(commitPageInput(2,'99',4),{previous:2,proposal:4,value:2,committed:false,changed:true,ownership:'controlled',input:'4',trigger:'Enter'});assert.equal(commitPageInput(2,'0',4,{trigger:'blur',controlled:false}).value,1);assert.equal(commitPageInput(2,'garbage',4).proposal,null);assert.equal(commitPageInput(2,'3',4,{trigger:'Tab'}).trigger,'ignored');});
test('page-size changes are numeric controlled proposals',()=>{assert.deepEqual(proposePageSize(10,25),{previous:10,proposal:25,value:10,committed:false,changed:true,ownership:'controlled'});assert.equal(proposePageSize(10,25,{controlled:false}).value,25);assert.throws(()=>proposePageSize(10,0),/invalid page size/);});
test('legacy SSR editing state is explicit and hydrates without replacement',()=>assert.deepEqual(legacySSRState(3),{serverEditingPage:1,hydratedEditingPage:3,nodeIdentity:true}));
test('all canonical behavior vectors are represented and repeat identically',()=>{const run=()=>contract.vectors.map(v=>{const p=v.props,m=maxPage(p.totalCount,p.perPage);switch(v.id){case'legacy-page-one':return paginationState(p);case'legacy-page-three-ssr':return legacySSRState(p.page);case'next-controlled':return nextPage(p.page,m);case'boundaries':return nextPage(p.page,m);case'input-enter-clamp':return commitPageInput(p.page,'99',m);case'input-blur-clamp':return commitPageInput(p.page,'0',m,{trigger:'blur'});case'compound-simple-labels':return paginationState(p);case'compound-dropdown-size':return proposePageSize(p.perPage,50);}});const a=run(),b=run();assert.deepEqual(a,b);assert.equal(a[2].proposal,3);assert.equal(a[3].changed,false);assert.equal(a[4].proposal,4);assert.equal(a[5].proposal,1);});
test('unknowns remain explicit and validator fails closed',()=>{const value=loadPaginationState();assert.deepEqual(value.unknowns.map(x=>x.field),['selectPopupPlatformPresentation','invalidPageInputUserFeedback','pageSizePageReset']);for(const mutate of [x=>x.navigation.previous='invented',x=>delete x.provenance.contractDigest,x=>x.provenance.vectorIds.pop()]){const bad=structuredClone(value);mutate(bad);assert.throws(()=>validatePaginationState(bad),/invalid|provenance|digest/);}});
