import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { validateShootout, fanIn, digest, FIXTURE_GATES } from "../shootout/validate.mjs";
const baseline = JSON.parse(readFileSync(new URL("../proof/shootout/baseline/baseline.json", import.meta.url)));
const make = (component="button") => ({schemaVersion:"shootout/v1",axis:"language",language:"typescript",candidateId:"ts-a",framework:"react",component,candidateRevision:"abc",frameworkRevision:"19.2.7",componentRevision:"def",runId:"run-1",evidenceDigest:"a".repeat(64),environmentManifestDigest:baseline.environmentManifestDigest,baseline:{digest:digest(baseline)},gates:Object.fromEntries(FIXTURE_GATES[component].map(g=>[g,"passed"]))});
test("accepts deterministic complete result",()=>assert.equal(validateShootout(make(),{baseline}).valid,true));
test("rejects cross-axis claims",()=>{const x=make();x.architecture="mitosis";assert.match(validateShootout(x).errors.join(),/only the language axis/)});
test("rejects optimistic booleans",()=>{const x=make();x.gates.api=true;assert.match(validateShootout(x).errors.join(),/boolean/)});
test("rejects missing provenance",()=>{const x=make();delete x.runId;assert.match(validateShootout(x).errors.join(),/runId/)});
test("rejects stale baseline hashes",()=>{const x=make();x.baseline.digest="b".repeat(64);assert.match(validateShootout(x,{baseline}).errors.join(),/stale/)});
test("rejects machine paths",()=>{const x=make();x.candidateRevision="/Users/alice/build";assert.match(validateShootout(x).errors.join(),/machine-local/)});
test("fan-in blocks incomplete mandatory gates and winner",()=>{const x=make("select");x.gates.keyboard="not-run";assert.deepEqual(fanIn([x]),{status:"blocked",winnerAllowed:false})});
test("baseline binds current immutable authority without changing it",()=>{const bytes=readFileSync(new URL("../generated/browser-evidence/authority.json",import.meta.url));assert.equal(createHash("sha256").update(bytes).digest("hex"),baseline.authority.manifestSha256);assert.equal(baseline.authority.coverage,"164/164")});
