import React from'react';
import{mkdir,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';import{resolve}from'node:path';
import{renderToString}from'react-dom/server';
import{loadContracts}from'../observable-contracts.mjs';
import{fixtureElement}from'../observable-runner.mjs';
import{runObservableBrowser}from'../observable-browser-runner.mjs';

export const collectionComponents=['autocomplete','combobox','command-palette','select'];
const modulePath=name=>name==='command-palette'?'command-palette':name;
const eventValue=value=>Array.isArray(value)?value.map(x=>x&&typeof x==='object'?x.id:x).join(','):value&&typeof value==='object'?value.id:value;
const serialise=s=>JSON.stringify(s).replace(/</g,'\\u003c');
const root=resolve(import.meta.dirname,'../..');

async function canonicalComponent(contract){const mod=await import(`@cloudflare/kumo/components/${modulePath(contract.component)}`);return{mod,Component:mod[contract.publicApi.exports[0]]}}
function callbacks(component,log){if(component==='autocomplete'||component==='combobox')return{onValueChange:value=>log(`value:${eventValue(value)}`),onOpenChange:open=>log(`open:${open}`)};if(component==='command-palette')return{itemToStringValue:value=>String(value),onValueChange:value=>log(`value:${eventValue(value)}`),onOpenChange:open=>log(`open:${open}`),onItemHighlighted:value=>log(`highlight:${eventValue(value)}`),onSelect:value=>log(`select:${eventValue(value)}`)};return{onValueChange:value=>log(`value-change:${eventValue(value)}`),onOpenChange:open=>log(`open-change:${open}`)}}
function elementFor(vector,Component,props){return vector.fixture?fixtureElement(vector.fixture,Component,props):React.createElement(Component,props)}
function serverElement(contract,vector,Component){const props={...vector.props,...callbacks(contract.component,()=>{})};if(contract.component==='command-palette'&&vector.id==='open-search-close')return React.createElement(Component.Root,props,React.createElement(Component.Input,{placeholder:'Search'}),React.createElement(Component.List,null,React.createElement(Component.Results,null,item=>React.createElement(Component.Item,{value:item},String(item)))));return elementFor(vector,Component,props)}

export async function renderCollectionSsr(contracts=loadContracts().filter(c=>collectionComponents.includes(c.component))){const results=[];for(const contract of contracts){const{Component}=await canonicalComponent(contract);for(const vector of contract.vectors.filter(v=>!v.actions?.length)){const first=renderToString(serverElement(contract,vector,Component)),second=renderToString(serverElement(contract,vector,Component));if(first!==second)throw Error(`${contract.component}/${vector.id}: nondeterministic SSR`);results.push({component:contract.component,id:vector.id,html:first})}}return results}

function clientSource(spec){return `import React,{useState}from'react';import{hydrateRoot}from'react-dom/client';import*as M from'@cloudflare/kumo/components/${modulePath(spec.component)}';const s=${serialise(spec)};globalThis.__events=[];const val=x=>Array.isArray(x)?x.map(y=>y&&typeof y==='object'?y.id:y).join(','):x&&typeof x==='object'?x.id:x,log=x=>globalThis.__events.push(x);function resolve(p){let C=M[s.exportName];if(p!=='root')for(const k of p.slice(1).split('.'))C=C[k];return C}function node(n,C,rootProps){if('text'in n)return n.text;let X=resolve(n.export),p=n.export==='root'?{...rootProps,...n.props}:n.props;return React.createElement(X,p,...n.children.map(x=>node(x,C,rootProps)))}function App(){let[p,setP]=useState(()=>s.component==='autocomplete'||s.component==='combobox'?{...s.props,value:null}:s.props),cb=s.component==='select'?{onValueChange:x=>{log('value-change:'+val(x));if(!('value'in s.props))setP(q=>({...q,value:x}))},onOpenChange:x=>{log('open-change:'+x);if(!('open'in s.props))setP(q=>({...q,open:x}))}}:s.component==='command-palette'?{onValueChange:x=>{log('value:'+val(x));setP(q=>({...q,value:x}))},onOpenChange:x=>{log('open:'+x);setP(q=>({...q,open:x}))},onItemHighlighted:x=>log('highlight:'+val(x)),onSelect:x=>log('select:'+val(x)),itemToStringValue:x=>String(x)}:{onValueChange:x=>{log('value:'+val(x));setP(q=>({...q,value:x}))},onOpenChange:x=>{log('open:'+x);setP(q=>({...q,open:x}))}};let C=M[s.exportName],props={...p,...cb};if(s.component==='command-palette'&&s.id==='open-search-close')return React.createElement(C.Root,props,React.createElement(C.Input,{placeholder:'Search'}),React.createElement(C.List,null,React.createElement(C.Results,null,item=>React.createElement(C.Item,{value:item},String(item)))));return s.fixture?node(s.fixture,C,props):React.createElement(C,props)}hydrateRoot(document.querySelector('#app'),React.createElement('section',{id:'v0'},React.createElement(App)));globalThis.__ready=true;`}
function snapshotExpression(){return `(()=>{let root=document.querySelector('#v0'),input=root.querySelector('input')||document.querySelector('input[role=combobox]'),trigger=root.querySelector('button,[role=combobox]')||document.querySelector('button[role=combobox]'),control=root.querySelector('[role=combobox]')||document.querySelector('[role=combobox]'),list=document.querySelector('[role=listbox]'),options=[...document.querySelectorAll('[role=option]')],selected=options.filter(x=>x.getAttribute('aria-selected')==='true'||x.dataset.selected!==undefined),highlight=options.find(x=>x.dataset.highlighted!==undefined||x.getAttribute('aria-current')==='true');return{value:input?.value??trigger?.textContent?.trim()??[...globalThis.__events].reverse().find(x=>x.startsWith('value:'))?.slice(6)??null,open:control?.getAttribute('aria-expanded')==='true',events:globalThis.__events,active:document.activeElement===input?'input':document.activeElement===trigger?'button':document.activeElement===list?'listbox':document.activeElement===document.body?'none':document.activeElement?.getAttribute('role')||document.activeElement?.tagName?.toLowerCase(),selectedIds:selected.map(x=>x.textContent.trim().toLowerCase()),disabledOptionSelectable:options.some(x=>(x.disabled||x.getAttribute('aria-disabled')==='true')&&(x.getAttribute('aria-selected')==='true'||x.dataset.selected!==undefined)),disabledSkipped:!highlight||highlight.getAttribute('aria-disabled')!=='true',highlightScrolled:!highlight||(()=>{let r=highlight.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight})(),loading:!!document.querySelector('[data-loading],[aria-busy=true]')}})()`}
function assertState(actual,expected){for(const[k,v]of Object.entries(expected.state||{})){if(k==='selectedIds'){const normal=v.map(x=>String(x).toLowerCase());if(JSON.stringify(actual.selectedIds)!==JSON.stringify(normal))throw Error(`${k}: ${JSON.stringify(actual.selectedIds)}`)}else if(k in actual&&actual[k]!==v)throw Error(`${k}: ${JSON.stringify(actual[k])}`)}if(expected.events&&JSON.stringify(actual.events)!==JSON.stringify(expected.events))throw Error(`events: ${JSON.stringify(actual.events)}`);if(expected.focus&&actual.active!==expected.focus.replace('[role=','').replace(']',''))throw Error(`focus: ${actual.active}`)}
export async function runCollectionBrowserContracts(contracts=loadContracts().filter(c=>collectionComponents.includes(c.component))){const results=[],diagnostics=[];for(const contract of contracts)for(const vector of contract.vectors){const{Component}=await canonicalComponent(contract),spec={component:contract.component,exportName:contract.publicApi.exports[0],id:vector.id,props:vector.props,fixture:vector.fixture},html=renderToString(React.createElement('section',{id:'v0'},serverElement(contract,vector,Component)));let run;try{run=await runObservableBrowser({name:`collections-${contract.component}-${vector.id}`,entrySource:clientSource(spec),html,vectors:[{...vector,component:contract.component}],runVector:async(api,current,i)=>{for(const action of current.actions||[]){let a={...action};if(!a.selector)a.selector=contract.component==='select'?'button':'input';if((contract.component==='select'||contract.component==='command-palette')&&(a.selector==='[role=option]'||a.selector==='input'))a.scope='document';try{await api.action(i,a)}catch(error){throw Error(`action ${JSON.stringify(a)}: ${error.message}`)}if(action.checkpoint)assertState(await api.evaluate(snapshotExpression()),action.checkpoint)}const observed=await api.evaluate(snapshotExpression());assertState(observed,current.expected);return{component:contract.component,id:current.id,passed:true}}})}catch(error){throw Error(`${contract.component}/${vector.id}: ${error.message}`)}results.push(...run.results);diagnostics.push(...run.diagnostics)}const receipt={schemaVersion:1,status:'passed',family:'collections',canonical:'@cloudflare/kumo@2.5.2',counts:{passed:results.length,failed:0,blocked:0},components:collectionComponents,cells:results.map(x=>({component:x.component,vector:x.id,status:'passed'}))};return{results,browserCells:results.length,diagnostics,capabilities:['trusted-pointer','trusted-keyboard','trusted-typeahead','native-focus','native-scroll','document-portal','ssr-hydration-equality'],receipt}}
export async function writeCollectionReceipt(result){if(result.diagnostics.length||result.browserCells!==result.receipt.counts.passed)throw Error('refusing non-green collections receipt');const receipt=structuredClone(result.receipt);receipt.digest=createHash('sha256').update(JSON.stringify(receipt)).digest('hex');const dir=resolve(root,'proof/observable-contracts/families');await mkdir(dir,{recursive:true});await writeFile(resolve(dir,'collections.json'),JSON.stringify(receipt,null,2)+'\n');return receipt}

if(import.meta.url===`file://${process.argv[1]}`){if(!process.argv.includes('--browser')){const r=await renderCollectionSsr();console.log(JSON.stringify({family:'collections',ssrCells:r.length},null,2))}else{const first=await runCollectionBrowserContracts(),second=await runCollectionBrowserContracts();if(JSON.stringify(first.results)!==JSON.stringify(second.results)||first.diagnostics.length||second.diagnostics.length)throw Error('collections repeat verification mismatch');if(process.argv.includes('--write'))await writeCollectionReceipt(second);console.log(JSON.stringify(second,null,2))}}
