import React,{useState}from'react';
import{renderToString}from'react-dom/server';
import{loadContracts}from'../observable-contracts.mjs';
import{runObservableBrowser}from'../observable-browser-runner.mjs';

export const layerNames=['dialog','dropdown-menu','popover'];
const importName=x=>x==='dropdown-menu'?'dropdown':x;
const vector=(c,v)=>({component:c.component,id:v.id,props:v.props,fixture:v.fixture,actions:v.actions||[],expected:v.expected});

function member(K,name){if(name==='root')return K;if(!name.startsWith('.'))throw Error(`invalid fixture export ${name}`);return name.slice(1).split('.').reduce((x,key)=>x?.[key],K)}
function fixtureNode(node,K,decorate=()=>({})){if(Object.hasOwn(node,'text'))return node.text;const C=member(K,node.export);if(!C)throw Error(`missing canonical compound export ${node.export}`);return React.createElement(C,{...node.props,...decorate(node)},...(node.children||[]).map((child,index)=>React.createElement(React.Fragment,{key:index},fixtureNode(child,K,decorate))))}
function fixtureProps(spec,{client=false,log=()=>{}}={}){const controlled=Object.hasOwn(spec.props,'open');return node=>{if(node!==spec.fixture)return{};return{...spec.props,...client&&{onOpenChange:open=>log(`${spec.component==='popover'?'open-change':'open'}:${open}`)},...controlled&&{open:spec.props.open}}}}
export function renderLayerFixture(spec,K){return fixtureNode(spec.fixture,K,fixtureProps(spec))}
export async function renderLayerSsr(contracts=loadContracts().filter(x=>layerNames.includes(x.component))){const rows=[];for(const contract of contracts)for(const value of contract.vectors){const spec=vector(contract,value),module=await import(`@cloudflare/kumo/components/${importName(spec.component)}`),K=module[contract.publicApi.exports[0]];rows.push({...spec,html:renderToString(React.createElement('section',{id:`v${rows.length}`},renderLayerFixture(spec,K)))})}return rows}

function clientSource(vectors){return `import React,{useState}from'react';import{hydrateRoot}from'react-dom/client';import{Dialog}from'@cloudflare/kumo/components/dialog';import{Popover}from'@cloudflare/kumo/components/popover';import{DropdownMenu}from'@cloudflare/kumo/components/dropdown';const S=${JSON.stringify(vectors)},C={dialog:Dialog,popover:Popover,'dropdown-menu':DropdownMenu};globalThis.__events={};function member(K,n){return n==='root'?K:n.slice(1).split('.').reduce((x,k)=>x[k],K)}function F({s,i}){let controlled=Object.hasOwn(s.props,'open'),[open,setOpen]=useState(s.props.open),log=x=>(globalThis.__events[i]??=[]).push(x),decorate=n=>n!==s.fixture?{}:{...s.props,onOpenChange:x=>{log((s.component==='popover'?'open-change':'open')+':'+x);if(!controlled)setOpen(x)},...controlled?{open}:{}},node=n=>Object.hasOwn(n,'text')?n.text:React.createElement(member(C[s.component],n.export),{...n.props,...decorate(n)},...(n.children||[]).map((x,k)=>React.createElement(React.Fragment,{key:k},node(x))));return node(s.fixture)}function App(){return React.createElement(React.Fragment,null,...S.map((s,i)=>React.createElement('section',{id:'v'+i,key:i},React.createElement(F,{s,i}))));}hydrateRoot(document.querySelector('#app'),React.createElement(App));globalThis.__ready=true;`}
function inspectExpression(i){return `(()=>{let v=document.querySelector('#v${i}'),trigger=v.querySelector('button'),layer=[...document.querySelectorAll('[role=dialog],[role=menu],[data-kumo-part=content]')].find(x=>!v.contains(x)||x!==trigger);return{open:trigger?.getAttribute('aria-expanded')==='true'||!!layer,portal:!!layer&&!v.contains(layer),role:layer?.getAttribute('role'),active:document.activeElement===trigger?'button':document.activeElement?.getAttribute('role')?('[role='+document.activeElement.getAttribute('role')+']'):document.activeElement?.tagName?.toLowerCase(),events:globalThis.__events[${i}]||[],positionMethod:layer?.style.position||layer?.parentElement?.style.position,side:layer?.getAttribute('data-side'),align:layer?.getAttribute('data-align')}})()`}
function check(g,e){if(e.events&&JSON.stringify(g.events)!==JSON.stringify(e.events))throw Error(`events ${JSON.stringify(g.events)}`);for(const[k,w]of Object.entries(e.state||{}))if(w!==undefined&&g[k]!==w)throw Error(`${k} ${JSON.stringify(g[k])}`);if(e.focus&&g.active!==e.focus)throw Error(`focus ${g.active}`)}
export async function runLayersBrowserContracts(contracts=loadContracts().filter(x=>layerNames.includes(x.component))){const vectors=contracts.flatMap(c=>c.vectors.map(v=>vector(c,v))),ssr=await renderLayerSsr(contracts),html=ssr.map(x=>x.html).join('');return runObservableBrowser({name:'layers',entrySource:clientSource(vectors),html,vectors,runVector:async(api,s,i)=>{for(const action of s.actions){let a={...action};if(a.type==='click'&&a.target!=null)a={...a,scope:'document',selector:'button,[role=menuitem]'};if(a.type==='key'&&!a.selector)a={...a,scope:'document',selector:'[role=dialog],[role=menu],[data-kumo-part=content],button'};await api.action(i,a);if(action.checkpoint)check(await api.evaluate(inspectExpression(i)),action.checkpoint)}const got=await api.evaluate(inspectExpression(i));check(got,s.expected);return{component:s.component,id:s.id,passed:true,portalDocumentScope:got.portal||!got.open}}})}
if(import.meta.url===`file://${process.argv[1]}`)console.log(JSON.stringify(await runLayersBrowserContracts(),null,2));
