import React from'react';
import{mkdir,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';import{resolve}from'node:path';
import{renderToString}from'react-dom/server';
import{loadContracts}from'../observable-contracts.mjs';
import{runObservableBrowser}from'../observable-browser-runner.mjs';

const root=resolve(import.meta.dirname,'../..');
export const layerNames=['dialog','dropdown-menu','popover'];
const importName=x=>x==='dropdown-menu'?'dropdown':x;
const vector=(c,v)=>({component:c.component,id:v.id,props:v.props,fixture:v.fixture,actions:v.actions||[],expected:v.expected});

function member(K,name){if(name==='root')return K;if(!name.startsWith('.'))throw Error(`invalid fixture export ${name}`);return name.slice(1).split('.').reduce((x,key)=>x?.[key],K)}
function fixtureNode(node,K,decorate=()=>({})){if(Object.hasOwn(node,'text'))return node.text;const C=member(K,node.export);if(!C)throw Error(`missing canonical compound export ${node.export}`);const props={...decorate(node),...node.props},children=(node.children||[]).map(child=>fixtureNode(child,K,decorate));return React.createElement(C,props,...children)}
function fixtureProps(spec,{client=false,log=()=>{}}={}){const controlled=Object.hasOwn(spec.props,'open');return node=>{if(spec.component==='dropdown-menu'&&node.export==='root')return{...client&&{onOpenChange:open=>log(`open-change:${open}`)}};if(node!==spec.fixture)return{};return{...spec.props,...client&&{onOpenChange:open=>log(`${spec.component==='popover'?'open-change':'open'}:${open}`)},...controlled&&{open:spec.props.open}}}}
export function renderLayerFixture(spec,K){return fixtureNode(spec.fixture,K,fixtureProps(spec))}
export async function renderLayerSsr(contracts=loadContracts().filter(x=>layerNames.includes(x.component))){const rows=[];for(const contract of contracts)for(const value of contract.vectors){const spec=vector(contract,value),module=await import(`@cloudflare/kumo/components/${importName(spec.component)}`),K=module[contract.publicApi.exports[0]];rows.push({...spec,html:renderToString(React.createElement('section',{id:'v0'},renderLayerFixture(spec,K)))})}return rows}

function clientSource(s){return `import React,{useState}from'react';import{hydrateRoot}from'react-dom/client';import{Dialog}from'@cloudflare/kumo/components/dialog';import{Popover}from'@cloudflare/kumo/components/popover';import{DropdownMenu}from'@cloudflare/kumo/components/dropdown';const s=${JSON.stringify(s)},C={dialog:Dialog,popover:Popover,'dropdown-menu':DropdownMenu};globalThis.__events=[];function member(K,n){return n==='root'?K:n.slice(1).split('.').reduce((x,k)=>x[k],K)}function F(){let controlled=Object.hasOwn(s.props,'open'),[open,setOpen]=useState(s.props.open),log=x=>globalThis.__events.push(x),decorate=n=>s.component==='dropdown-menu'&&n.export==='root'?{onOpenChange:x=>log('open-change:'+x)}:n!==s.fixture?{}:{...s.props,onOpenChange:x=>{log((s.component==='popover'?'open-change':'open')+':'+x);if(!controlled)setOpen(x)},...controlled?{open}:{}},node=n=>{if(Object.hasOwn(n,'text'))return n.text;let K=C[s.component],X=member(K,n.export),p={...decorate(n),...n.props,...s.component==='dropdown-menu'&&n.export==='.Item'?{onClick:()=>log('select:'+n.children.map(x=>x.text||'').join(''))}:{}},children=(n.children||[]).map(x=>node(x));return React.createElement(X,p,...children)};return node(s.fixture)}hydrateRoot(document.querySelector('#app'),React.createElement('section',{id:'v0'},React.createElement(F)));globalThis.__ready=true;`}
function inspectExpression(controlled=false){return `(()=>{let v=document.querySelector('#v0'),trigger=v.querySelector('button'),layers=[...document.querySelectorAll('[role=dialog],[role=menu],[data-kumo-part=content]')],layer=layers.find(x=>!v.contains(x)),expanded=trigger?.getAttribute('aria-expanded')==='true';return{open:expanded,portal:!!layer&&!v.contains(layer),portalCount:layers.filter(x=>!v.contains(x)).length,role:layer?.getAttribute('role'),active:document.activeElement===trigger?'button':document.activeElement?.getAttribute('role')?('[role='+document.activeElement.getAttribute('role')+']'):document.activeElement?.tagName?.toLowerCase(),events:globalThis.__events,positionMethod:layer?.style.position||layer?.parentElement?.style.position,side:layer?.getAttribute('data-side'),align:layer?.getAttribute('data-align'),disabledSkipped:document.activeElement?.textContent?.trim()!=='Blocked',submenuOpen:document.querySelectorAll('[role=menu]').length>1,controlled:${controlled}}})()`}
function check(g,e){if(e.events&&JSON.stringify(g.events)!==JSON.stringify(e.events))throw Error(`events ${JSON.stringify(g.events)}`);for(const[k,w]of Object.entries(e.state||{}))if(w!==undefined&&g[k]!==w)throw Error(`${k} ${JSON.stringify(g[k])}`);if(e.focus&&g.active!==e.focus)throw Error(`focus ${g.active}`)}
function actionFor(s,a){if(a.type==='click'&&a.target!=null)return{...a,scope:'document',selector:'button,[role=menuitem]'};if(a.type==='click'&&a.selector?.startsWith('[role=')||a.type==='click'&&a.selector?.startsWith('[data-kumo-part='))return{...a,scope:'document'};if((a.type==='key'||a.type==='type')&&!a.selector)return{...a,scope:'document',selector:'[role=dialog],[role=menu],[data-kumo-part=content],button'};return a}
export async function runLayersBrowserContracts(contracts=loadContracts().filter(x=>layerNames.includes(x.component))){const vectors=contracts.flatMap(c=>c.vectors.map(v=>vector(c,v))),ssr=await renderLayerSsr(contracts),results=[],diagnostics=[],telemetry={phases:{},vectors:[]},capabilities=new Set();for(let n=0;n<vectors.length;n++){const s=vectors[n],row=ssr[n];let run;try{run=await runObservableBrowser({name:`layers-${s.component}-${s.id}`,entrySource:clientSource(s),html:row.html,vectors:[s],runVector:async(api,x,i)=>{for(const action of x.actions){await api.action(i,actionFor(x,action));if(action.checkpoint)check(await api.evaluate(inspectExpression(Object.hasOwn(x.props,'open'))),action.checkpoint)}const got=await api.evaluate(inspectExpression(Object.hasOwn(x.props,'open')));check(got,x.expected);if(got.open&&!got.portal)throw Error('open layer was not portalled to document');if(got.portalCount>1)throw Error(`unexpected portal count ${got.portalCount}`);return{component:x.component,id:x.id,passed:true,portalDocumentScope:got.portal||!got.open}}})}catch(error){throw Error(`${s.component}/${s.id}: ${error.message}`)}results.push(...run.results);diagnostics.push(...run.diagnostics);for(const[p,ms]of Object.entries(run.telemetry.phases))telemetry.phases[p]=(telemetry.phases[p]||0)+ms;telemetry.vectors.push(...run.telemetry.vectors);run.capabilities.forEach(x=>capabilities.add(x))}return{results,browserCells:results.length,diagnostics,telemetry,capabilities:[...capabilities],receipt:{schemaVersion:1,status:'passed',family:'layers',canonical:'@cloudflare/kumo@2.5.2',counts:{passed:results.length,failed:0,blocked:0},components:layerNames,cells:results.map(x=>({component:x.component,vector:x.id,status:'passed'}))}}}
export async function writeLayersReceipt(result){if(result.diagnostics.length||result.browserCells!==result.results.length||result.results.some(x=>!x.passed))throw Error('refusing to write non-green layers receipt');const receipt=structuredClone(result.receipt);receipt.digest=createHash('sha256').update(JSON.stringify(receipt)).digest('hex');const dir=resolve(root,'proof/observable-contracts/families');await mkdir(dir,{recursive:true});await writeFile(resolve(dir,'layers.json'),JSON.stringify(receipt,null,2)+'\n');return receipt}
if(import.meta.url===`file://${process.argv[1]}`){const result=await runLayersBrowserContracts();if(process.argv.includes('--write'))await writeLayersReceipt(result);console.log(JSON.stringify(result,null,2))}
