import React,{useState}from'react';
import{mkdir,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';import{resolve}from'node:path';
import{renderToString}from'react-dom/server';
import{loadContracts}from'../observable-contracts.mjs';
import{runObservableBrowser}from'../observable-browser-runner.mjs';
const root=resolve(import.meta.dirname,'../..');const names=['button','date-picker','date-range-picker','pagination','toasty'];
const spec=(c,v)=>({component:c.component,id:v.id,props:v.props,actions:v.actions||[],expected:v.expected});
const importName=x=>x.component==='toasty'?'toast':x.component;
const date=x=>{if(!x)return undefined;let[y,m,d]=x.split('-').map(Number);return new Date(y,m-1,d,12)};
const day=x=>x instanceof Date?`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`:null;
function mappedProps(s){if(s.component!=='date-picker')return s.props;let{selectedDate,defaultMonthDate,disabledBeforeDate,disabledAfterDate,...p}=s.props,disabled=[];if(disabledBeforeDate)disabled.push({before:date(disabledBeforeDate)});if(disabledAfterDate)disabled.push({after:date(disabledAfterDate)});return{...p,...selectedDate&&{selected:date(selectedDate)},...defaultMonthDate&&{defaultMonth:date(defaultMonthDate)},...disabled.length&&{disabled}}}
function serverElement(s,C,module){let p=mappedProps(s);if(s.component==='button'){const button=React.createElement(C,p);return React.createElement('form',null,button)}if(s.component==='date-picker')return React.createElement(C,{...p,onChange:()=>{}});if(s.component==='date-range-picker')return React.createElement(C,{...p,onStartDateChange:()=>{},onEndDateChange:()=>{}});if(s.component==='pagination'){const base={...p,setPage:()=>{}};if(!p.fixtureMode)return React.createElement(C,base);return React.createElement(C,base,p.fixtureMode==='simple'?React.createElement(C.Controls,{controls:'simple'}):React.createElement(React.Fragment,null,React.createElement(C.PageSize,{value:p.perPage,onChange:()=>{}}),React.createElement(C.Controls,{pageSelector:'dropdown'})))}if(s.component==='toasty')return React.createElement(C,{toastManager:module.createKumoToastManager()},React.createElement('div',null,p.children,React.createElement('button',{'data-notify':true},'Notify')));throw Error(`unwired server component ${s.component}`)}
function observeSource(s){return `import React,{useState}from'react';import{hydrateRoot}from'react-dom/client';import*as M from'@cloudflare/kumo/components/${importName(s)}';const s=${JSON.stringify(s)};globalThis.__events=[];const date=x=>{if(!x)return undefined;let[y,m,d]=x.split('-').map(Number);return new Date(y,m-1,d,12)},day=x=>x instanceof Date?\`${'${x.getFullYear()}'}-${'${String(x.getMonth()+1).padStart(2,"0")}' }-${'${String(x.getDate()).padStart(2,"0")}' }\`:null;function props(){if(s.component!=='date-picker')return s.props;let{selectedDate,defaultMonthDate,disabledBeforeDate,disabledAfterDate,...p}=s.props,disabled=[];if(disabledBeforeDate)disabled.push({before:date(disabledBeforeDate)});if(disabledAfterDate)disabled.push({after:date(disabledAfterDate)});return{...p,...selectedDate&&{selected:date(selectedDate)},...defaultMonthDate&&{defaultMonth:date(defaultMonthDate)},...disabled.length&&{disabled}}}function F(){let[p,setP]=useState(props()),log=x=>globalThis.__events.push(x);if(s.component==='pagination'){let base={...p,setPage:x=>{log('page:'+x);setP(q=>({...q,page:x}))}};if(!p.fixtureMode)return React.createElement(M.Pagination,base);return React.createElement(M.Pagination,base,p.fixtureMode==='simple'?React.createElement(M.Pagination.Controls,{controls:'simple'}):React.createElement(React.Fragment,null,React.createElement(M.Pagination.PageSize,{value:p.perPage,onChange:x=>log('size:'+x)}),React.createElement(M.Pagination.Controls,{pageSelector:'dropdown'})))}if(s.component==='toasty'){let manager=M.createKumoToastManager();return React.createElement(M.Toasty,{toastManager:manager},React.createElement('div',null,s.props.children,React.createElement('button',{'data-notify':true,onClick:()=>{log('notify');manager.add({title:'Saved',description:'Changes saved',actions:[{children:'Undo','data-toast-action':true,onClick:()=>log('action')} ]})}},'Notify')))}if(s.component==='button')return React.createElement('form',{onSubmit:e=>{e.preventDefault();log('submit')}},React.createElement(M.Button,{...p,onClick:()=>log('click')}));if(s.component==='date-picker')return React.createElement(M.DatePicker,{...p,onChange:x=>{let v=day(x);log('change:'+v);setP(q=>({...q,selected:x}))}});if(s.component==='date-range-picker')return React.createElement(M.DateRangePicker,{...p,onStartDateChange:x=>log('start:'+(x?'date':'null')),onEndDateChange:x=>log('end:'+(x?'date':'null'))});throw Error('unwired misc component')}hydrateRoot(document.querySelector('#app'),React.createElement('section',{id:'v0'},React.createElement(F)));globalThis.__ready=true;`}
function value(g,e){for(const[k,v]of Object.entries(e.state||{})){if(k==='page'&&g.input!==String(v))throw Error(`page ${g.input}`);if(k==='input'&&g.input!==v)throw Error(`input ${g.input}`);if(k==='visible'&&g.visible!==v)throw Error(`visible ${g.visible}`);if(k==='announcement'&&!g.text.replace(/\s+/g,' ').includes(v))throw Error(`announcement ${g.text}`)}}
export async function runMiscBrowserContracts(contracts=loadContracts().filter(x=>names.includes(x.component))){let results=[],diagnostics=[],vectors=contracts.flatMap(c=>c.vectors.map(v=>spec(c,v)));for(const s of vectors){let mod=await import(`@cloudflare/kumo/components/${importName(s)}`),C=mod[contracts.find(x=>x.component===s.component).publicApi.exports[0]],body=serverElement(s,C,mod),html=renderToString(React.createElement('section',{id:'v0'},body));let r;try{r=await runObservableBrowser({name:`misc-${s.component}-${s.id}`,entrySource:observeSource(s),html,vectors:[s],runVector:async(api,x,i)=>{for(const a of x.actions){let action=a;if(x.component==='date-picker'&&a.type==='click'&&a.selector?.startsWith('[data-day='))action={...a,selector:a.selector+' button'};else if(x.component==='date-range-picker'&&a.type==='click'&&Number.isInteger(a.target))action={...a,selector:'button'};else if(x.component==='date-range-picker'&&a.selector==='[data-reset]'){await api.evaluate(`(()=>{const button=[...document.querySelectorAll('#v0 button')].find(x=>x.textContent.trim()==='Reset Dates');if(!button)throw Error('Reset Dates button missing');button.setAttribute('data-observable-reset','')})()`);action={...a,selector:'[data-observable-reset]'}}await api.action(i,action);if(a.checkpoint){let g=await api.evaluate(`(()=>{let b=document.querySelector('#v0');return{visible:!!document.querySelector('[data-toast-title]'),text:document.body.innerText,input:b.querySelector('input')?.value,events:globalThis.__events}})()`);value(g,a.checkpoint)}}let g=await api.evaluate(`(()=>{let b=document.querySelector('#v0');return{visible:!!document.querySelector('[data-toast-title]'),text:document.body.innerText,input:b.querySelector('input')?.value,events:globalThis.__events}})()`);value(g,x.expected);if(JSON.stringify(g.events)!==JSON.stringify(x.expected.events||[]))throw Error(`events ${JSON.stringify(g.events)}`);return{component:x.component,id:x.id,passed:true}}})}catch(error){throw Error(`${s.component}/${s.id}: ${error.message}`)}results.push(...r.results);diagnostics.push(...r.diagnostics)}return{results,browserCells:results.length,diagnostics,receipt:{schemaVersion:1,status:'passed',family:'misc',canonical:'@cloudflare/kumo@2.5.2',counts:{passed:results.length,failed:0,blocked:0},components:names,cells:results.map(x=>({component:x.component,vector:x.id,status:'passed'}))}}}
export async function writeMiscReceipt(result){const receipt=structuredClone(result.receipt);receipt.digest=createHash('sha256').update(JSON.stringify(receipt)).digest('hex');const dir=resolve(root,'proof/observable-contracts/families');await mkdir(dir,{recursive:true});await writeFile(resolve(dir,'misc.json'),JSON.stringify(receipt,null,2)+'\n');return receipt}
if(import.meta.url===`file://${process.argv[1]}`){const result=await runMiscBrowserContracts();if(process.argv.includes('--write'))await writeMiscReceipt(result);console.log(JSON.stringify(result,null,2))}
