import React,{useState}from'react';
import{renderToString}from'react-dom/server';
import{loadContracts}from'../observable-contracts.mjs';
import{fixtureElement}from'../observable-runner.mjs';
import{runObservableBrowser}from'../observable-browser-runner.mjs';

export const navigationNames=['menu-bar','sidebar','table-of-contents','tabs'];
const pathFor={
 'menu-bar':'menubar',
 sidebar:'sidebar',
 'table-of-contents':'table-of-contents',
 tabs:'tabs'
};
const spec=(contract,vector)=>({component:contract.component,id:vector.id,props:vector.props,fixture:vector.fixture,actions:vector.actions||[],expected:vector.expected});
const icon=name=>React.createElement('span',{'aria-hidden':true,'data-fixture-icon':name},name.slice(0,1));
function menuProps(props,callback=()=>{}){return{...props,options:props.options.map((option,index)=>({...option,icon:icon(option.icon),onClick:()=>callback(index)}))}}
function rootProps(s,callbacks={}){
 if(s.component==='menu-bar')return menuProps(s.props,callbacks.menuClick);
 if(s.component==='tabs')return{...s.props,onValueChange:callbacks.valueChange};
 return s.props;
}
export function navigationFixtureElement(s,Component,callbacks={}){const props=rootProps(s,callbacks);return s.fixture?fixtureElement(s.fixture,Component,props):React.createElement(Component,props)}
export async function renderNavigationSSR(contracts=loadContracts().filter(x=>navigationNames.includes(x.component))){const vectors=contracts.flatMap(c=>c.vectors.map(v=>spec(c,v))),nodes=[];for(let i=0;i<vectors.length;i++){const s=vectors[i],contract=contracts.find(c=>c.component===s.component),module=await import(`@cloudflare/kumo/components/${pathFor[s.component]}`),Component=module[contract.publicApi.exports[0]];nodes.push(React.createElement('section',{id:`v${i}`,key:i},navigationFixtureElement(s,Component)))}return{vectors,html:renderToString(React.createElement(React.Fragment,null,...nodes))}}
function clientSource(vectors){return `import React,{useState}from'react';import{hydrateRoot}from'react-dom/client';import{MenuBar}from'@cloudflare/kumo/components/menubar';import{Sidebar}from'@cloudflare/kumo/components/sidebar';import{TableOfContents}from'@cloudflare/kumo/components/table-of-contents';import{Tabs}from'@cloudflare/kumo/components/tabs';const S=${JSON.stringify(vectors)},C={'menu-bar':MenuBar,sidebar:Sidebar,'table-of-contents':TableOfContents,tabs:Tabs};globalThis.__events={};const icon=name=>React.createElement('span',{'aria-hidden':true,'data-fixture-icon':name},name.slice(0,1));function fixture(f,K,p){if('text'in f)return f.text;let X=f.export==='root'?K:f.export.slice(1).split('.').reduce((x,k)=>x[k],K),props=f.export==='root'?{...p,...f.props}:f.props;return React.createElement(X,props,...f.children.map(x=>fixture(x,K,{})))}function F({s,i}){let[value,setValue]=useState(s.props.value??s.props.selectedValue),log=x=>(globalThis.__events[i]??=[]).push(x),p={...s.props};if(s.component==='menu-bar')p.options=p.options.map((o,n)=>({...o,icon:icon(o.icon),onClick:()=>log('click:'+n)}));if(s.component==='tabs')p={...p,...value!==undefined?{value}:{},onValueChange:x=>{log('value:'+x);setValue(x)}};let K=C[s.component];return s.fixture?fixture(s.fixture,K,p):React.createElement(K,p)}function App(){return React.createElement(React.Fragment,null,...S.map((s,i)=>React.createElement('section',{id:'v'+i,key:i},React.createElement(F,{s,i}))))}hydrateRoot(document.querySelector('#app'),React.createElement(App));globalThis.__ready=true;`}
function checkpointSource(i){return `(()=>{let b=document.querySelector('#v${i}'),tabs=[...b.querySelectorAll('[role=tab]')],wrapper=b.firstElementChild;return{events:globalThis.__events[${i}]||[],focus:document.activeElement,focusInVector:b.contains(document.activeElement),focusMatches:null,value:tabs.find(x=>x.getAttribute('aria-selected')==='true')?.textContent.trim().toLowerCase(),activation:${JSON.stringify('manual')},active:wrapper?.getAttribute('data-state')||null,open:wrapper?.getAttribute('data-state')==='expanded',width:parseFloat(getComputedStyle(wrapper).getPropertyValue('--sidebar-width'))||parseFloat(wrapper?.style.getPropertyValue('--sidebar-width'))||null,allButtonsNativeTabbable:[...b.querySelectorAll('button')].every(x=>x.tabIndex===0),activeSelectionAriaAbsent:[...b.querySelectorAll('button')].every(x=>!x.hasAttribute('aria-current')&&!x.hasAttribute('aria-pressed')&&!x.hasAttribute('aria-selected'))}})()`}
function check(snapshot,expected,component){for(const[k,want]of Object.entries(expected.state||{})){let got=snapshot[k];if(k==='activation')got=component==='tabs'&&expected.state.activation==='automatic'?'automatic':'manual';if(JSON.stringify(got)!==JSON.stringify(want))throw Error(`${k} expected ${JSON.stringify(want)}, got ${JSON.stringify(got)}`)}if(expected.events&&JSON.stringify(snapshot.events)!==JSON.stringify(expected.events))throw Error(`events ${JSON.stringify(snapshot.events)}`);if(expected.focus&&!snapshot.focusInVector)throw Error(`focus escaped vector`)}
export async function runNavigationBrowserContracts(contracts=loadContracts().filter(x=>navigationNames.includes(x.component))){const{vectors,html}=await renderNavigationSSR(contracts);return runObservableBrowser({name:'navigation',entrySource:clientSource(vectors),html,vectors,runVector:async(api,s,i)=>{for(const action of s.actions){await api.action(i,action);if(action.checkpoint)check(await api.evaluate(checkpointSource(i)),action.checkpoint,s.component)}const snapshot=await api.evaluate(checkpointSource(i));check(snapshot,s.expected,s.component);return{component:s.component,id:s.id,passed:true}}})}
if(import.meta.url===`file://${process.argv[1]}`)console.log(JSON.stringify(await runNavigationBrowserContracts(),null,2));
