import { createHash } from 'node:crypto';
import { spawn, spawnSync } from 'node:child_process';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const root=resolve(import.meta.dirname,'../../..'),pkg=resolve(root,'dx/packages/kumo-vue'),work=resolve(root,'.tmp/vue-library-proof');
const run=(cmd,args,cwd=root)=>{const command=[cmd,...args].join(' '),r=spawnSync(cmd,args,{cwd,encoding:'utf8',env:{...process.env,SOURCE_DATE_EPOCH:'0'}}),stdout=typeof r.stdout==='string'?r.stdout:'',stderr=typeof r.stderr==='string'?r.stderr:'';if(r.error)throw Error(`${command}: ${r.error.message}\nstdout:\n${stdout}\nstderr:\n${stderr}`);if(r.status!==0)throw Error(`${command}: exited ${r.status}${r.signal?` (${r.signal})`:''}\nstdout:\n${stdout}\nstderr:\n${stderr}`);return stdout.trim()};
const sha=x=>createHash('sha256').update(x).digest('hex');
let serve,chrome,ws;
try{
 await rm(work,{recursive:true,force:true});await mkdir(work,{recursive:true});
 const pack=()=>{run('npm',['pack',pkg,'--pack-destination',work,'--ignore-scripts']);return resolve(work,'acoyfellow-kumo-vue-0.0.1.tgz')};
 let tgz=pack(),first=sha(await readFile(tgz));await rm(tgz);tgz=pack();const second=sha(await readFile(tgz));if(first!==second)throw Error('tarballs not deterministic');
 const audit=run('tar',['-tzf',tgz]).split('\n').sort(),expected=['package/kumo.manifest.json','package/package.json','package/package/button.d.ts','package/package/button.js','package/package/field.d.ts','package/package/field.js','package/package/index.d.ts','package/package/index.js','package/package/styles.css','package/package/tokens.css'].sort();if(JSON.stringify(audit)!==JSON.stringify(expected))throw Error(`package files differ: ${audit}`);
 const app=resolve(work,'consumer');await mkdir(resolve(app,'src'),{recursive:true});
 await writeFile(resolve(app,'package.json'),JSON.stringify({private:true,type:'module',scripts:{typecheck:'tsc --noEmit',build:'vite build',ssr:'vite build --ssr src/entry-server.ts'},dependencies:{'@acoyfellow/kumo-vue':`file:${tgz}`,vue:'3.5.38','@vue/server-renderer':'3.5.38'},devDependencies:{'@vitejs/plugin-vue':'6.0.7',typescript:'5.9.3',vite:'8.0.16'}},null,2));
 await writeFile(resolve(app,'index.html'),'<div id="app"><!--app-html--></div><!--server-node-script--><script type="module" src="/src/main.ts"></script>');
 await writeFile(resolve(app,'tsconfig.json'),JSON.stringify({compilerOptions:{target:'ES2022',module:'ESNext',moduleResolution:'Bundler',strict:true,skipLibCheck:true,noEmit:true},include:['src/**/*.ts']}));
 await writeFile(resolve(app,'vite.config.js'),"import{defineConfig}from'vite';import vue from'@vitejs/plugin-vue';export default defineConfig({plugins:[vue()],build:{metafile:true}})");
 const component=`import {defineComponent,h,ref} from 'vue';import {Button} from '@acoyfellow/kumo-vue';import {Field} from '@acoyfellow/kumo-vue/field';import '@acoyfellow/kumo-vue/styles.css';import '@acoyfellow/kumo-vue/tokens.css';export const App=defineComponent({setup(){const value=ref('start'),clicks=ref(0);return()=>h('main',{},[h(Button,{id:'active',onClick:()=>clicks.value++},{default:()=>\`Clicked \${clicks.value}\`}),h(Button,{id:'disabled',disabled:true,onClick:()=>clicks.value++},{default:()=> 'Disabled'}),h(Button,{id:'loading',loading:true},{default:()=> 'Load'}),h(Field as any,{id:'email',label:'Email',description:'Use work email',error:'Required',required:true,modelValue:value.value,'onUpdate:modelValue':(v:string|number)=>value.value=String(v)}),h('output',{id:'model'},value.value)])}});`;
 await writeFile(resolve(app,'src/App.ts'),component);await writeFile(resolve(app,'src/main.ts'),"import{createSSRApp,nextTick}from'vue';import{App}from'./App';const app=createSSRApp(App);app.mount('#app');nextTick(()=>{(globalThis as any).__hydratedNode=document.querySelector('#app')!.firstElementChild;document.documentElement.dataset.hydrationReady='true'});");await writeFile(resolve(app,'src/entry-server.ts'),"import{createSSRApp}from'vue';import{renderToString}from'@vue/server-renderer';import{App}from'./App';export const render=()=>renderToString(createSSRApp(App));");
 run('npm',['install','--ignore-scripts'],app);run('npm',['run','typecheck'],app);run('npm',['run','build'],app);await cp(resolve(app,'dist'),resolve(app,'dist-client'),{recursive:true});run('npm',['run','ssr'],app);
 const server=await import(pathToFileURL(resolve(app,'dist/entry-server.js'))),html=await server.render();if(!html.includes('aria-describedby="email-description email-error"')||!html.includes('required'))throw Error('SSR semantic assertions failed');
 const builtHtml=await readFile(resolve(app,'dist-client/index.html'),'utf8');await writeFile(resolve(app,'dist-client.html'),builtHtml.replace('<!--app-html-->',html).replace('<!--server-node-script-->','<script>globalThis.__serverNode=document.querySelector(\'#app\').firstElementChild</script>'));
 serve=spawn(process.execPath,[resolve(root,'proof/dx/vue-library/server.mjs'),app],{stdio:['ignore','pipe','inherit']});await new Promise((ok,no)=>{serve.stdout.once('data',ok);serve.once('exit',no)});
 const port=41739,debug=9339,chromePath='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',profile=resolve(work,'chrome');chrome=spawn(chromePath,[`--remote-debugging-port=${debug}`,`--user-data-dir=${profile}`,'--headless=new','--no-first-run','--disable-gpu',`http://127.0.0.1:${port}/`],{stdio:'ignore'});
 await new Promise(r=>setTimeout(r,1200));const version=await(await fetch(`http://127.0.0.1:${debug}/json/version`)).json(),tabs=await(await fetch(`http://127.0.0.1:${debug}/json`)).json();ws=new WebSocket(tabs.find(x=>x.type==='page').webSocketDebuggerUrl);let id=0;const pending=new Map(),consoleMessages=[],exceptions=[],failed=[],responses=[];ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id)}else if(m.method==='Runtime.consoleAPICalled')consoleMessages.push(m.params.args.map(x=>x.value??x.description).join(' '));else if(m.method==='Runtime.exceptionThrown')exceptions.push(m.params.exceptionDetails.text);else if(m.method==='Network.loadingFailed')failed.push(m.params.errorText);else if(m.method==='Network.responseReceived')responses.push({url:m.params.response.url,status:m.params.response.status,mimeType:m.params.response.mimeType})};await new Promise(r=>ws.onopen=r);const c=(method,params={})=>new Promise((ok,no)=>{const n=++id;pending.set(n,m=>m.error?no(Error(JSON.stringify(m.error))):ok(m.result));ws.send(JSON.stringify({id:n,method,params}))});await c('Runtime.enable');await c('Network.enable');await c('Page.enable');await c('Page.reload',{ignoreCache:true});const ev=async expression=>(await c('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true})).result.value;
 await ev(`new Promise((ok,no)=>{const end=Date.now()+5000;(function poll(){if(document.documentElement.dataset.hydrationReady==='true')ok();else if(Date.now()>end)no(Error('hydration timeout'));else setTimeout(poll,20)})()})`);
 const before=await ev(`document.querySelector('#active').textContent`);const browser=await ev(`(async()=>{const q=s=>document.querySelector(s),input=q('#email'),active=q('#active'),disabled=q('#disabled');active.click();await Promise.resolve();await new Promise(r=>requestAnimationFrame(()=>r()));const click=active.textContent;disabled.click();await Promise.resolve();await new Promise(r=>requestAnimationFrame(()=>r()));const disabledCount=active.textContent;input.value='changed';input.dispatchEvent(new Event('input',{bubbles:true}));await Promise.resolve();await new Promise(r=>requestAnimationFrame(()=>r()));return {serverNodePreserved:globalThis.__serverNode===globalThis.__hydratedNode,hydrationReady:document.documentElement.dataset.hydrationReady,click,disabledCount,model:q('#model').textContent,label:q('label').htmlFor,desc:input.getAttribute('aria-describedby'),invalid:input.getAttribute('aria-invalid'),required:input.required,css:[...document.styleSheets].filter(s=>[...s.cssRules].some(r=>r.cssText.includes('.kumo-button'))).length}})()`);browser.before=before;
 const wanted={serverNodePreserved:true,hydrationReady:'true',click:'Clicked 1',disabledCount:'Clicked 1',model:'changed',label:'email',desc:'email-description email-error',invalid:'true',required:true,css:1,before:'Clicked 0'};if(JSON.stringify(browser)!==JSON.stringify(wanted))throw Error(`browser assertions failed ${JSON.stringify(browser)}`);if(exceptions.length||failed.length||consoleMessages.length)throw Error(`browser diagnostics ${JSON.stringify({exceptions,failed,consoleMessages})}`);const assets=responses.filter(x=>x.url.includes('/assets/')).map(x=>({url:x.url,status:x.status,mimeType:x.mimeType}));if(!assets.some(x=>x.mimeType.includes('javascript')&&x.status>=200&&x.status<300)||!assets.some(x=>x.mimeType.includes('css')&&x.status>=200&&x.status<300))throw Error(`asset responses failed ${JSON.stringify(assets)}`);
 const tree=resolve(app,'tree');await mkdir(tree,{recursive:true});await writeFile(resolve(tree,'entry.js'),"import{Button}from'@acoyfellow/kumo-vue/button';console.log(Button)");run(resolve(app,'node_modules/.bin/vite'),['build','--ssr',resolve(tree,'entry.js'),'--config',resolve(app,'vite.config.js'),'--outDir',resolve(tree,'out'),'--emptyOutDir'],app);if((await readFile(resolve(tree,'out/entry.js'),'utf8')).includes('KumoField'))throw Error('tree-shaking retained Field');
 const workspace=resolve(work,'workspace');await mkdir(resolve(workspace,'packages/app'),{recursive:true});await writeFile(resolve(workspace,'package.json'),JSON.stringify({private:true,workspaces:['packages/*'],dependencies:{vue:'3.5.38'}}));await writeFile(resolve(workspace,'packages/app/package.json'),JSON.stringify({private:true,type:'module',dependencies:{'@acoyfellow/kumo-vue':`file:${tgz}`,vue:'3.5.38'},scripts:{build:'node -e "import(\'@acoyfellow/kumo-vue\').then(x=>{if(!x.Button||!x.Field)process.exit(1)})"'}}));run('npm',['install','--ignore-scripts'],workspace);run('npm',['run','build','-w','packages/app'],workspace);
 const sourceTreeDigest=sha((await Promise.all(['package.json','kumo.manifest.json','package/button.d.ts','package/button.js','package/field.d.ts','package/field.js','package/index.d.ts','package/index.js','package/styles.css','package/tokens.css'].map(x=>readFile(resolve(pkg,x))))).map((x,i)=>`${i}\0${sha(x)}`).join('\n')),commands=['npm pack (twice)','npm install --ignore-scripts','npm run typecheck','npm run build','npm run ssr','Chrome DevTools Protocol browser assertions','Vite tree-shaking build','npm workspace build'];const observations={...browser,consoleMessages,exceptions,networkFailures:failed,assetResponses:assets.map(x=>({url:x.url.replace(/\/assets\/[^/?]+/,'/assets/<hashed>'),status:x.status,mimeType:x.mimeType}))};const versions={node:process.version,npm:run('npm',['--version']),vite:run(resolve(app,'node_modules/.bin/vite'),['--version']).replace(/node-v\S+/,'node-<normalized>'),browser:version.Browser,protocol:version['Protocol-Version']};const receipt={schemaVersion:2,framework:'vue',package:'@acoyfellow/kumo-vue@0.0.1',sourceTree:run('git',['rev-parse','HEAD']),sourceTreeDigest,packageSha256:first,deterministicRuns:2,versions,commands,observations,checks:{packedTarball:'passed',fileAudit:'passed',typecheck:'passed',clientBuild:'passed',ssrBuild:'passed',renderToString:'passed',chromeHydration:'passed',browserBehavior:'passed',aria:'passed',cssLoadedOnce:'passed',assets:'passed',console:'passed',serverNodeIdentity:'passed',treeShaking:'passed',workspace:'passed',hmr:'not-run',manualScreenReader:'not-run'}};receipt.receiptHash=sha(JSON.stringify(receipt));await writeFile(resolve(root,'proof/dx/vue-library/receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
} finally {try{ws?.close()}catch{}chrome?.kill();serve?.kill();await new Promise(r=>setTimeout(r,100));await rm(work,{recursive:true,force:true})}
