import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { loadLibrary } from '../../../src/kumo/library/index.mjs';
import { compareMarkup } from '../../../scripts/observable-runner.mjs';

const root=resolve(import.meta.dirname,'../../..'),pkg=resolve(root,'dx/packages/kumo-vue'),work=resolve(root,'.tmp/vue-library-proof');
const run=(cmd,args,cwd=root)=>{const command=[cmd,...args].join(' '),r=spawnSync(cmd,args,{cwd,encoding:'utf8',env:{...process.env,SOURCE_DATE_EPOCH:'0'}}),stdout=typeof r.stdout==='string'?r.stdout:'',stderr=typeof r.stderr==='string'?r.stderr:'';if(r.error)throw Error(`${command}: ${r.error.message}\nstdout:\n${stdout}\nstderr:\n${stderr}`);if(r.status!==0)throw Error(`${command}: exited ${r.status}${r.signal?` (${r.signal})`:''}\nstdout:\n${stdout}\nstderr:\n${stderr}`);return stdout.trim()};
const sha=x=>createHash('sha256').update(x).digest('hex');
try{
 await rm(work,{recursive:true,force:true});await mkdir(work,{recursive:true});
 const pack=()=>{run('npm',['pack',pkg,'--pack-destination',work,'--ignore-scripts']);return resolve(work,'acoyfellow-kumo-vue-0.0.1.tgz')};
 let tgz=pack(),first=sha(await readFile(tgz));await rm(tgz);tgz=pack();const second=sha(await readFile(tgz));if(first!==second)throw Error('tarballs not deterministic');
 const audit=run('tar',['-tzf',tgz]).split('\n').sort();const manifest=JSON.parse(await readFile(resolve(pkg,'kumo.manifest.json'),'utf8'));const expected=['package/kumo.manifest.json','package/package.json',...audit.filter(x=>x.startsWith('package/package/'))].sort();if(JSON.stringify(audit)!==JSON.stringify(expected))throw Error(`package files differ: ${audit}`);
 const app=resolve(work,'consumer');await mkdir(resolve(app,'src'),{recursive:true});
 await writeFile(resolve(app,'package.json'),JSON.stringify({private:true,type:'module',scripts:{typecheck:'tsc --noEmit',build:'vite build',ssr:'vite build --ssr src/entry-server.ts'},dependencies:{'@acoyfellow/kumo-vue':`file:${tgz}`,vue:'3.5.38','@vue/server-renderer':'3.5.38'},devDependencies:{'@vitejs/plugin-vue':'6.0.7',typescript:'5.9.3',vite:'8.0.16'}},null,2));
 await writeFile(resolve(app,'index.html'),'<div id="app"><!--app-html--></div><!--server-node-script--><script type="module" src="/src/main.ts"></script>');
 await writeFile(resolve(app,'tsconfig.json'),JSON.stringify({compilerOptions:{target:'ES2022',module:'ESNext',moduleResolution:'Bundler',strict:true,skipLibCheck:true,noEmit:true},include:['src/**/*.ts']}));
 await writeFile(resolve(app,'vite.config.js'),"import{defineConfig}from'vite';import vue from'@vitejs/plugin-vue';export default defineConfig({plugins:[vue()],build:{metafile:true}})");
 const component=`import {defineComponent,h,ref} from 'vue';import * as Kumo from '@acoyfellow/kumo-vue';import {Button} from '@acoyfellow/kumo-vue';import {Field} from '@acoyfellow/kumo-vue/field';import '@acoyfellow/kumo-vue/styles.css';import '@acoyfellow/kumo-vue/tokens.css';export const App=defineComponent({setup(){const value=ref('start'),clicks=ref(0);return()=>h('main',{},[h(Button,{id:'active',onClick:()=>clicks.value++},{default:()=>\`Clicked \${clicks.value}\`}),h(Button,{id:'disabled',disabled:true,onClick:()=>clicks.value++},{default:()=> 'Disabled'}),h(Button,{id:'loading',loading:true},{default:()=> 'Load'}),h(Field as any,{id:'email',label:'Email',description:'Use work email',error:'Required',required:true,modelValue:value.value,'onUpdate:modelValue':(v:string|number)=>value.value=String(v)}),h('output',{id:'model'},value.value)])}});`;
 await writeFile(resolve(app,'src/App.ts'),component);await writeFile(resolve(app,'src/main.ts'),"import{createSSRApp,nextTick}from'vue';import{App}from'./App';const app=createSSRApp(App);app.mount('#app');nextTick(()=>{(globalThis as any).__hydratedNode=document.querySelector('#app')!.firstElementChild;document.documentElement.dataset.hydrationReady='true'});");await writeFile(resolve(app,'src/entry-server.ts'),"import{createSSRApp}from'vue';import{renderToString}from'@vue/server-renderer';import{App}from'./App';export const render=()=>renderToString(createSSRApp(App));");
 const imports=manifest.components.map(entry=>entry.component);await writeFile(resolve(app,'src/all.ts'),manifest.components.map(({symbol:name},i)=>`import { ${name} as Root${name} } from '@acoyfellow/kumo-vue'; import Sub${name} from '@acoyfellow/kumo-vue/${imports[i]}'; void Root${name}; void Sub${name};`).join('\n'));
 const library=loadLibrary(),semanticCases=library.models.flatMap(model=>(model.draftImplementation.semanticVariants??[]).map(variant=>({component:model.component,symbol:model.public.symbol,id:variant.id,when:variant.when})));await writeFile(resolve(app,'src/semantic.ts'),`import{createSSRApp,h}from'vue';import{renderToString}from'@vue/server-renderer';import*as Kumo from'@acoyfellow/kumo-vue';const Library=Kumo as Record<string,any>,cases:any[]=${JSON.stringify(semanticCases)},results:any[]=[];for(const c of cases){const props=Object.fromEntries(c.when.filter((x:any)=>x.kind==='prop-equals'&&x.name!=='children').map((x:any)=>[x.name,x.value])),content=c.when.find((x:any)=>x.kind==='prop-equals'&&x.name==='children')?.value,fixture=c.when.find((x:any)=>x.kind==='fixture-equals')?.value;if(fixture!==undefined)props.fixture=fixture;const C=Library[c.symbol];const html=await renderToString(createSSRApp({setup:()=>()=>h(C,props,content===undefined?{}:{default:()=>content})}));results.push({key:c.component+'#'+c.id,html})}console.log(JSON.stringify(results));`);
 run('npm',['install','--ignore-scripts'],app);run('npm',['run','typecheck'],app);run('npm',['run','build'],app);await cp(resolve(app,'dist'),resolve(app,'dist-client'),{recursive:true});run('npm',['run','ssr'],app);
 const server=await import(pathToFileURL(resolve(app,'dist/entry-server.js'))),html=await server.render();if(!html.includes('aria-describedby="email-description email-error"')||!html.includes('required'))throw Error('SSR semantic assertions failed');
 run(resolve(app,'node_modules/.bin/vite'),['build','--ssr','src/semantic.ts','--outDir','semantic-dist','--emptyOutDir'],app);const semanticOutput=run(process.execPath,['semantic-dist/semantic.js'],app),semanticResults=JSON.parse(semanticOutput.split(/\r?\n/).at(-1)),semanticByKey=new Map(semanticResults.map(result=>[result.key,result.html]));let semanticPassed=0;for(const model of library.models)for(const variant of model.draftImplementation.semanticVariants??[]){const key=`${model.component}#${variant.id}`,raw=semanticByKey.get(key);if(typeof raw!=='string')throw Error(`missing packed semantic result ${key}`);const markup=raw.replace(/<(area|base|br|col|embed|hr|img|input|link|meta|param|source|track|wbr)([^>]*)>/g,'<$1$2></$1>'),vector=library.semanticRender.components.find(x=>x.component===model.component)?.vectors.find(x=>x.id===variant.id);if(!vector)throw Error(`missing semantic expectation ${key}`);for(const constraint of vector.nodes){const expected={root:constraint.selector===':root'?constraint.require:{},...(constraint.selector===':root'?{}:{descendants:[{selector:constraint.selector,...constraint.require}]})};try{compareMarkup(markup,expected)}catch(error){throw Error(`${key} ${constraint.selector}: ${error.message}`)}}semanticPassed++}if(semanticPassed!==66)throw Error(`packed semantic count ${semanticPassed}`);const semanticUnresolved=library.models.flatMap(model=>model.unresolvedSemanticOperations??[]).length;if(semanticUnresolved!==0)throw Error(`packed unresolved semantic count ${semanticUnresolved}`);
 const builtHtml=await readFile(resolve(app,'dist-client/index.html'),'utf8');const builtAssets=[...builtHtml.matchAll(/(?:src|href)="([^"]*assets\/[^"]+)"/g)].map(x=>x[1]);if(!builtAssets.some(x=>x.endsWith('.js'))||!builtAssets.some(x=>x.endsWith('.css')))throw Error(`client CSS/assets missing ${JSON.stringify(builtAssets)}`);for(const asset of builtAssets)await readFile(resolve(app,'dist-client',asset.replace(/^\//,'')));
 const tree=resolve(app,'tree');await mkdir(tree,{recursive:true});await writeFile(resolve(tree,'entry.js'),"import{Button}from'@acoyfellow/kumo-vue/button';console.log(Button)");run(resolve(app,'node_modules/.bin/vite'),['build','--ssr',resolve(tree,'entry.js'),'--config',resolve(app,'vite.config.js'),'--outDir',resolve(tree,'out'),'--emptyOutDir'],app);if((await readFile(resolve(tree,'out/entry.js'),'utf8')).includes('KumoField'))throw Error('tree-shaking retained Field');
 const workspace=resolve(work,'workspace');await mkdir(resolve(workspace,'packages/app'),{recursive:true});await writeFile(resolve(workspace,'package.json'),JSON.stringify({private:true,workspaces:['packages/*'],dependencies:{vue:'3.5.38'}}));await writeFile(resolve(workspace,'packages/app/package.json'),JSON.stringify({private:true,type:'module',dependencies:{'@acoyfellow/kumo-vue':`file:${tgz}`,vue:'3.5.38'},scripts:{build:'node -e "import(\'@acoyfellow/kumo-vue\').then(x=>{if(!x.Button||!x.Field)process.exit(1)})"'}}));run('npm',['install','--ignore-scripts'],workspace);run('npm',['run','build','-w','packages/app'],workspace);
 const canonical=JSON.parse(await readFile(resolve(root,'generated/libraries/vue/manifest.json'),'utf8'));if(manifest.components.some((entry,i)=>entry.component!==canonical.components[i]?.component||entry.symbol!==canonical.components[i]?.symbol||entry.modelDigest!==canonical.components[i]?.modelDigest))throw Error('stale package manifest model binding');for(const part of manifest.compoundExports.paths){const rootApi=await import(pathToFileURL(resolve(app,'node_modules/@acoyfellow/kumo-vue/package/index.js')));const sub=await import(pathToFileURL(resolve(app,'node_modules/@acoyfellow/kumo-vue',part.file)));if(!part.binding.split('.').slice(1).reduce((x,k)=>x?.[k],rootApi[part.root])&&!sub.default&&!sub[part.symbol])throw Error(`unresolved compound export ${part.binding}`)}const sourceFiles=['package.json','kumo.manifest.json',...audit.filter(x=>x.startsWith('package/package/')).map(x=>x.slice(8))];const sourceTreeDigest=sha((await Promise.all(sourceFiles.map(x=>readFile(resolve(pkg,x))))).map((x,i)=>`${i}\0${sha(x)}`).join('\n')),commands=['npm pack (twice)','package file audit','fresh tgz npm install','all 41 root/subpath TypeScript imports','Vite client build','Vue SSR build/render','66 packed semantic SSR comparisons','compound export imports','CSS/assets file presence','Vite tree-shaking build','npm workspace build'];const versions={node:process.version,npm:run('npm',['--version']),vite:run(resolve(app,'node_modules/.bin/vite'),['--version']).replace(/node-v\S+/,'node-<normalized>')};const pending='requires scripts/observable-browser-runner.mjs trusted conformance';const receipt={schemaVersion:3,framework:'vue',package:'@acoyfellow/kumo-vue@0.0.1',sourceTree:run('git',['rev-parse','HEAD']),sourceTreeDigest,packageSha256:first,deterministicRuns:2,versions,commands,exportSurface:{componentCount:manifest.components.length,compoundPathCount:manifest.compoundExports.paths.length,modelBindings:'passed',compoundPaths:'passed',rootImports:'passed',subpathImports:'passed',types:'passed',noWorkspaceImports:'passed',fileAudit:'passed',treeShaking:'passed'},packageConformance:{clientBuild:'passed',ssrBuild:'passed',renderToString:'passed',cssAssetsPresent:'passed'},browserConformance:{hydration:'not-run',serverNodeIdentity:'not-run',buttonFieldBehavior:'not-run',hmr:'not-run',screenReader:'not-run'},staticSemanticConformance:{status:'passed',passed:semanticPassed,unresolved:semanticUnresolved},pendingReasons:{hydration:pending,serverNodeIdentity:pending,buttonFieldBehavior:pending,hmr:pending,screenReader:pending},observations:{}};receipt.receiptHash=sha(JSON.stringify(receipt));await writeFile(resolve(root,'proof/dx/vue-library/receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
} finally {await rm(work,{recursive:true,force:true})}
