import {createHash} from 'node:crypto';
import {readFile,readdir,lstat} from 'node:fs/promises';
import path from 'node:path';
export const sha256=x=>createHash('sha256').update(x).digest('hex');
export const diagnostic=(code,message,p='$')=>({severity:'error',code,message,path:p});
export function safeRelative(value){return typeof value==='string'&&value.length>0&&!path.isAbsolute(value)&&!value.split(/[\\/]/).includes('..')&&!value.includes('\\')}
export async function tree(root){const out=[];async function walk(dir){for(const name of (await readdir(dir)).sort()){const absolute=path.join(dir,name),s=await lstat(absolute);if(s.isSymbolicLink())throw new Error(`symlink output forbidden: ${absolute}`);if(s.isDirectory())await walk(absolute);else if(s.isFile()){const body=await readFile(absolute);out.push({path:path.relative(root,absolute).split(path.sep).join('/'),sha256:sha256(body),bytes:body.byteLength});}}}await walk(root);return out.sort((a,b)=>a.path.localeCompare(b.path));}
export function validateDiagnostic(d){return d&&['error','warning','info'].includes(d.severity)&&/^[a-z0-9][a-z0-9-]*$/.test(d.code)&&typeof d.message==='string'&&d.message.length>0&&/^\$(?:\.[A-Za-z0-9_-]+|\[[0-9]+\])*$/.test(d.path)&&Object.keys(d).every(k=>['severity','code','message','path'].includes(k));}
export function validateReceipt(r){const errors=[];if(r?.schemaVersion!=='kumo.compiler.receipt/v1')errors.push('receipt schemaVersion');if(!r?.compiler?.name||!r.compiler.version||!r.compiler.toolchain)errors.push('compiler identity');if(!r?.roots?.input||!r?.roots?.output)errors.push('roots');if(!['ok','error'].includes(r?.status))errors.push('status');if(!Array.isArray(r?.diagnostics)||r.diagnostics.some(d=>!validateDiagnostic(d)))errors.push('diagnostics');if(!Array.isArray(r?.plan))errors.push('plan');if(!Array.isArray(r?.outputs))errors.push('outputs');else {const seen=new Set;for(const o of r.outputs){if(!safeRelative(o.path)||seen.has(o.path)||!/^[a-f0-9]{64}$/.test(o.sha256)||!Number.isSafeInteger(o.bytes)||o.bytes<0)errors.push('output manifest');seen.add(o.path)}if(r.outputs.some((x,i,a)=>i&&a[i-1].path.localeCompare(x.path)>0))errors.push('output sorting')}return errors;}
export const stable=x=>JSON.stringify(x,Object.keys(x).sort());
