import path from'node:path';
import{fileURLToPath}from'node:url';
import{runObservableBrowser}from'../../../../scripts/observable-browser-runner.mjs';
import{compareMarkup}from'../../../../scripts/observable-runner.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../..'),ids=new Set(['disabled-click','loading-click','enabled-click','submit-form']),json=JSON.stringify;
export async function runSvelteButtonBrowser({consumer,vectors,ssrRenders}){
 const specs=vectors.filter(v=>v.provenance.vector.startsWith('button/')&&ids.has(v.provenance.vector.split('/')[1])).map(v=>({...v,component:'button',id:v.provenance.vector.split('/')[1]}));
 if(specs.length!==4||ssrRenders.length!==4)throw Error('Svelte Button browser slice requires exactly four vectors');
 const results=[],diagnostics=[],telemetry=[];
 for(let i=0;i<4;i++){const spec=specs[i],data={id:spec.id,props:spec.fixture.props,children:spec.fixture.children.map(n=>n.value??'').join('')};
  const source=`import{hydrate}from'svelte';import App from'./App.svelte';const app=hydrate(App,{target:document.querySelector('#app'),props:{spec:${json(data)}}});queueMicrotask(()=>{globalThis.__ready=true});export default app;`;
  const app=`<script>import Button from'@acoyfellow/kumo-svelte/button';let{spec}=$props();let clicks=0,submits=0,events=[];function click(){clicks++;events=[...events,'click']}function submit(e){e.preventDefault();submits++;events=[...events,'submit']}</script><section id="v0" data-clicks={clicks} data-submits={submits} data-events={JSON.stringify(events)}>{#if spec.id==='submit-form'}<form onsubmit={submit}><Button {...spec.props} onclick={click}>{#snippet children()}{spec.children}{/snippet}</Button></form>{:else}<Button {...spec.props} onclick={click}>{#snippet children()}{spec.children}{/snippet}</Button>{/if}</section>`;
  const appFile=path.join(consumer,'src/App.svelte');await import('node:fs/promises').then(fs=>fs.writeFile(appFile,app));
  const run=await runObservableBrowser({name:`svelte-packed-button-${spec.id}`,entrySource:source,entryFilename:'client.js',viteConfig:path.join(root,'proof/dx/conformance/shared/svelte-vite.config.mjs'),buildEnv:{KUMO_CONSUMER:consumer},cssPath:path.join(consumer,'node_modules/@acoyfellow/kumo-svelte/package/styles.css'),html:ssrRenders[i].html,vectors:[spec],runVector:async(api,current)=>{for(const action of current.actions)await api.action(0,{...action,selector:'button'});const got=await api.evaluate(`(()=>{const root=document.querySelector('#v0'),button=root.querySelector('button');return{html:button.outerHTML,clicks:Number(root.dataset.clicks),submits:Number(root.dataset.submits),events:JSON.parse(root.dataset.events),focus:document.activeElement===button?'root':'none',svg:button.querySelectorAll('svg').length}})()`);compareMarkup(got.html,current.expected);for(const[k,v]of Object.entries(current.expected.state??{}))if(got[k]!==v)throw Error(k+' expected '+v+', got '+got[k]);if(json(got.events)!==json(current.expected.events??[]))throw Error('events mismatch');if(got.focus!==(current.expected.focus??'none'))throw Error('focus mismatch');return{component:'button',id:current.id,passed:true,ssr:'passed',hydration:'passed',nodeIdentity:'preserved',observation:got}}});results.push(...run.results);diagnostics.push(...run.diagnostics);telemetry.push({id:spec.id,...run.telemetry});
 }
 return{results,browserCells:results.length,diagnostics,telemetry,capabilities:['trusted-cdp','native-focus','hydration','isolated-vector-batches']};
}
