import { mkdtemp, mkdir, readFile, rm, writeFile, cp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { spawn } from 'node:child_process';

const root=resolve(import.meta.dirname,'../..'),artifacts=resolve(root,'library-artifacts'),output=resolve(root,'library-gallery');
const manifest=JSON.parse(await readFile(resolve(artifacts,'manifest.json'),'utf8'));
const used=['badge','banner','button','checkbox','code','field','input','label','link','loader','meter','switch'];
const symbols={badge:'Badge',banner:'Banner',button:'Button',checkbox:'Checkbox',code:'Code',field:'Field',input:'Input',label:'Label',link:'Link',loader:'Loader',meter:'Meter',switch:'Switch'};
const command=(program,args,cwd,timeout=120000)=>new Promise((ok,no)=>{const child=spawn(program,args,{cwd,stdio:'inherit'}),timer=setTimeout(()=>child.kill('SIGKILL'),timeout);child.once('error',e=>{clearTimeout(timer);no(e)});child.once('exit',(code,signal)=>{clearTimeout(timer);code===0?ok():no(new Error(`${program} ${args.join(' ')} failed (${signal||code})`))})});
await rm(output,{recursive:true,force:true});await mkdir(output,{recursive:true});
const imports=framework=>used.map(name=>`import { ${symbols[name]} } from '@acoyfellow/kumo-${framework}/${name}';`).join(' ');
const content=`<aside><strong>Workers</strong><nav aria-label="Workspace"><a href="#overview">Overview</a><a href="#traffic">Traffic</a><a href="#settings">Settings</a></nav></aside><main id="overview"><Banner>Package-native application preview</Banner><header><div><Badge>Production</Badge><h2>Edge API</h2><p>Live operations across the global network.</p></div><Button>Deploy</Button></header><section class="stats"><article><Label>Requests</Label><strong>18.4M</strong><Meter value="72" max="100" /></article><article><Label>Availability</Label><strong>99.99%</strong><Loader /></article></section><section><h3>Project settings</h3><Field id="project" label="Project name" description="Rendered by the installed package." value="edge-api" /><Input aria-label="Search deployments" placeholder="Search deployments" /><Checkbox checked>Automatic deployments</Checkbox><Switch checked aria-label="Enable observability" /><Code>npm run deploy</Code><Link href="/docs/">Open deployment guide</Link></section></main>`;
const vue=`${imports('vue')} import {createApp,h} from 'vue'; import '@acoyfellow/kumo-vue/styles.css'; const C={${used.map(n=>symbols[n]).join(',')}}; const App={template:\`${content.replaceAll(/<([A-Z][A-Za-z]*)/g,'<$1').replaceAll(' checked>',' :checked="true">')}\`};createApp(App).component('Badge',C.Badge).component('Banner',C.Banner).component('Button',C.Button).component('Checkbox',C.Checkbox).component('Code',C.Code).component('Field',C.Field).component('Input',C.Input).component('Label',C.Label).component('Link',C.Link).component('Loader',C.Loader).component('Meter',C.Meter).component('Switch',C.Switch).mount('#app');`;
const solid=`${imports('solid')} import {render} from 'solid-js/web'; import '@acoyfellow/kumo-solid/styles.css'; function App(){return <>${content}</>} render(()=><App/>,document.getElementById('app'));`;
const svelte=`<script>${imports('svelte')} import '@acoyfellow/kumo-svelte/styles.css';</script>${content}`;
const html=`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kumo kitchen sink</title><style>*{box-sizing:border-box}html{color-scheme:light dark}body{margin:0;background:#f8fafc;color:#0f172a;font:15px system-ui}#app{display:grid;grid-template-columns:180px 1fr;min-height:100vh}aside{padding:22px;background:#111827;color:white}nav{display:grid;gap:8px;margin-top:28px}nav a{padding:9px;color:#cbd5e1;text-decoration:none}main{display:grid;align-content:start;gap:18px;padding:28px}header,.stats{display:flex;justify-content:space-between;gap:18px}h2{font-size:32px;margin:7px 0}section,article{padding:18px;border:1px solid #cbd5e1;border-radius:10px;background:white}.stats article{flex:1}.stats strong{display:block;margin:8px 0;font-size:26px}section>*{margin:8px 6px 8px 0}@media(prefers-color-scheme:dark){body{background:#0f172a;color:#e2e8f0}section,article{border-color:#475569;background:#1e293b}}@media(max-width:600px){#app{grid-template-columns:1fr}aside{padding:14px}nav{display:flex;flex-wrap:wrap;margin-top:8px}main{padding:16px}header,.stats{display:grid}}</style></head><body><div id="app"></div><script type="module" src="/src/main"></script></body></html>`;
for(const entry of manifest.packages){const dir=await mkdtemp(resolve(tmpdir(),`kumo-gallery-${entry.framework}-`));try{await writeFile(resolve(dir,'package.json'),JSON.stringify({type:'module',dependencies:{vite:'8.0.16',[entry.package]:`file:${resolve(artifacts,entry.friendlyName)}`,...entry.framework==='vue'?{vue:'3.5.38','@vitejs/plugin-vue':'6.0.7'}:entry.framework==='svelte'?{svelte:'5.56.3','@sveltejs/vite-plugin-svelte':'7.1.2'}:{'solid-js':'1.9.13','vite-plugin-solid':'2.11.12'}}}));const plugin=entry.framework==='vue'?`import vue from '@vitejs/plugin-vue';export default {base:'/library-gallery/vue/',plugins:[vue()]}`:entry.framework==='svelte'?`import {svelte} from '@sveltejs/vite-plugin-svelte';export default {base:'/library-gallery/svelte/',plugins:[svelte()]}`:`import solid from 'vite-plugin-solid';export default {base:'/library-gallery/solid/',plugins:[solid()]}`;await writeFile(resolve(dir,'vite.config.js'),plugin);await writeFile(resolve(dir,'index.html'),html);await mkdir(resolve(dir,'src'));await writeFile(resolve(dir,`src/main.${entry.framework==='solid'?'jsx':'js'}`),entry.framework==='vue'?vue:entry.framework==='solid'?solid:`import {mount} from 'svelte';import App from './App.svelte';mount(App,{target:document.getElementById('app')});`);if(entry.framework==='svelte')await writeFile(resolve(dir,'src/App.svelte'),svelte);await command('npm',['install','--ignore-scripts','--no-audit','--no-fund'],dir);await command('npx',['vite','build','--outDir',resolve(output,entry.framework),'--emptyOutDir'],dir)}finally{await rm(dir,{recursive:true,force:true})}}
await cp(resolve(artifacts,'manifest.json'),resolve(output,'manifest.json'));console.log(`Built package-installed kitchen sinks using ${used.length} components per framework`);
