import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import {spawn,spawnSync} from 'node:child_process';
import {existsSync,readFileSync} from 'node:fs';
import {mkdtemp,readFile,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {extname,resolve,sep} from 'node:path';

const root=resolve(import.meta.dirname,'../..'),deploy=resolve(root,'.library-pages-deploy'),chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const sha=x=>createHash('sha256').update(x).digest('hex'), manifest=JSON.parse(await readFile(resolve(root,'library-artifacts/manifest.json'),'utf8'));
const run=(cmd,args,cwd=root)=>{const x=spawnSync(cmd,args,{cwd,stdio:'inherit'});if(x.status)throw Error(`${cmd} ${args.join(' ')} failed`)};
const runAsync=(cmd,args,cwd=root,timeout=120000)=>new Promise((ok,no)=>{const child=spawn(cmd,args,{cwd,stdio:'inherit'}),timer=setTimeout(()=>child.kill('SIGKILL'),timeout);child.once('error',e=>{clearTimeout(timer);no(e)});child.once('exit',(code,signal)=>{clearTimeout(timer);code===0?ok():no(Error(`${cmd} ${args.join(' ')} failed (${signal||code})`))})});
run('node',['scripts/libraries/build-gallery.mjs']);run('npm',['--prefix','astro','run','build']);
await rm(deploy,{recursive:true,force:true});run('cp',['-R','astro/dist',deploy]);run('cp',['-R','library-artifacts',resolve(deploy,'packages')]);run('cp',['-R','library-gallery',resolve(deploy,'library-gallery')]);
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.tgz':'application/octet-stream'};
const requests=[];const server=createServer(async(q,r)=>{try{let p=decodeURIComponent(new URL(q.url,'http://x').pathname);if(p==='/favicon.ico'){requests.push({path:p,status:204,bytes:0});r.writeHead(204);return r.end()}if(p.endsWith('/'))p+='index.html';const file=resolve(deploy,'.'+p);if(!file.startsWith(deploy+sep))throw Error('bad path');const bytes=await readFile(file);requests.push({path:new URL(q.url,'http://x').pathname,status:200,bytes:bytes.length});r.writeHead(200,{'content-type':mime[extname(file)]||'application/octet-stream'});r.end(bytes)}catch{requests.push({path:q.url,status:404});r.writeHead(404);r.end('not found')}});await new Promise(ok=>server.listen(0,'127.0.0.1',ok));const origin=`http://127.0.0.1:${server.address().port}`;
const diagnostics={console:[],exceptions:[],network:[],http:[]},cells=[],profile=await mkdtemp(resolve(tmpdir(),'kumo-library-pages-chrome-'));let cp,ws;
try{cp=spawn(chrome,['--headless=new','--disable-background-networking','--no-first-run',`--user-data-dir=${profile}`,'--remote-debugging-port=0','about:blank'],{stdio:'ignore'});const active=resolve(profile,'DevToolsActivePort');for(let i=0;i<240&&!existsSync(active);i++)await new Promise(r=>setTimeout(r,25));const [port,path]=readFileSync(active,'utf8').trim().split('\n');ws=new WebSocket(`ws://127.0.0.1:${port}${path}`);await new Promise((ok,no)=>{ws.onopen=ok;ws.onerror=no});let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.no(Error(m.error.message)):p.ok(m.result)}else if(m.method==='Runtime.consoleAPICalled'&&['error','warning'].includes(m.params.type))diagnostics.console.push(m.params.args.map(x=>x.value??x.description).join(' '));else if(m.method==='Runtime.exceptionThrown')diagnostics.exceptions.push(m.params.exceptionDetails.text);else if(m.method==='Network.loadingFailed'&&!m.params.canceled)diagnostics.network.push(m.params.errorText);else if(m.method==='Network.responseReceived'&&m.params.response.status>=400)diagnostics.http.push({url:m.params.response.url,status:m.params.response.status})};const send=(method,params={},sessionId)=>new Promise((ok,no)=>{const n=++id;pending.set(n,{ok,no});ws.send(JSON.stringify({id:n,method,params,...sessionId&&{sessionId}}))});const targets=await send('Target.getTargets'),page=targets.targetInfos.find(x=>x.type==='page'),{sessionId}=await send('Target.attachToTarget',{targetId:page.targetId,flatten:true});for(const method of ['Runtime.enable','Network.enable','Page.enable'])await send(method,{},sessionId);const ev=async expression=>{const x=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true},sessionId);if(x.exceptionDetails)throw Error(x.exceptionDetails.exception?.description||x.exceptionDetails.text);return x.result.value};
for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900}])for(const entry of manifest.packages){await send('Emulation.setDeviceMetricsOverride',{...viewport,deviceScaleFactor:1,mobile:false},sessionId);await send('Page.navigate',{url:`${origin}/libraries/${entry.framework}/`},sessionId);await ev(`new Promise((ok,no)=>{let n=0;const p=()=>document.querySelector('iframe')?.contentDocument?.querySelector('button')?ok():n++>300?no(Error('gallery timeout')):setTimeout(p,20);p()})`);const o=await ev(`(async()=>{const f=document.querySelector('iframe'),d=f.contentDocument,b=d.querySelector('button'),i=d.querySelector('input'),before=b.textContent.trim();b.click();await new Promise(r=>setTimeout(r,30));i.value='changed';i.dispatchEvent(new InputEvent('input',{bubbles:true}));await new Promise(r=>setTimeout(r,30));const desc=i.getAttribute('aria-describedby');const install=[...document.querySelectorAll('code')].find(x=>x.textContent.startsWith('npm install '))?.textContent;return{outerUrl:location.href,iframeUrl:f.contentWindow.location.href,sameOrigin:f.contentWindow.location.origin===location.origin,noOverflow:document.documentElement.scrollWidth<=document.documentElement.clientWidth,install,before,after:b.textContent.trim(),model:d.querySelector('output')?.textContent.trim(),label:d.querySelector('label')?.htmlFor,description:desc,descriptionExists:!!desc&&desc.split(' ').every(id=>d.getElementById(id)),cssApplied:[...d.styleSheets].some(s=>{try{return[...s.cssRules].some(r=>r.cssText.includes('.kumo-button'))}catch{return false}}),copyButtons:[...document.querySelectorAll('[data-copy]')].map(x=>({name:x.textContent.trim(),type:x.type})),selectAbsent:![...document.querySelectorAll('li')].some(x=>/^Select\\b/.test(x.textContent))}})()`);const expected=`npm install https://kumo-compiler.coey.dev${entry.installUrl}`;if(!o.noOverflow||!o.sameOrigin||o.install!==expected||o.after!=='Clicked 1'||o.model!=='Model: changed'||o.label!=='gallery-field'||!o.descriptionExists||!o.cssApplied||o.copyButtons.length!==2||o.copyButtons.some(x=>!x.name||x.type!=='button')||!o.selectAbsent)throw Error(`${entry.framework} ${viewport.width} assertions: ${JSON.stringify(o)}`);cells.push({framework:entry.framework,viewport,path:`/libraries/${entry.framework}/`,status:'passed',observations:o})}
}finally{ws?.close();cp?.kill();await new Promise(r=>server.close(r));await rm(profile,{recursive:true,force:true});await rm(deploy,{recursive:true,force:true})}
if(Object.values(diagnostics).some(x=>x.length))throw Error(`browser diagnostics: ${JSON.stringify(diagnostics)}`);
const artifacts=[];for(const e of manifest.packages)for(const name of [e.friendlyName,e.artifact]){const bytes=await readFile(resolve(root,'library-artifacts',name));if(bytes.length!==e.bytes||sha(bytes)!==e.sha256)throw Error(`${name} bytes/hash`);artifacts.push({url:`/packages/${name}`,bytes:bytes.length,sha256:sha(bytes),status:200})}
const work=await mkdtemp(resolve(tmpdir(),'kumo-library-http-install-'));const installServer=createServer(async(q,r)=>{try{r.end(await readFile(resolve(root,'library-artifacts','.'+new URL(q.url,'http://x').pathname.replace('/packages',''))))}catch{r.writeHead(404);r.end()}});await new Promise(ok=>installServer.listen(0,'127.0.0.1',ok));const installs=[];try{for(const e of manifest.packages){const dir=resolve(work,e.framework);run('mkdir',['-p',dir]);await writeFile(resolve(dir,'package.json'),JSON.stringify({type:'module'}));await runAsync('npm',['install','--ignore-scripts','--no-audit','--no-fund',`http://127.0.0.1:${installServer.address().port}/packages/${e.friendlyName}`],dir);const pkgPath=resolve(dir,'node_modules',...e.package.split('/'),'package.json'),pkg=JSON.parse(await readFile(pkgPath,'utf8')),keys=Object.keys(pkg.exports||{});if(!keys.includes('./button')||!keys.includes('./field')||keys.includes('./select')||keys.includes('./tabs'))throw Error(`${e.framework} exports audit: ${keys.join(', ')}`);for(const subpath of ['./button','./field']){const target=pkg.exports[subpath],file=typeof target==='string'?target:target.import||target.default;if(!file||!existsSync(resolve(dir,'node_modules',...e.package.split('/'),file)))throw Error(`${e.framework} ${subpath} has no loadable target`);if(e.framework==='vue')await import(`file://${resolve(dir,'node_modules',...e.package.split('/'),file)}`)}installs.push({framework:e.framework,url:`http://127.0.0.1:<PORT>/packages/${e.friendlyName}`,package:pkg.name,exports:keys,button:true,field:true,select:false,tabs:false,status:'passed'})}}finally{await new Promise(r=>installServer.close(r));await rm(work,{recursive:true,force:true})}
const receipt={schemaVersion:1,status:'passed',browser:{product:'system Chrome',protocol:'CDP'},origin:'http://127.0.0.1:<PORT>',cells,diagnostics,manifest:{status:200,sha256:sha(await readFile(resolve(root,'library-artifacts/manifest.json')))},artifacts,installs,requests:[...new Map(requests.map(x=>[x.path, x])).values()].sort((a,b)=>a.path.localeCompare(b.path))};receipt.receiptHash=sha(JSON.stringify(receipt));await writeFile(resolve(root,'proof/library-pages/receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log(`library pages proof passed (${cells.length} cells, ${receipt.receiptHash})`);
