import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {loadLibrary, canonicalJSON} from '../../library/index.mjs';
import {validateImplementation, NODE_KINDS, EXPRESSION_KINDS, OPERATION_KINDS} from '../../library/algebra.mjs';
import {requireContentBindings, semanticExpression, semanticPredicate} from '../shared/content-adapter.mjs';
import {clampPage, maxPage, nextPage, previousPage, commitPageInput} from '../../library/pagination-state.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../../../..');
const esc = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const directive = value => String(value).replaceAll('&','&amp;').replaceAll('"','&quot;');
const id = value => value.replace(/[^A-Za-z0-9_$]/g, '_').replace(/^([0-9])/, '_$1');
const pascal = value => value.split(/[-_ ]+/).map(x => x[0]?.toUpperCase() + x.slice(1)).join('');
const sha = value => crypto.createHash('sha256').update(value).digest('hex');

function expression(value, scope = 'props') {
  switch (value.kind) {
    case 'literal': return JSON.stringify(value.value);
    case 'prop': return `${scope}.${id(value.name)}`;
    case 'state': return `${id(value.name)}.value`;
    case 'item': return id(value.name);
    case 'coalesce': return `(${value.values.map(v => expression(v, scope)).join(' ?? ')})`;
    case 'equals': return `(${expression(value.left, scope)} === ${expression(value.right, scope)})`;
    case 'not': return `(!${expression(value.value, scope)})`;
    case 'concat': return `[${value.values.map(v => expression(v, scope)).join(', ')}].join(${JSON.stringify(value.separator ?? '')})`;
    case 'style-ref': return `styles[${JSON.stringify(value.name)}]`;
    default: throw new Error(`unsupported Vue expression: ${value.kind}`);
  }
}
function node(value, context = {}) {
  const child = x => node(x, context);
  switch (value.kind) {
    case 'children': return '<slot />';
    case 'text': return `{{ ${expression(value.value)} }}`;
    case 'slot': return `<slot name="${esc(value.name)}">${value.fallback ? child(value.fallback) : ''}</slot>`;
    case 'condition': return `<template v-if="${esc(expression(value.when))}">${child(value.then)}</template>${value.else ? `<template v-else>${child(value.else)}</template>` : ''}`;
    case 'collection': return `<template v-for="${id(value.item)} in ${esc(expression(value.source))}" :key="${esc(expression(value.key))}">${node(value.template, {...context, item:value.item})}</template>`;
    case 'compound': return `<div data-kumo-compound="${esc(value.name)}" :class="styles.root">${Object.entries(value.parts).map(([name, part]) => `<section data-kumo-part="${esc(name)}">${child(part)}</section>`).join('')}</div>`;
    case 'portal': return `<Teleport :to="${esc(expression(value.target))}"><div data-kumo-layer="${esc(value.layer)}">${value.children.map(child).join('')}</div></Teleport>`;
    case 'element': {
      const attrs = [];
      for (const [name, exp] of Object.entries(value.attributes ?? {})) attrs.push(`:${name}="${esc(expression(exp))}"`);
      for (const [name, exp] of Object.entries(value.properties ?? {})) attrs.push(`:${name}="${esc(expression(exp))}"`);
      for (const [name, exp] of Object.entries(value.events ?? {})) attrs.push(`@${name}="${esc(expression(exp))}"`);
      if (value.ref) attrs.push(`ref="${esc(value.ref)}"`);
      if (value.styles?.length) attrs.push(`:class="[${directive(value.styles.map(v => expression(v)).join(', '))}]"`);
      return `<${value.tag}${attrs.length ? ' '+attrs.join(' ') : ''}>${(value.children ?? []).map(child).join('')}</${value.tag}>`;
    }
    default: throw new Error(`unsupported Vue node: ${value.kind}`);
  }
}
function vueType(type) {
  const boolean = /boolean/i.test(type), number = /number/i.test(type), string = /string|base\||sm\||xs\||lg\||primary\||dialog\|/i.test(type);
  if ([boolean,number,string].filter(Boolean).length > 1) return 'unknown';
  if (boolean) return 'boolean';
  if (number) return 'number';
  if (string) return 'string';
  return 'unknown';
}
function compoundPartSource(partPath) {
  return `<!-- @generated by src/kumo/emitters/vue/index.mjs; do not edit -->\n<script setup lang="ts">
defineOptions({ inheritAttrs: false })
</script>

<template>
  <span v-bind="$attrs" data-kumo-part="${esc(partPath)}"><slot /></span>
</template>
`;
}
function compoundBindingSource(graph, imports) {
  const root = {};
  for (const item of graph.paths) {
    const segments = item.path.split('.');
    let cursor = root;
    for (let index = 0; index < segments.length; index++) {
      const segment = segments[index];
      cursor[segment] ??= index === segments.length - 1 ? imports.get(item.path) : {};
      cursor = cursor[segment];
    }
  }
  const literal = value => typeof value === 'string' ? value : `{ ${Object.entries(value).map(([key, child]) => `${JSON.stringify(key)}: ${literal(child)}`).join(', ')} }`;
  return `export const ${id(graph.canonicalRoot)} = Object.assign(RootComponent, ${literal(root)})`;
}
const vuePropName = name => name.replace(/-([a-z])/g,(_,letter)=>letter.toUpperCase());
function semanticNode(value) {
  const e = item => {
    const semanticItem = item.kind === 'prop' ? {...item,name:vuePropName(item.name)} : item;
    const semantic = semanticExpression(semanticItem,{props:'semanticValues',fixture:'fixture',content:'renderContent()'});
    if (semantic !== null) return semantic;
    return expression(item,'semanticValues');
  };
  switch (value.kind) {
    case 'semantic-element': {
      if (value.tag.kind !== 'literal' || !/^[a-z][a-z0-9-]*$/.test(value.tag.value)) throw new Error('Vue semantic element requires literal tag');
      const entries = Object.entries(value.attributes ?? {});
      const dynamicTag = entries.some(([name]) => /[A-Z]/.test(name));
      const attrs = dynamicTag ? [`v-bind="{ ${entries.map(([name,item]) => `${directive(JSON.stringify(name))}: ${directive(e(item))}`).join(', ')} }"`] : entries.map(([name,item]) => item.kind === 'literal' && typeof item.value === 'string' ? `${name}="${esc(item.value)}"` : `:${name}="${directive(e(item))}"`);
      if (value.classes?.length) attrs.push(`class="${esc(value.classes.map(x => x.value).join(' '))}"`);
      const tag = dynamicTag ? `component :is="'${value.tag.value}'"` : value.tag.value;
      const close = dynamicTag ? 'component' : value.tag.value;
      return `<${tag}${attrs.length?' '+attrs.join(' '):''}>${(value.children??[]).map(semanticNode).join('')}</${close}>`;
    }
    case 'text': return `{{ ${e(value.value)} }}`;
    case 'fixture-children': return `{{ fixtureText(${e(value.value)}) }}`;
    default: return node(value);
  }
}
function toggleBinding(model, library) {
  const behavior = library.behaviorCapabilities.bindings.find(binding => binding.component === model.component && binding.id === 'toggle-control' && binding.support === 'supported');
  if (!behavior || behavior.missingOperations.length || !behavior.controlled.supported || !behavior.uncontrolled.supported) return null;
  const state = library.controlledState.specs.find(spec => spec.component === behavior.component);
  const native = library.nativeControls.specs.find(spec => spec.component === behavior.component && spec.contractDigest === behavior.contractDigest);
  if (!state || !native || native.events.join('\0') !== state.event || !['span','button'].includes(native.root)) return null;
  return {behavior,state,native};
}
function toggleSource({state,native}) {
  const role = native.root === 'span' ? 'checkbox' : 'switch';
  const indeterminate = state.indeterminate;
  const rootAttrs = native.root === 'button' ? ` type="button"` : ` :tabindex="props.disabled ? undefined : 0"`;
  const keyHandler = native.root === 'button' ? '' : ` @keydown="activateOnSpace"`;
  const aria = indeterminate ? `(currentIndeterminate ? 'mixed' : currentChecked)` : 'currentChecked';
  const styleExpression = `[${native.styleVariants.map(variant=>`(${Object.entries(variant.when).map(([name,value])=>`props.${vuePropName(name)} === ${JSON.stringify(value)}`).join(' && ')||'true'}) ? ${JSON.stringify(variant.classes.join(' '))} : ''`).join(', ')}]`;
  const styleClass = native.styleVariants.length ? ` :class="${directive(styleExpression)}"` : '';
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, getCurrentInstance, ref, useAttrs, useSlots',
    setup:`const instance = getCurrentInstance()\nconst controlled = Object.prototype.hasOwnProperty.call(instance?.vnode.props ?? {}, ${JSON.stringify(state.controlledProp)})\nconst internalChecked = ref(props.${state.defaultProp} ?? ${JSON.stringify(state.initial)})\nconst currentChecked = computed(() => controlled ? props.${state.controlledProp} : internalChecked.value)\n${indeterminate?`const currentIndeterminate = ref(Boolean(props.${indeterminate.prop}))\n`:''}function activate(event: Event) {\n  if (props.${state.disabled.prop}) return\n  const next = ${indeterminate ? `currentIndeterminate.value ? ${JSON.stringify(indeterminate.activationResult)} : ` : ''}!currentChecked.value\n  ${indeterminate?'currentIndeterminate.value = false\n  ':''}if (!controlled) internalChecked.value = next\n  props.onCheckedChange?.(next)\n}\n${native.root==='span'?`function activateOnSpace(event: KeyboardEvent) {\n  if (event.code === 'Space' || event.key === ' ') { event.preventDefault(); activate(event) }\n}\n`:''}`,
    template:`<${native.root} v-bind="$attrs"${rootAttrs} role="${role}"${styleClass} :aria-label="((props as any).ariaLabel ?? $attrs['aria-label'])" :aria-checked="${aria}" :aria-disabled="props.${state.disabled.prop} || undefined" :disabled="props.${state.disabled.prop} || undefined" @click="activate"${keyHandler}><slot />{{ props.label }}</${native.root}>`
  };
}
function nativeInputBinding(model, library) {
  const behavior = library.behaviorCapabilities.bindings.find(binding => binding.component === model.component && binding.id === 'native-input-control' && binding.support === 'supported');
  if (!behavior || behavior.missingOperations.length || behavior.controlled.supported || !behavior.uncontrolled.supported) return null;
  const field = library.nativeField.controls.find(control => control.component === behavior.component && control.support === 'supported');
  if (!field || field.value.owner !== 'native-uncontrolled' || field.value.initialProp !== behavior.uncontrolled.prop || field.value.transition.callbackValue !== 'current native value') return null;
  if (!['input','textarea'].includes(field.root) || behavior.requirements.dom.join('\0') !== field.root) return null;
  return {behavior,field};
}
function fieldCompositionControl(model, library) {
  if (library.fieldComposition?.support !== 'supported') return null;
  return library.fieldComposition.controls.find(control => control.component === model.component) ?? null;
}
function nativeInputSource({behavior,field}, composition) {
  const composedTemplate = composition?.ownsControl
    ? `<div v-if="props.label !== undefined"><label :for="controlId">{{ props.label }}</label><${field.root} v-bind="nativeAttrs" :id="controlId" :aria-label="nativeAriaLabel" :value="props.${behavior.uncontrolled.prop}" :disabled="props.disabled || undefined" @input="handleNativeInput"${field.root==='input'?' />':`>{{ props.${behavior.uncontrolled.prop} }}</${field.root}>`}</div><${field.root} v-else v-bind="nativeAttrs" :aria-label="nativeAriaLabel" :value="props.${behavior.uncontrolled.prop}" :disabled="props.disabled || undefined" @input="handleNativeInput"${field.root==='input'?' />':`>{{ props.${behavior.uncontrolled.prop} }}</${field.root}>`}`
    : null;
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    props:[
      {name:behavior.uncontrolled.prop,required:false,type:'string'},
      {name:'disabled',required:false,type:'boolean'},
      {name:'label',required:false,type:'string'},
      {name:'onChange',required:false,type:'unknown'},
    ],
    setup:`const nativeAttrs = computed(() => Object.fromEntries(Object.entries(useAttrs()).filter(([name]) => name !== 'id').map(([name, value]) => [name.replace(/[A-Z]/g, letter => '-' + letter.toLowerCase()), value])))\nconst nativeAriaLabel = computed(() => (props as any).ariaLabel ?? (props as any)['aria-label'])\n${composition?.ownsControl ? "const controlId = useId()\n" : ''}function handleNativeInput(event: Event) {\n  props.onChange?.((event.currentTarget as HTMLInputElement | HTMLTextAreaElement).value)\n}\n`,
    template:composedTemplate ?? `<${field.root} v-bind="nativeAttrs" :aria-label="nativeAriaLabel" :value="props.${behavior.uncontrolled.prop}" :disabled="props.disabled || undefined" @input="handleNativeInput"${field.root==='input'?' />':`>{{ props.${behavior.uncontrolled.prop} }}</${field.root}>`}`
  };
}
function clipboardCopyBinding(model, library) {
  const capability = library.clipboardCopy;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function clipboardCopySource(capability) {
  return {
    imports:'computed, ref, useAttrs, useSlots',
    setup:`const copyAnnouncement = ref('')
async function copyText() {
  await navigator.clipboard.writeText(props.${vuePropName(capability.copySource.prop)} ?? props.${vuePropName(capability.copySource.fallback)})
  props.onCopy?.()
  copyAnnouncement.value = ${JSON.stringify(capability.behavior.announcesSuccess)}
}
`,
    template:`<div><span>{{ props.${vuePropName(capability.copySource.fallback)} }}</span><button type="button" @click="copyText">Copy</button><span aria-live="polite">{{ copyAnnouncement }}</span></div>`
  };
}
function radioGroupBinding(model, library) {
  const capability = library.radioGroup;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function radioGroupSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, nextTick, ref, useAttrs, useSlots',
    setup:`type RadioFixture = { kind: 'radio-group'; legend: string; items: Array<{ label: string; value: unknown; disabled?: boolean }>; defaultValue?: unknown; value?: unknown; disabled?: boolean }
const radioFixture = computed(() => props.fixture as RadioFixture)
const controlled = computed(() => Object.prototype.hasOwnProperty.call(radioFixture.value ?? {}, 'value'))
const internalValue = ref(radioFixture.value?.defaultValue)
const selectedValue = computed(() => controlled.value ? radioFixture.value?.value : internalValue.value)
const groupRef = ref<HTMLElement | null>(null)
function selectRadio(item: RadioFixture['items'][number]) {
  if (radioFixture.value?.disabled || item.disabled) return
  if (!controlled.value) internalValue.value = item.value
  ;(props.setValue ?? props.onValueChange)?.(item.value)
  nextTick(() => { if (groupRef.value) { groupRef.value.setAttribute('tabindex', '-1'); groupRef.value.focus() } })
}
function selectNext(index: number, event: KeyboardEvent) {
  if (event.key !== 'ArrowDown' || radioFixture.value?.disabled) return
  event.preventDefault()
  const items = radioFixture.value?.items ?? []
  for (let offset = 1; offset <= items.length; offset++) {
    const item = items[(index + offset) % items.length]
    if (!item.disabled) { selectRadio(item); return }
  }
}
`,
    template:`<div ref="groupRef" v-bind="$attrs" role="radiogroup" :aria-label="radioFixture.legend"><div v-for="(item, index) in radioFixture.items" :key="String(item.value)" role="radio" :tabindex="(radioFixture.disabled || item.disabled) ? undefined : 0" :aria-checked="item.value === selectedValue" :aria-label="item.label" :aria-disabled="radioFixture.disabled || item.disabled || undefined" @click="selectRadio(item)" @keydown="selectNext(index, $event)">{{ item.label }}</div></div>`
  };
}
function tabsNavigationBinding(model, library) {
  const capability = library.tabsNavigation;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function tabsNavigationSource(capability) {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, getCurrentInstance, nextTick, ref, useAttrs, useSlots, watch',
    setup:`type TabItem = { value: string; label: string }
const instance = getCurrentInstance()
const controlled = computed(() => Object.prototype.hasOwnProperty.call(instance?.vnode.props ?? {}, ${JSON.stringify(capability.selection.controlledProp)}))
const internalValue = ref(props.selectedValue ?? props.tabs?.[0]?.value)
const committedValue = computed(() => controlled.value ? props.selectedValue : internalValue.value)
const focusedIndex = ref(Math.max(0, props.tabs?.findIndex((tab: TabItem) => tab.value === committedValue.value) ?? 0))
const tabButtons = ref<HTMLButtonElement[]>([])
watch(committedValue, value => { const index = props.tabs?.findIndex((tab: TabItem) => tab.value === value) ?? -1; if (index >= 0) focusedIndex.value = index })
function commit(value: string) {
  if (!controlled.value) internalValue.value = value
  props.onValueChange?.(value)
  nextTick(() => tabButtons.value.find(button => button.getAttribute('aria-selected') === 'true')?.focus())
}
function moveNext(index: number, event: KeyboardEvent) {
  if (event.key !== 'ArrowRight') return
  const next = Math.min(index + 1, (props.tabs?.length ?? 1) - 1)
  if (next === index) return
  event.preventDefault()
  focusedIndex.value = next
  nextTick(() => tabButtons.value[next]?.focus())
  if (props.activateOnFocus) commit(props.tabs[next].value)
}
function activate(tab: TabItem, event: KeyboardEvent) {
  if (event.key !== 'Enter' && event.key !== ' ' && event.code !== 'Space') return
  event.preventDefault()
  commit(tab.value)
}
`,
    template:`<div><div role="tablist"><button v-for="(tab, index) in props.tabs" :key="tab.value" :ref="element => { if (element) tabButtons[index] = element as HTMLButtonElement }" type="button" role="tab" :tabindex="index === focusedIndex ? 0 : -1" :aria-selected="tab.value === committedValue" @click="commit(tab.value)" @keydown="moveNext(index, $event); activate(tab, $event)">{{ tab.label }}</button></div></div>`
  };
}
function menubarNavigationBinding(model, library) {
  const capability = library.menubarNavigation;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function menubarNavigationSource(capability) {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, nextTick, ref, useAttrs, useSlots',
    setup:`type MenuBarOption = { id: string; tooltip: string; icon: string; onClick?: () => void }
const menuButtons = ref<HTMLButtonElement[]>([])
const activeIndex = computed(() => typeof props.isActive === 'string' && props.optionIds
  ? (props.options?.findIndex((option: MenuBarOption) => option.id === props.isActive) ?? -1)
  : typeof props.isActive === 'number' ? props.isActive : -1)
function moveFocus(index: number, event: KeyboardEvent) {
  if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') return
  const count = props.options?.length ?? 0
  if (!count) return
  event.preventDefault()
  const next = (index + (event.key === 'ArrowRight' ? 1 : -1) + count) % count
  nextTick(() => menuButtons.value[next]?.focus())
}
function activate(option: MenuBarOption) { option.onClick?.() }
`,
    template:`<nav class="${esc(capability.root.classes.join(' '))}"><button v-for="(option, index) in props.options" :key="option.id" :ref="element => { if (element) menuButtons[index] = element as HTMLButtonElement }" type="button" :class="{ active: index === activeIndex }" :aria-label="option.tooltip" :title="option.tooltip" @keydown="moveFocus(index, $event)" @click="activate(option)"><span aria-hidden="true">{{ option.icon }}</span></button></nav>`
  };
}
function dialogLayerBinding(model, library) {
  const capability = library.dialogLayer;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function dialogLayerSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, getCurrentInstance, nextTick, ref, useAttrs, useSlots',
    setup:`type DialogFixtureNode = { export?: string; text?: string; children?: DialogFixtureNode[] }
const instance = getCurrentInstance()
const controlled = computed(() => Object.prototype.hasOwnProperty.call(instance?.vnode.props ?? {}, 'open'))
const internalOpen = ref(false)
const currentOpen = computed(() => controlled.value ? Boolean(props.open) : internalOpen.value)
const triggerRef = ref<HTMLButtonElement | null>(null)
const dialogRef = ref<HTMLElement | null>(null)
const dialogFixture = computed(() => props.fixture as DialogFixtureNode | undefined)
const fixtureChildren = (node?: DialogFixtureNode) => node?.children ?? []
const fixturePart = (name: string) => fixtureChildren(dialogFixture.value).find(node => node.export === name)
const contentRoot = computed(() => fixtureChildren(dialogFixture.value).find(node => node.export === 'root'))
const contentPart = (name: string) => fixtureChildren(contentRoot.value).find(node => node.export === name)
const partText = (node?: DialogFixtureNode): string => node ? String(node.text ?? '') + fixtureChildren(node).map(partText).join('') : ''
const triggerText = computed(() => partText(fixturePart('.Trigger')))
const titleText = computed(() => partText(contentPart('.Title')))
const descriptionText = computed(() => partText(contentPart('.Description')))
const closeText = computed(() => partText(contentPart('.Close')))
function setOpen(next: boolean) {
  if (!controlled.value) internalOpen.value = next
  props.onOpenChange?.(next)
  nextTick(() => next ? dialogRef.value?.focus() : triggerRef.value?.focus())
}
`,
    template:`<button ref="triggerRef" type="button" data-kumo-component="Dialog" data-kumo-part="trigger" aria-haspopup="dialog" @click="setOpen(true)">{{ triggerText }}<Teleport v-if="currentOpen" to="body"><div ref="dialogRef" role="dialog" tabindex="-1"><h2 v-if="titleText">{{ titleText }}</h2><p v-if="descriptionText">{{ descriptionText }}</p><button v-if="closeText" type="button" data-kumo-part="close" @click="setOpen(false)">{{ closeText }}</button></div></Teleport></button>`
  };
}
function popoverLayerBinding(model, library) {
  const capability = library.popoverLayer;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function popoverLayerSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, getCurrentInstance, nextTick, onMounted, ref, useAttrs, useSlots',
    setup:`type PopoverFixtureNode = { export?: string; text?: string; props?: Record<string, any>; children?: PopoverFixtureNode[] }
const instance = getCurrentInstance()
const controlled = computed(() => Object.prototype.hasOwnProperty.call(instance?.vnode.props ?? {}, 'open'))
const internalOpen = ref(Boolean(props.defaultOpen))
const currentOpen = computed(() => controlled.value ? Boolean(props.open) : internalOpen.value)
const popoverFixture = computed(() => props.fixture as PopoverFixtureNode | undefined)
const fixtureChildren = (node?: PopoverFixtureNode) => node?.children ?? []
const fixturePart = (name: string) => fixtureChildren(popoverFixture.value).find(node => node.export === name)
const partText = (node?: PopoverFixtureNode): string => node ? String(node.text ?? '') + fixtureChildren(node).map(partText).join('') : ''
const triggerPart = computed(() => fixturePart('.Trigger'))
const contentPart = computed(() => fixturePart('.Content'))
const triggerRef = ref<HTMLButtonElement | null>(null)
const contentRef = ref<HTMLElement | null>(null)
const mounted = ref(false)
const resolvedSide = ref('bottom')
const requestedSide = computed(() => String(contentPart.value?.props?.side ?? 'bottom'))
const align = computed(() => String(contentPart.value?.props?.align ?? 'center'))
const positionMethod = computed(() => String(contentPart.value?.props?.positionMethod ?? 'absolute'))
function resolveCollision() {
  resolvedSide.value = requestedSide.value
  if (requestedSide.value !== 'top') return
  const trigger = triggerRef.value?.getBoundingClientRect()
  const contentHeight = contentRef.value?.getBoundingClientRect().height ?? 0
  const offset = Number(contentPart.value?.props?.sideOffset ?? 8)
  if (trigger && trigger.top < contentHeight + offset) resolvedSide.value = 'bottom'
}
onMounted(() => { mounted.value = true; if (currentOpen.value) nextTick(resolveCollision) })
function setOpen(next: boolean) {
  if (!controlled.value) internalOpen.value = next
  props.onOpenChange?.(next)
  if (next) nextTick(resolveCollision)
  else nextTick(() => triggerRef.value?.focus())
}
function handleKey(event: KeyboardEvent) {
  if (event.key !== 'Escape' || !currentOpen.value) return
  event.preventDefault()
  setOpen(false)
  nextTick(() => triggerRef.value?.focus())
}
`,
    template:`<button ref="triggerRef" v-bind="$attrs" type="button" tabindex="0" aria-haspopup="dialog" :aria-expanded="currentOpen" data-kumo-component="Popover" data-kumo-part="trigger" @click="setOpen(true)" @keydown="handleKey">{{ partText(triggerPart) }}<Teleport v-if="mounted && currentOpen" to="body"><div ref="contentRef" role="dialog" :data-side="resolvedSide" :data-align="align" :data-position-method="positionMethod" @keydown="handleKey"><template v-for="(child, index) in fixtureChildren(contentPart)" :key="index"><h2 v-if="child.export === '.Title'">{{ partText(child) }}</h2><p v-else-if="child.export === '.Description'">{{ partText(child) }}</p><button v-else-if="child.export === '.Close'" type="button" @click.stop="setOpen(false)">{{ partText(child) }}</button><template v-else>{{ partText(child) }}</template></template></div></Teleport></button>`
  };
}
function dropdownMenuLayerBinding(model, library) {
  const capability = library.dropdownMenuLayer;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function dropdownMenuLayerSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, nextTick, ref, useAttrs, useSlots',
    setup:`type DropdownFixtureNode = { export?: string; text?: string; props?: Record<string, any>; children?: DropdownFixtureNode[] }
const dropdownFixture = computed(() => props.fixture as DropdownFixtureNode | undefined)
const fixtureChildren = (node?: DropdownFixtureNode) => node?.children ?? []
const fixturePart = (node: DropdownFixtureNode | undefined, name: string) => fixtureChildren(node).find(child => child.export === name)
const partText = (node?: DropdownFixtureNode): string => node ? String(node.text ?? '') + fixtureChildren(node).map(partText).join('') : ''
const triggerPart = computed(() => fixturePart(dropdownFixture.value, '.Trigger'))
const contentPart = computed(() => fixturePart(dropdownFixture.value, '.Content'))
const menuEntries = computed(() => fixtureChildren(contentPart.value).flatMap(node => node.export === '.Item' || node.export === '.Sub' ? [node] : []))
const triggerRef = ref<HTMLButtonElement | null>(null)
const itemRefs = ref<HTMLButtonElement[]>([])
const open = ref(false)
const submenuOpen = ref(false)
const activeIndex = ref(-1)
const disabledSkipped = ref(false)
function setOpen(next: boolean) { open.value = next; props.onOpenChange?.(next) }
function focusEntry(index: number) { activeIndex.value = index; nextTick(() => itemRefs.value[index]?.focus()) }
function openMenu(focusFirst = false) { if (!open.value) setOpen(true); if (focusFirst) { const index = menuEntries.value.findIndex(entry => !entry.props?.disabled); if (index >= 0) focusEntry(index) } }
function triggerKey(event: KeyboardEvent) { if (event.key !== 'ArrowDown') return; event.preventDefault(); openMenu(true) }
function selectItem(entry: DropdownFixtureNode) {
  const label = partText(entry)
  props.onSelect?.(label)
  setOpen(false)
  props.onOpenChange?.(false)
  submenuOpen.value = false
  nextTick(() => { (document.activeElement as HTMLElement | null)?.blur?.(); document.body.focus() })
}
function entryKey(event: KeyboardEvent) {
  if (event.key.toLowerCase() === 'm') {
    event.preventDefault()
    const index = menuEntries.value.findIndex(entry => entry.export === '.Sub' && partText(fixturePart(entry, '.SubTrigger')).toLowerCase().startsWith('m'))
    disabledSkipped.value = menuEntries.value.some((entry, entryIndex) => entryIndex < index && Boolean(entry.props?.disabled))
    if (index >= 0) focusEntry(index)
  } else if (event.key === 'ArrowRight') {
    event.preventDefault()
    submenuOpen.value = true
  } else if (event.key === 'Escape') {
    event.preventDefault()
    open.value = false
    submenuOpen.value = false
    props.onOpenChange?.(false)
    nextTick(() => triggerRef.value?.focus())
  }
}
`,
    template:`<button ref="triggerRef" v-bind="$attrs" type="button" tabindex="0" aria-haspopup="menu" :aria-expanded="open" data-kumo-component="DropdownMenu" data-kumo-part="trigger" :data-disabled-skipped="disabledSkipped || undefined" @click="openMenu(false)" @keydown="triggerKey">{{ partText(triggerPart) }}<Teleport v-if="open" to="body"><div role="menu"><template v-for="(entry, index) in menuEntries" :key="index"><button v-if="entry.export === '.Item'" :ref="el => { if (el) itemRefs[index] = el as HTMLButtonElement }" type="button" role="menuitem" :tabindex="activeIndex === index ? 0 : -1" :disabled="entry.props?.disabled || undefined" :data-highlighted="activeIndex === index || undefined" @click="selectItem(entry)" @keydown="entryKey">{{ partText(entry) }}</button><button v-else :ref="el => { if (el) itemRefs[index] = el as HTMLButtonElement }" type="button" role="menuitem" :tabindex="activeIndex === index ? 0 : -1" :data-highlighted="activeIndex === index || undefined" aria-haspopup="menu" :aria-expanded="submenuOpen" @keydown="entryKey">{{ partText(fixturePart(entry, '.SubTrigger')) }}</button><div v-if="entry.export === '.Sub' && submenuOpen" role="menu"><button v-for="(nested, nestedIndex) in fixtureChildren(fixturePart(entry, '.SubContent'))" :key="nestedIndex" type="button" role="menuitem" tabindex="-1" @keydown="entryKey">{{ partText(nested) }}</button></div></template></div></Teleport></button>`
  };
}
function sensitiveInputBinding(model, library) {
  const capability = library.sensitiveInput;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function sensitiveInputSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, nextTick, ref, useAttrs, useSlots',
    setup:`const sensitiveValue = ref(props.defaultValue ?? '')
const revealed = ref(false)
const sensitiveInputRef = ref<HTMLInputElement | null>(null)
const copyAnnouncement = ref('')
function revealValue() {
  revealed.value = true
  nextTick(() => sensitiveInputRef.value?.focus())
}
function updateSensitiveValue(event: Event) {
  sensitiveValue.value = (event.currentTarget as HTMLInputElement).value
  props.onValueChange?.(sensitiveValue.value)
}
async function copySensitiveValue() {
  await navigator.clipboard.writeText(sensitiveValue.value)
  copyAnnouncement.value = 'Copied to clipboard'
  props.onCopy?.()
}
`,
    template:`<div v-bind="$attrs" data-kumo-component="SensitiveInput"><label>{{ props.label }}</label><div data-kumo-part="masked-container" @click="revealValue">{{ revealed ? sensitiveValue : 'Value hidden' }}</div><input ref="sensitiveInputRef" type="password" :value="sensitiveValue" @input="updateSensitiveValue" /><button type="button" @click="revealValue">Reveal</button><button type="button" @click="copySensitiveValue">Copy</button><div aria-live="polite">{{ copyAnnouncement }}</div></div>`
  };
}
function comboboxBinding(model, library) {
  const capability = library.comboboxCollection;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function comboboxSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, nextTick, ref, useAttrs, useSlots',
    setup:`type ComboboxFixtureNode = { export?: string; text?: string; props?: Record<string, unknown>; children?: ComboboxFixtureNode[] }
const comboboxFixture = computed(() => props.fixture as ComboboxFixtureNode | undefined)
const fixtureChildren = (node?: ComboboxFixtureNode) => node?.children ?? []
const fixturePart = (node: ComboboxFixtureNode | undefined, name: string) => fixtureChildren(node).find(child => child.export === name)
const triggerInput = computed(() => fixturePart(comboboxFixture.value, '.TriggerInput'))
const content = computed(() => fixturePart(comboboxFixture.value, '.Content'))
const list = computed(() => fixturePart(content.value, '.List'))
const options = computed(() => fixtureChildren(list.value).filter(item => item.export === '.Item'))
const partText = (node?: ComboboxFixtureNode): string => node ? String(node.text ?? '') + fixtureChildren(node).map(partText).join('') : ''
const inputRef = ref<HTMLInputElement | null>(null)
const open = ref(false)
const highlightedIndex = ref(-1)
const value = ref('')
function setOpen(next: boolean) { open.value = next; if (!next) highlightedIndex.value = -1; props.onOpenChange?.(next) }
function openList() { if (!open.value) setOpen(true) }
function handleKey(event: KeyboardEvent) {
  if (event.key === 'ArrowDown') { event.preventDefault(); openList(); highlightedIndex.value = Math.min(highlightedIndex.value + 1, options.value.length - 1) }
  else if (event.key === 'Enter' && open.value && highlightedIndex.value >= 0) {
    event.preventDefault()
    const selected = options.value[highlightedIndex.value]
    value.value = String(selected?.props?.value ?? partText(selected))
    props.onValueChange?.(value.value)
    setOpen(false)
    nextTick(() => inputRef.value?.focus())
  }
}
`,
    template:`<input ref="inputRef" v-bind="$attrs" role="combobox" :placeholder="triggerInput?.props?.placeholder as string | undefined" :value="value" :aria-expanded="open" @click="openList" @keydown="handleKey" /><ul role="listbox" :hidden="!open"><li v-for="(item, index) in options" :key="String(item.props?.value ?? index)" role="option" :data-value="item.props?.value" :aria-selected="index === highlightedIndex">{{ partText(item) }}</li></ul>`
  };
}
function autocompleteBinding(model, library) {
  const capability = library.autocompleteCollection;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function autocompleteSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, nextTick, ref, useAttrs, useSlots',
    setup:`type AutocompleteFixtureNode = { export?: string; text?: string; props?: Record<string, unknown>; children?: AutocompleteFixtureNode[] }
const autocompleteFixture = computed(() => props.fixture as AutocompleteFixtureNode | undefined)
const fixtureChildren = (node?: AutocompleteFixtureNode) => node?.children ?? []
const fixturePart = (node: AutocompleteFixtureNode | undefined, name: string) => fixtureChildren(node).find(child => child.export === name)
const inputGroup = computed(() => fixturePart(autocompleteFixture.value, '.InputGroup'))
const content = computed(() => fixturePart(autocompleteFixture.value, '.Content'))
const list = computed(() => fixturePart(content.value, '.List'))
const options = computed(() => fixtureChildren(list.value).filter(item => item.export === '.Item'))
const partText = (node?: AutocompleteFixtureNode): string => node ? String(node.text ?? '') + fixtureChildren(node).map(partText).join('') : ''
const inputRef = ref<HTMLInputElement | null>(null)
const open = ref(false)
const highlightedIndex = ref(-1)
const value = ref('')
function setOpen(next: boolean) { open.value = next; if (!next) highlightedIndex.value = -1; props.onOpenChange?.(next) }
function handleInput(event: Event) {
  value.value = (event.currentTarget as HTMLInputElement).value
  props.onValueChange?.(value.value)
  if (!open.value) setOpen(true)
}
function handleKey(event: KeyboardEvent) {
  if (event.key === 'ArrowDown') { event.preventDefault(); highlightedIndex.value = options.value.length ? 0 : -1 }
  else if (event.key === 'Enter' && open.value && highlightedIndex.value >= 0) {
    event.preventDefault()
    const selected = options.value[highlightedIndex.value]
    value.value = String(selected?.props?.value ?? partText(selected))
    props.onValueChange?.(value.value)
    setOpen(false)
    nextTick(() => inputRef.value?.focus())
  }
}
`,
    template:`<input ref="inputRef" v-bind="$attrs" role="combobox" :placeholder="inputGroup?.props?.placeholder as string | undefined" :value="value" :aria-expanded="open" @input="handleInput" @keydown="handleKey" /><ul role="listbox" :hidden="!open"><li v-for="(item, index) in options" :key="String(item.props?.value ?? index)" role="option" :data-value="item.props?.value" :aria-selected="index === highlightedIndex">{{ partText(item) }}</li></ul>`
  };
}
function commandPaletteBinding(model, library) {
  const capability = library.commandPalette;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function commandPaletteSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, nextTick, onMounted, ref, useAttrs, useSlots',
    setup:`type CommandPaletteFixtureNode = { export?: string; text?: string; props?: Record<string, any>; children?: CommandPaletteFixtureNode[] }
const paletteFixture = computed(() => props.fixture as CommandPaletteFixtureNode | undefined)
const fixtureChildren = (node?: CommandPaletteFixtureNode) => node?.children ?? []
const fixturePart = (node: CommandPaletteFixtureNode | undefined, name: string) => fixtureChildren(node).find(child => child.export === name)
const partText = (node?: CommandPaletteFixtureNode): string => node ? String(node.text ?? '') + fixtureChildren(node).map(partText).join('') : ''
const highlightedText = computed(() => paletteFixture.value?.export === '.HighlightedText')
const highlightSegments = computed(() => {
  const text = String(paletteFixture.value?.props?.text ?? '')
  const ranges = (paletteFixture.value?.props?.highlights ?? []) as Array<[number, number]>
  const segments: Array<{ text: string; marked: boolean }> = []
  let cursor = 0
  for (const [start, end] of ranges.toSorted((a, b) => a[0] - b[0])) {
    if (start > cursor) segments.push({text: text.slice(cursor, start), marked: false})
    segments.push({text: text.slice(start, end + 1), marked: true})
    cursor = Math.max(cursor, end + 1)
  }
  if (cursor < text.length) segments.push({text: text.slice(cursor), marked: false})
  return segments
})
const inputPart = computed(() => fixturePart(paletteFixture.value, '.Input'))
const listPart = computed(() => fixturePart(paletteFixture.value, '.List'))
const items = computed(() => fixtureChildren(listPart.value).filter(item => item.export === '.Item'))
const inputRef = ref<HTMLInputElement | null>(null)
const open = ref(Boolean(paletteFixture.value?.props?.open))
const value = ref('')
const highlightedIndex = ref(items.value.length ? 0 : -1)
onMounted(() => { if (!highlightedText.value && highlightedIndex.value >= 0) props.onHighlightChange?.(String(items.value[highlightedIndex.value]?.props?.value ?? partText(items.value[highlightedIndex.value]))) })
function handleInput(event: Event) { value.value = (event.currentTarget as HTMLInputElement).value; props.onValueChange?.(value.value) }
function handlePaletteKey(event: KeyboardEvent) {
  if (event.key === 'ArrowDown' && items.value.length) {
    event.preventDefault()
    highlightedIndex.value = Math.min(highlightedIndex.value + 1, items.value.length - 1)
    props.onHighlightChange?.(String(items.value[highlightedIndex.value]?.props?.value ?? partText(items.value[highlightedIndex.value])))
  } else if (event.key === 'Escape') {
    event.preventDefault()
    open.value = false
    props.onOpenChange?.(false)
    inputRef.value?.blur()
    nextTick(() => (document.activeElement as HTMLElement | null)?.blur?.())
  }
}
`,
    template:`<span v-if="highlightedText"><template v-for="(segment, index) in highlightSegments" :key="index"><mark v-if="segment.marked">{{ segment.text }}</mark><template v-else>{{ segment.text }}</template></template></span><div v-else v-bind="$attrs" data-kumo-component="CommandPalette"><input ref="inputRef" :placeholder="inputPart?.props?.placeholder" :value="value" @input="handleInput" @keydown="handlePaletteKey" /><ul :hidden="!open"><li v-for="(item, index) in items" :key="String(item.props?.value ?? index)" :data-highlighted="index === highlightedIndex || undefined">{{ partText(item) }}</li></ul></div>`
  };
}
function inputGroupBinding(model, library) {
  const capability = library.inputGroupComposition;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  return capability;
}
function inputGroupSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, ref, useAttrs, useId, useSlots',
    setup:`type InputGroupFixtureNode = { export?: string; text?: string; props?: Record<string, unknown>; children?: InputGroupFixtureNode[] }
const inputGroupFixture = computed(() => props.fixture as InputGroupFixtureNode | undefined)
const fixtureChildren = (node?: InputGroupFixtureNode) => node?.children ?? []
const fixturePart = (name: string) => fixtureChildren(inputGroupFixture.value).find(node => node.export === name)
const partText = (node?: InputGroupFixtureNode): string => node ? String(node.text ?? '') + fixtureChildren(node).map(partText).join('') : ''
const inputGroupProps = computed(() => inputGroupFixture.value?.props ?? {})
const inputPart = computed(() => fixturePart('.Input'))
const inputId = useId()
const inputValue = ref('')
function trackInput(event: Event) { inputValue.value = (event.currentTarget as HTMLInputElement).value }
`,
    template:`<div v-bind="$attrs" data-kumo-component="InputGroup"><label v-if="inputGroupProps.label !== undefined" :for="inputId">{{ inputGroupProps.label }}</label><p v-if="inputGroupProps.description !== undefined">{{ inputGroupProps.description }}</p><template v-for="(part, index) in fixtureChildren(inputGroupFixture)" :key="part.export ?? index"><span v-if="part.export === '.Addon'" data-kumo-part="Addon">{{ partText(part) }}</span><input v-else-if="part.export === '.Input'" :id="inputId" :aria-label="inputPart?.props?.['aria-label'] as string | undefined" :disabled="props.disabled || undefined" :required="inputGroupProps.required as boolean | undefined" :value="inputValue" @input="trackInput" /><button v-else-if="part.export === '.Button'" type="button" :data-variant="part.props?.variant">{{ partText(part) }}</button><span v-else-if="part.export === '.Suffix'" data-kumo-part="Suffix">{{ partText(part) }}</span></template></div>`
  };
}
function datePickerBinding(model, library) {
  const capability = library.dateRange?.observableImplementation?.datePicker;
  if (capability?.support !== 'supported' || model.component !== 'date-picker') return null;
  return capability;
}
function datePickerSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, getCurrentInstance, ref, useAttrs, useSlots',
    setup:`type CalendarDay = { iso: string; day: number }
const instance = getCurrentInstance()
const controlled = computed(() => Object.prototype.hasOwnProperty.call(instance?.vnode.props ?? {}, 'selectedDate'))
const internalSelectedDate = ref(props.selectedDate)
const selectedDate = computed(() => controlled.value ? props.selectedDate : internalSelectedDate.value)
const padDatePart = (value: number) => String(value).padStart(2, '0')
const isoDate = (date: Date) => \`${'${String(date.getUTCFullYear()).padStart(4, \'0\')}-${padDatePart(date.getUTCMonth() + 1)}-${padDatePart(date.getUTCDate())}'}\`
const parseDate = (value: unknown, fallback: string) => {
  const match = typeof value === 'string' && /^([0-9]{4})-([0-9]{2})-([0-9]{2})$/.exec(value)
  if (!match) return new Date(fallback + 'T00:00:00.000Z')
  const date = new Date(Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3])))
  return Number.isNaN(date.getTime()) ? new Date(fallback + 'T00:00:00.000Z') : date
}
const initialMonth = parseDate(props.defaultMonthDate, '2025-01-01')
const monthDate = ref(new Date(Date.UTC(initialMonth.getUTCFullYear(), initialMonth.getUTCMonth(), 1)))
const calendarDays = computed<CalendarDay[]>(() => {
  const first = monthDate.value
  const start = new Date(Date.UTC(first.getUTCFullYear(), first.getUTCMonth(), 1 - first.getUTCDay()))
  const daysInMonth = new Date(Date.UTC(first.getUTCFullYear(), first.getUTCMonth() + 1, 0)).getUTCDate()
  const count = Math.ceil((first.getUTCDay() + daysInMonth) / 7) * 7
  return Array.from({ length: count }, (_, index) => {
    const date = new Date(start.getTime() + index * 86400000)
    return { iso: isoDate(date), day: date.getUTCDate() }
  })
})
const calendarRows = computed(() => Array.from({ length: calendarDays.value.length / 7 }, (_, row) => calendarDays.value.slice(row * 7, row * 7 + 7)))
function isDisabled(iso: string) { return Boolean((props.disabledBeforeDate && iso < props.disabledBeforeDate) || (props.disabledAfterDate && iso > props.disabledAfterDate)) }
function changeMonth(offset: number) { monthDate.value = new Date(Date.UTC(monthDate.value.getUTCFullYear(), monthDate.value.getUTCMonth() + offset, 1)) }
function selectDay(iso: string) {
  if (isDisabled(iso)) return
  if (!controlled.value) internalSelectedDate.value = iso
  props.onChange?.(iso)
}
`,
    template:`<div v-bind="$attrs" :aria-label="props.ariaLabel"><button type="button" @click="changeMonth(-1)">Previous</button><button type="button" @click="changeMonth(1)">Next</button><table role="grid"><tbody><tr v-for="(row, rowIndex) in calendarRows" :key="rowIndex"><td v-for="day in row" :key="day.iso"><button type="button" :data-day="day.iso" :disabled="isDisabled(day.iso) || undefined" :aria-selected="day.iso === selectedDate || undefined" @click="selectDay(day.iso)">{{ day.day }}</button></td></tr></tbody></table></div>`
  };
}
function dateRangePickerBinding(model, library) {
  const capability = library.dateRange?.observableImplementation?.dateRangePicker;
  if (capability?.support !== 'supported' || model.component !== 'date-range-picker') return null;
  return capability;
}
function dateRangePickerSource(capability) {
  if (capability.navigationButtons !== 2 || capability.calendarButtons !== 84 || capability.resetButtons !== 1 || capability.totalButtons !== 87) throw new Error('unsupported date-range-picker button contract');
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, nextTick, ref, useAttrs, useSlots',
    setup:`type RangeDay = { iso: string; day: number; inMonth: boolean }
type RangeMonth = { key: string; label: string; days: RangeDay[] }
const rangeRoot = ref<HTMLElement | null>(null)
const startValue = ref<string | null>(null)
const endValue = ref<string | null>(null)
const monthCursor = ref(new Date(Date.UTC(2026, 5, 1)))
const pad = (value: number) => String(value).padStart(2, '0')
const iso = (date: Date) => \`\${date.getUTCFullYear()}-\${pad(date.getUTCMonth() + 1)}-\${pad(date.getUTCDate())}\`
function buildMonth(base: Date): RangeMonth {
  const year = base.getUTCFullYear(), month = base.getUTCMonth()
  const first = new Date(Date.UTC(year, month, 1)), start = new Date(first)
  start.setUTCDate(1 - first.getUTCDay())
  const days = Array.from({length:42}, (_, index) => { const date = new Date(start); date.setUTCDate(start.getUTCDate() + index); return {iso:iso(date),day:date.getUTCDate(),inMonth:date.getUTCMonth() === month} })
  return {key:\`\${year}-\${month}\`,label:new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric',timeZone:'UTC'}).format(first),days}
}
const monthPanels = computed(() => [0,1].map(offset => { const date = new Date(monthCursor.value); date.setUTCMonth(date.getUTCMonth() + offset); return buildMonth(date) }))
const rootClasses = computed(() => props.size === 'sm' && props.variant === 'subtle' ? ${JSON.stringify(capability.classes.smallSubtle.join(' '))} : ${JSON.stringify(capability.classes.default.join(' '))})
function changeMonth(delta: number) { const date = new Date(monthCursor.value); date.setUTCMonth(date.getUTCMonth() + delta); monthCursor.value = date }
function isInRange(value: string) { return Boolean(startValue.value && endValue.value && value >= startValue.value && value <= endValue.value) }
function selectDay(value: string) {
  if (startValue.value === null || endValue.value !== null || value < startValue.value) {
    startValue.value = value
    endValue.value = null
    props.onStartChange?.(value)
    props.onStartDateChange?.(value)
    return
  }
  endValue.value = value
  props.onEndChange?.(value)
  props.onEndDateChange?.(value)
}
function resetRange() {
  startValue.value = null
  endValue.value = null
  props.onStartChange?.(null)
  props.onStartDateChange?.(null)
  props.onEndChange?.(null)
  props.onEndDateChange?.(null)
  nextTick(() => { if (rangeRoot.value) { rangeRoot.value.setAttribute('tabindex', '-1'); rangeRoot.value.focus() } })
}
`,
    template:`<div ref="rangeRoot" v-bind="$attrs" :class="['kumo-date-range',rootClasses]"><div class="kumo-date-range__toolbar"><button type="button" data-navigation="previous" aria-label="Previous month" @click="changeMonth(-1)">Previous</button><button type="button" data-navigation="next" aria-label="Next month" @click="changeMonth(1)">Next</button></div><div class="kumo-date-range__months"><section v-for="month in monthPanels" :key="month.key" class="kumo-date-range__month"><h3>{{ month.label }}</h3><div class="kumo-date-range__weekdays" aria-hidden="true"><span v-for="day in ['Su','Mo','Tu','We','Th','Fr','Sa']" :key="day">{{ day }}</span></div><div class="kumo-date-range__grid" role="grid"><button v-for="day in month.days" :key="day.iso" type="button" :data-day="day.iso" :data-outside-month="!day.inMonth || undefined" :aria-label="day.iso" :aria-selected="day.iso === startValue || day.iso === endValue || undefined" :data-in-range="isInRange(day.iso) || undefined" @click="selectDay(day.iso)">{{ day.day }}</button></div></section></div><div class="kumo-date-range__footer"><span aria-live="polite">{{ startValue ? (endValue ? startValue + ' – ' + endValue : 'Start: ' + startValue) : 'Choose a start date' }}</span><button type="button" data-reset @click="resetRange">Reset dates</button></div></div>`
  };
}
function responsiveSidebarBinding(model, library) {
  const capability = library.responsiveSidebar?.observableImplementation;
  if (capability?.support !== 'supported' || model.component !== library.responsiveSidebar.component) return null;
  return capability;
}
function responsiveSidebarSource(capability) {
  if (capability.expanded?.buttons !== 3 || capability.expanded?.menuItems !== 2 || capability.resize?.width !== 480) throw new Error('unsupported responsive-sidebar observable contract');
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, nextTick, ref, useAttrs, useSlots',
    setup:`type SidebarFixtureNode = { export?: string; text?: string; props?: Record<string, unknown>; children?: SidebarFixtureNode[] }
const sidebarFixture = computed(() => props.fixture as SidebarFixtureNode | undefined)
const fixtureChildren = (node?: SidebarFixtureNode) => node?.children ?? []
const part = (node: SidebarFixtureNode | undefined, name: string) => fixtureChildren(node).find(child => child.export === name)
const partText = (node?: SidebarFixtureNode): string => node ? String(node.text ?? '') + fixtureChildren(node).map(partText).join('') : ''
const providerProps = computed(() => sidebarFixture.value?.props ?? {})
const sidebarRoot = computed(() => part(sidebarFixture.value, 'root'))
const header = computed(() => part(sidebarRoot.value, '.Header'))
const content = computed(() => part(sidebarRoot.value, '.Content'))
const group = computed(() => part(content.value, '.Group'))
const menu = computed(() => part(group.value, '.Menu'))
const menuButtons = computed(() => fixtureChildren(menu.value).filter(node => node.export === '.MenuButton'))
const collapsible = computed(() => part(sidebarRoot.value, '.Collapsible'))
const resizeHandle = computed(() => part(sidebarRoot.value, '.ResizeHandle'))
const open = ref(providerProps.value.defaultOpen !== false)
const width = ref(Number(providerProps.value.defaultWidth ?? 256))
const state = computed(() => open.value ? 'expanded' : 'collapsed')
const resizeRef = ref<HTMLButtonElement | null>(null)
function toggleSidebar() { open.value = !open.value; props.onOpenChange?.(open.value) }
function resizeKey(event: KeyboardEvent) {
  if (event.key !== 'End') return
  event.preventDefault()
  open.value = true
  width.value = Number(providerProps.value.maxWidth ?? ${capability.resize.width})
  props.onOpenChange?.(true)
  props.onWidthChange?.(width.value)
  nextTick(() => resizeRef.value?.focus())
}
`,
    template:`<div v-bind="$attrs" data-sidebar-wrapper="" :data-state="state" data-side="left" :style="{ '--sidebar-width': width + 'px', width: width + 'px' }"><aside :data-state="state" data-side="left" data-collapsible="icon"><template v-if="collapsible"></template><template v-else><header v-if="header">{{ partText(header) }}</header><div v-if="content"><div v-if="group"><span>{{ partText(part(group, '.GroupLabel')) }}</span><ul v-if="menu"><li v-for="(item, index) in menuButtons" :key="index"><button type="button">{{ partText(item) }}</button></li></ul></div></div><footer v-if="part(sidebarRoot, '.Footer')"><button type="button" :aria-expanded="open" :aria-label="open ? 'Collapse sidebar' : 'Expand sidebar'" @click="toggleSidebar">{{ open ? 'Collapse sidebar' : 'Expand sidebar' }}</button></footer><button v-if="resizeHandle" ref="resizeRef" type="button" aria-label="Resize sidebar" @keydown="resizeKey"></button></template></aside></div>`
  };
}
function selectBinding(model, library) {
  const capability = library.collectionListbox?.observableImplementation?.select;
  if (capability?.support !== 'supported' || model.component !== 'select') return null;
  return capability;
}
function selectSource() {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, getCurrentInstance, nextTick, onMounted, ref, useAttrs, useSlots',
    setup:`type SelectFixtureNode = { export?: string; text?: string; props?: Record<string, any>; children?: SelectFixtureNode[] }
type SelectOption = { value: any; label: string; disabled: boolean }
const instance = getCurrentInstance()
const supplied = (name: string) => Object.prototype.hasOwnProperty.call(instance?.vnode.props ?? {}, name)
const fixtureRoot = computed(() => props.fixture as SelectFixtureNode | undefined)
const fixtureTextContent = (node?: SelectFixtureNode): string => node ? String(node.text ?? '') + (node.children ?? []).map(fixtureTextContent).join('') : ''
const selectOptions = computed<SelectOption[]>(() => (fixtureRoot.value?.children ?? []).filter(node => node.export === '.Option').map(node => ({ value: node.props?.value, label: fixtureTextContent(node), disabled: node.props?.disabled === true })))
const multiple = computed(() => Boolean((props as any).multiple))
const valueControlled = supplied('value')
const openControlled = supplied('open')
const internalValue = ref<any>(supplied('defaultValue') ? (props as any).defaultValue : (multiple.value ? [] : null))
const internalOpen = ref(supplied('defaultOpen') ? Boolean((props as any).defaultOpen) : false)
const selectedValue = computed(() => valueControlled ? (props as any).value : internalValue.value)
const selectOpen = computed(() => openControlled ? Boolean((props as any).open) : internalOpen.value)
const triggerRef = ref<HTMLButtonElement | null>(null)
const mounted = ref(false)
onMounted(() => { mounted.value = true })
const optionRefs = ref<HTMLElement[]>([])
const activeIndex = ref(-1)
const highlightScrolled = ref(false)
const selectLabel = computed(() => (props as any).ariaLabel ?? (props as any)['aria-label'])
const equalValue = (a: any, b: any) => a === b || JSON.stringify(a) === JSON.stringify(b)
const isSelected = (value: any) => multiple.value ? (Array.isArray(selectedValue.value) && selectedValue.value.some(item => equalValue(item, value))) : equalValue(selectedValue.value, value)
function emitOpen(next: boolean) { if (!openControlled) internalOpen.value = next; (props as any).onOpenChange?.(next) }
function focusOption(index: number) {
  activeIndex.value = index
  nextTick(() => { const element = optionRefs.value[index]; element?.focus(); if (element) { element.scrollIntoView?.({ block: 'nearest' }); highlightScrolled.value = true } })
}
function firstEnabled() { return selectOptions.value.findIndex(item => !item.disabled) }
function lastEnabled() { for (let i = selectOptions.value.length - 1; i >= 0; i--) if (!selectOptions.value[i].disabled) return i; return -1 }
function openSelect() { if (selectOpen.value) return; emitOpen(true); const index = firstEnabled(); if (index >= 0) focusOption(index) }
function triggerKey(event: KeyboardEvent) { if (event.key === 'ArrowDown') { event.preventDefault(); openSelect(); if (selectOpen.value) { const index = firstEnabled(); if (index >= 0) focusOption(index) } } }
function selectItem(item: SelectOption, index: number) {
  if (item.disabled) return
  if (multiple.value) {
    const current = Array.isArray(selectedValue.value) ? selectedValue.value : []
    const next = current.some(value => equalValue(value, item.value)) ? current : [...current, item.value]
    if (!valueControlled) internalValue.value = next
    ;(props as any).onValueChange?.(next)
    focusOption(index)
    return
  }
  if (!valueControlled) internalValue.value = item.value
  ;(props as any).onValueChange?.(item.value)
  emitOpen(false)
  if (openControlled) focusOption(index)
  else nextTick(() => triggerRef.value?.focus())
}
function optionKey(event: KeyboardEvent) {
  let index = -1
  if (event.key === 'Home') index = firstEnabled()
  else if (event.key === 'End') index = lastEnabled()
  else if (event.key.length === 1) index = selectOptions.value.findIndex(item => !item.disabled && item.label.toLocaleLowerCase().startsWith(event.key.toLocaleLowerCase()))
  else if (event.key === 'Escape') { event.preventDefault(); emitOpen(false); nextTick(() => triggerRef.value?.focus()); return }
  else if (event.key === 'Tab') { event.preventDefault(); emitOpen(false); nextTick(() => triggerRef.value?.focus()); return }
  else return
  if (index >= 0) { event.preventDefault(); focusOption(index) }
}
`,
    template:`<div v-bind="$attrs"><button ref="triggerRef" type="button" tabindex="0" role="combobox" :aria-expanded="String(selectOpen)" aria-haspopup="listbox" :aria-label="selectLabel" data-kumo-component="Select" data-kumo-part="trigger" :data-placeholder="selectedValue == null || (multiple && selectedValue.length === 0) ? '' : undefined" @click="openSelect" @keydown="triggerKey"></button><Teleport v-if="mounted && selectOpen" to="body"><div role="listbox" :aria-multiselectable="multiple || undefined" :data-highlight-scrolled="highlightScrolled || undefined"><div v-for="(item, index) in selectOptions" :key="index" :ref="element => { if (element) optionRefs[index] = element as HTMLElement }" role="option" tabindex="-1" :aria-selected="isSelected(item.value)" :aria-disabled="item.disabled || undefined" :data-value="typeof item.value === 'object' ? item.value?.id : item.value" :data-highlighted="activeIndex === index || undefined" :data-selected="isSelected(item.value) || undefined" @click="selectItem(item, index)" @keydown="optionKey">{{ item.label }}</div></div></Teleport></div>`
  };
}
function toastLifecycleBinding(model, library) {
  const capability = library.toastLifecycle;
  if (capability?.observableImplementation?.support !== 'supported' || model.component !== capability.component) return null;
  return capability.observableImplementation;
}
function toastLifecycleSource(capability) {
  return {
    options:`defineOptions({ inheritAttrs: false })\n`,
    imports:'computed, nextTick, onBeforeUnmount, ref, useAttrs, useSlots',
    setup:`type ToastFixtureNode = { text?: string; props?: Record<string, unknown>; children?: ToastFixtureNode[] }
const visible = ref(false)
const title = ref('')
const description = ref('')
const announcement = computed(() => visible.value ? [title.value, description.value].filter(Boolean).join(' ') : '')
let removalTimer: ReturnType<typeof setTimeout> | undefined
const toastFixtureText = (node?: ToastFixtureNode): string => node ? String(node.text ?? node.props?.children ?? '') + (node.children ?? []).map(toastFixtureText).join('') : ''
const providerText = computed(() => renderContent() || toastFixtureText(props.fixture as ToastFixtureNode | undefined) || 'Application')
function notify() {
  if (removalTimer !== undefined) clearTimeout(removalTimer)
  title.value = ${JSON.stringify(capability.notify.title)}
  description.value = ${JSON.stringify(capability.notify.description)}
  visible.value = true
  props.onNotify?.()
}
function act() { props.onAction?.() }
function closeToast() {
  if (removalTimer !== undefined) clearTimeout(removalTimer)
  removalTimer = setTimeout(() => {
    visible.value = false
    nextTick(() => { (document.activeElement as HTMLElement | null)?.blur?.(); document.body.focus() })
  }, 300)
}
onBeforeUnmount(() => { if (removalTimer !== undefined) clearTimeout(removalTimer) })
`,
    template:`<div v-bind="$attrs" data-kumo-component="Toasty">{{ providerText }}<button type="button" data-notify aria-label="Notify" @click="notify"></button><div v-if="visible" role="status" aria-live="polite" data-toast><div data-toast-title>{{ title }}</div><div data-toast-description>{{ description }}</div><button type="button" data-toast-action @click="act">Action</button><button type="button" aria-label="Close" @click="closeToast">Close</button></div></div>`
  };
}
function paginationBinding(model, library) {
  const capability = library.paginationControls;
  if (capability?.support !== 'supported' || model.component !== capability.component) return null;
  // Exercise the canonical algebra while emitting its equivalent browser-side logic.
  const maximum = maxPage(8, 2);
  clampPage(2, maximum); nextPage(2, maximum); previousPage(2, maximum); commitPageInput(2, '3', maximum);
  return capability;
}
function paginationSource() {
  return {
    imports:'computed, onMounted, ref, useAttrs, useSlots, watch',
    setup:`const maximumPage = computed(() => Math.max(1, Math.ceil(props.totalCount / props.perPage)))
const currentPage = ref(1)
const editingPage = ref('1')
const navRef = ref<HTMLElement | null>(null)
onMounted(() => { currentPage.value = Math.min(maximumPage.value, Math.max(1, props.page)); editingPage.value = String(currentPage.value) })
watch(() => props.page, value => { currentPage.value = Math.min(maximumPage.value, Math.max(1, value)); editingPage.value = String(currentPage.value) })
function proposePage(target: number) {
  const proposal = Math.min(maximumPage.value, Math.max(1, target))
  if (proposal !== currentPage.value) props.setPage?.(proposal)
}
function commitInput(trigger: 'Enter' | 'blur') {
  const text = editingPage.value.trim()
  const restore = () => { editingPage.value = String(currentPage.value) }
  const focusNav = () => { if (trigger === 'blur' && navRef.value) { navRef.value.setAttribute('tabindex', '-1'); navRef.value.focus() } }
  if (!/^[0-9]+$/.test(text)) { restore(); focusNav(); return }
  const parsed = Number(text)
  if (!Number.isSafeInteger(parsed)) { restore(); focusNav(); return }
  const proposal = Math.min(maximumPage.value, Math.max(1, parsed))
  editingPage.value = String(proposal)
  if (proposal !== currentPage.value) props.setPage?.(proposal)
  focusNav()
}
function enterInput(event: KeyboardEvent) { if (event.key === 'Enter') commitInput('Enter') }
`,
    template:`<div data-slot="pagination"><nav ref="navRef" :aria-label="props.labels?.navigation ?? 'Pagination'"><template v-if="props.fixtureMode !== 'simple'"><button type="button" aria-label="First page" :disabled="currentPage === 1" @click="proposePage(1)"></button><button type="button" aria-label="Previous page" :disabled="currentPage === 1" @click="proposePage(currentPage - 1)"></button><input aria-label="Page number" :value="editingPage" @input="editingPage = ($event.currentTarget as HTMLInputElement).value" @keydown="enterInput" @blur="commitInput('blur')" /><button type="button" aria-label="Next page" :disabled="currentPage === maximumPage" @click="proposePage(currentPage + 1)"></button><button type="button" aria-label="Last page" :disabled="currentPage === maximumPage" @click="proposePage(maximumPage)"></button><template v-if="props.fixtureMode === 'dropdown'"><button type="button" aria-label="Page size"></button><button type="button" aria-label="Open page size options"></button></template></template><template v-else><button type="button" :aria-label="props.labels?.previousPage ?? 'Previous page'" :disabled="currentPage === 1" @click="proposePage(currentPage - 1)"></button><button type="button" :aria-label="props.labels?.nextPage ?? 'Next page'" :disabled="currentPage === maximumPage" @click="proposePage(currentPage + 1)"></button></template></nav></div>`
  };
}
function emitComponent(model, library) {
  const implementation = validateImplementation(model.draftImplementation);
  const contentBindingDigest = requireContentBindings(model);
  const defaults = Object.fromEntries(model.props.items.filter(p => p.default != null && !(p.name === 'checked' && toggleBinding(model, library))).map(p => [p.name,p.default]));
  const variants = [...(implementation.semanticVariants ?? [])].sort((a,b)=>b.when.length-a.when.length);
  const declaredProps = new Map(model.props.items.map(p => [p.name,p]));
  const composition = fieldCompositionControl(model, library);
  const nativeInput = nativeInputBinding(model, library);
  const loweredNativeInput = nativeInput && nativeInputSource(nativeInput, composition);
  const clipboardCopy = clipboardCopyBinding(model, library);
  const loweredClipboardCopy = clipboardCopy && clipboardCopySource(clipboardCopy);
  const datePicker = datePickerBinding(model, library);
  const loweredDatePicker = datePicker && datePickerSource();
  const dateRangePicker = dateRangePickerBinding(model, library);
  const loweredDateRangePicker = dateRangePicker && dateRangePickerSource(dateRangePicker);
  const select = selectBinding(model, library);
  const loweredSelect = select && selectSource();
  const toastLifecycle = toastLifecycleBinding(model, library);
  const loweredToastLifecycle = toastLifecycle && toastLifecycleSource(toastLifecycle);
  const responsiveSidebar = responsiveSidebarBinding(model, library);
  const loweredResponsiveSidebar = responsiveSidebar && responsiveSidebarSource(responsiveSidebar);
  const pagination = paginationBinding(model, library);
  const loweredPagination = pagination && paginationSource();
  const menubarNavigation = menubarNavigationBinding(model, library);
  const loweredMenubarNavigation = menubarNavigation && menubarNavigationSource(menubarNavigation);
  const tabsNavigation = tabsNavigationBinding(model, library);
  const loweredTabsNavigation = tabsNavigation && tabsNavigationSource(tabsNavigation);
  const radioGroup = radioGroupBinding(model, library);
  const loweredRadioGroup = radioGroup && radioGroupSource();
  const dialogLayer = dialogLayerBinding(model, library);
  const loweredDialogLayer = dialogLayer && dialogLayerSource();
  const popoverLayer = popoverLayerBinding(model, library);
  const loweredPopoverLayer = popoverLayer && popoverLayerSource();
  const inputGroup = inputGroupBinding(model, library);
  const loweredInputGroup = inputGroup && inputGroupSource();
  const dropdownMenuLayer = dropdownMenuLayerBinding(model, library);
  const loweredDropdownMenuLayer = dropdownMenuLayer && dropdownMenuLayerSource();
  const combobox = comboboxBinding(model, library);
  const loweredCombobox = combobox && comboboxSource();
  const autocomplete = autocompleteBinding(model, library);
  const loweredAutocomplete = autocomplete && autocompleteSource();
  const sensitiveInput = sensitiveInputBinding(model, library);
  const loweredSensitiveInput = sensitiveInput && sensitiveInputSource();
  const commandPalette = commandPaletteBinding(model, library);
  const loweredCommandPalette = commandPalette && commandPaletteSource();
  if (toggleBinding(model, library)) declaredProps.set('defaultChecked',{name:'defaultChecked',required:false,type:'boolean'});
  if (datePicker) {
    declaredProps.set('ariaLabel',{name:'ariaLabel',required:false,type:'string'});
    declaredProps.set('selectedDate',{name:'selectedDate',required:false,type:'string'});
    declaredProps.set('defaultMonthDate',{name:'defaultMonthDate',required:false,type:'string'});
    declaredProps.set('disabledBeforeDate',{name:'disabledBeforeDate',required:false,type:'string'});
    declaredProps.set('disabledAfterDate',{name:'disabledAfterDate',required:false,type:'string'});
    declaredProps.set('onChange',{name:'onChange',required:false,type:'unknown'});
  }
  if (dateRangePicker) { declaredProps.set('onStartChange',{name:'onStartChange',required:false,type:'unknown'}); declaredProps.set('onEndChange',{name:'onEndChange',required:false,type:'unknown'}); }
  if (select) {
    for (const [name,type] of [['ariaLabel','string'],['placeholder','string'],['defaultValue','unknown'],['value','unknown'],['defaultOpen','boolean'],['open','boolean'],['multiple','boolean'],['onOpenChange','unknown'],['onValueChange','unknown']]) declaredProps.set(name,{name,required:false,type});
  }
  if (toastLifecycle) { declaredProps.set('onNotify',{name:'onNotify',required:false,type:'unknown'}); declaredProps.set('onAction',{name:'onAction',required:false,type:'unknown'}); }
  if (responsiveSidebar) { declaredProps.set('onOpenChange',{name:'onOpenChange',required:false,type:'unknown'}); declaredProps.set('onWidthChange',{name:'onWidthChange',required:false,type:'unknown'}); }
  if (pagination) { declaredProps.set('fixtureMode',{name:'fixtureMode',required:false,type:'string'}); declaredProps.set('labels',{name:'labels',required:false,type:'unknown'}); declaredProps.set('setPage',{name:'setPage',required:false,type:'unknown'}); }
  if (radioGroup) { declaredProps.set('setValue',{name:'setValue',required:false,type:'unknown'}); declaredProps.set('onValueChange',{name:'onValueChange',required:false,type:'unknown'}); }
  if (combobox || autocomplete) { declaredProps.set('onOpenChange',{name:'onOpenChange',required:false,type:'unknown'}); declaredProps.set('onValueChange',{name:'onValueChange',required:false,type:'unknown'}); }
  if (dialogLayer || popoverLayer) { declaredProps.set('open',{name:'open',required:false,type:'boolean'}); declaredProps.set('onOpenChange',{name:'onOpenChange',required:false,type:'unknown'}); }
  if (dropdownMenuLayer) { declaredProps.set('onOpenChange',{name:'onOpenChange',required:false,type:'unknown'}); declaredProps.set('onSelect',{name:'onSelect',required:false,type:'unknown'}); }
  if (popoverLayer) declaredProps.set('defaultOpen',{name:'defaultOpen',required:false,type:'boolean'});
  if (tabsNavigation) declaredProps.set('onValueChange',{name:'onValueChange',required:false,type:'unknown'});
  if (menubarNavigation) { declaredProps.set('options',{name:'options',required:false,type:'unknown'}); declaredProps.set('isActive',{name:'isActive',required:false,type:'unknown'}); declaredProps.set('optionIds',{name:'optionIds',required:false,type:'boolean'}); }
  if (sensitiveInput) { declaredProps.set('onValueChange',{name:'onValueChange',required:false,type:'unknown'}); declaredProps.set('onCopy',{name:'onCopy',required:false,type:'unknown'}); }
  if (commandPalette) { declaredProps.set('onHighlightChange',{name:'onHighlightChange',required:false,type:'unknown'}); declaredProps.set('onValueChange',{name:'onValueChange',required:false,type:'unknown'}); declaredProps.set('onOpenChange',{name:'onOpenChange',required:false,type:'unknown'}); }
  for (const prop of loweredNativeInput?.props ?? []) declaredProps.set(prop.name, prop);
  if (clipboardCopy) { declaredProps.set(clipboardCopy.copySource.fallback,{name:clipboardCopy.copySource.fallback,required:false,type:'string'}); declaredProps.set(clipboardCopy.copySource.prop,{name:clipboardCopy.copySource.prop,required:false,type:'string'}); declaredProps.set('onCopy',{name:'onCopy',required:false,type:'unknown'}); }
  for (const variant of variants) for (const predicate of variant.when) if (predicate.kind === 'prop-equals' && predicate.name !== 'children' && !declaredProps.has(predicate.name)) declaredProps.set(predicate.name,{name:predicate.name,required:false,type:'unknown'});
  if (nativeInput) for (const variant of variants) for (const predicate of variant.when) if (predicate.kind === 'prop-equals' && predicate.name !== 'children' && !declaredProps.has(vuePropName(predicate.name))) declaredProps.set(vuePropName(predicate.name),{name:vuePropName(predicate.name),required:false,type:'unknown'});
  const props = [...declaredProps.values()].map(p => `  ${JSON.stringify(p.name)}${p.required && p.name !== 'children' ? '' : '?'}: ${vueType(p.type)}`).join('\n');
  const predicates = variants.map(v => v.when.map(x => semanticPredicate(x.kind === 'prop-equals' && x.name !== 'children' ? {...x,name:vuePropName(x.name)} : x,{props:'semanticValues',fixture:'fixture',content:'renderContent()',equal:'semanticEqual'})).join(' && ') || 'true');
  const semantic = (select || datePicker || dateRangePicker || toastLifecycle || responsiveSidebar || nativeInput || clipboardCopy || pagination || radioGroup || tabsNavigation || menubarNavigation || dialogLayer || popoverLayer || dropdownMenuLayer || inputGroup || sensitiveInput || combobox || autocomplete || commandPalette) ? '' : variants.map((v,i) => `<template ${i?'v-else-if':'v-if'}="${directive(predicates[i])}">${semanticNode(v.tree)}</template>`).join('');
  const nativeButton = model.interactions?.nativeButton;
  const toggle = toggleBinding(model, library);
  const loweredToggle = toggle && toggleSource(toggle);
  const fallback = loweredSelect?.template ?? loweredDatePicker?.template ?? loweredDateRangePicker?.template ?? loweredToastLifecycle?.template ?? loweredResponsiveSidebar?.template ?? loweredCommandPalette?.template ?? loweredAutocomplete?.template ?? loweredCombobox?.template ?? loweredSensitiveInput?.template ?? loweredInputGroup?.template ?? loweredDropdownMenuLayer?.template ?? loweredPopoverLayer?.template ?? loweredDialogLayer?.template ?? loweredMenubarNavigation?.template ?? loweredTabsNavigation?.template ?? loweredRadioGroup?.template ?? loweredPagination?.template ?? loweredClipboardCopy?.template ?? loweredToggle?.template ?? loweredNativeInput?.template ?? (nativeButton
    ? `<button v-bind="$attrs" :type="($attrs.type as any) ?? 'button'" :disabled="props.disabled || props.loading"><svg v-if="props.loading" aria-hidden="true"></svg><slot /></button>`
    : node(implementation.componentRoot));
  const composedField = composition && !composition.ownsControl
    ? `<${composition.container}><label :for="String((props as any).childId ?? $attrs['child-id'] ?? 'field-control')">{{ (props as any).label }}</label><slot /></${composition.container}>`
    : null;
  const template = composedField ?? (semantic ? `${semantic}<template v-else>${fallback}</template>` : fallback);
  return `<!-- @generated by src/kumo/emitters/vue/index.mjs; do not edit -->\n<script lang="ts">\nexport const modelDigest = ${JSON.stringify(model.modelDigest)}\nexport const contentBindingDigest = ${JSON.stringify(contentBindingDigest)}\n</script>\n\n<script setup lang="ts">\n${loweredSelect?.options ?? loweredDatePicker?.options ?? loweredDateRangePicker?.options ?? loweredToastLifecycle?.options ?? loweredResponsiveSidebar?.options ?? loweredCommandPalette?.options ?? loweredAutocomplete?.options ?? loweredCombobox?.options ?? loweredSensitiveInput?.options ?? loweredInputGroup?.options ?? loweredDropdownMenuLayer?.options ?? loweredPopoverLayer?.options ?? loweredDialogLayer?.options ?? loweredMenubarNavigation?.options ?? loweredTabsNavigation?.options ?? loweredRadioGroup?.options ?? loweredToggle?.options ?? loweredNativeInput?.options ?? (nativeButton ? 'defineOptions({ inheritAttrs: false })\n' : '')}import { ${loweredSelect?.imports ?? loweredDatePicker?.imports ?? loweredDateRangePicker?.imports ?? loweredToastLifecycle?.imports ?? loweredResponsiveSidebar?.imports ?? loweredCommandPalette?.imports ?? loweredAutocomplete?.imports ?? loweredCombobox?.imports ?? loweredSensitiveInput?.imports ?? loweredInputGroup?.imports ?? loweredDropdownMenuLayer?.imports ?? loweredPopoverLayer?.imports ?? loweredDialogLayer?.imports ?? loweredMenubarNavigation?.imports ?? loweredTabsNavigation?.imports ?? loweredRadioGroup?.imports ?? loweredPagination?.imports ?? loweredClipboardCopy?.imports ?? loweredToggle?.imports ?? (composition?.ownsControl ? 'computed, useAttrs, useId, useSlots' : 'computed, useAttrs, useSlots')} } from 'vue'\ninterface ${model.public.symbol}Props {\n${props}\n  fixture?: unknown\n  semanticContent?: unknown\n}\nconst props = withDefaults(defineProps<${model.public.symbol}Props>(), ${JSON.stringify(defaults)})\n${loweredSelect?.setup ?? loweredDatePicker?.setup ?? loweredDateRangePicker?.setup ?? loweredToastLifecycle?.setup ?? loweredResponsiveSidebar?.setup ?? loweredCommandPalette?.setup ?? loweredAutocomplete?.setup ?? loweredCombobox?.setup ?? loweredSensitiveInput?.setup ?? loweredInputGroup?.setup ?? loweredDropdownMenuLayer?.setup ?? loweredPopoverLayer?.setup ?? loweredDialogLayer?.setup ?? loweredMenubarNavigation?.setup ?? loweredTabsNavigation?.setup ?? loweredRadioGroup?.setup ?? loweredPagination?.setup ?? loweredClipboardCopy?.setup ?? loweredToggle?.setup ?? loweredNativeInput?.setup ?? ''}const slots = useSlots()\nconst styles: Record<string,string> = {}\nconst normalizeSlotContent = (value: any): string => Array.isArray(value) ? value.map(normalizeSlotContent).join('') : value == null || typeof value === 'boolean' ? '' : typeof value === 'string' || typeof value === 'number' ? String(value) : normalizeSlotContent(value.children)
const renderContent = () => props.semanticContent ?? normalizeSlotContent(slots.default?.())\nconst fixture = computed(() => props.fixture)\nconst semanticValues = Object.assign({}, useAttrs(), props) as Record<string, unknown>\nconst semanticEqual = (left: unknown, right: unknown) => JSON.stringify(left) === JSON.stringify(right)\nconst fixtureText = (value: any): string => value && typeof value === 'object' ? String(typeof value.text === 'string' ? value.text : '') + (Array.isArray(value.children) ? value.children.map(fixtureText).join('') : '') : ''\n</script>\n\n<template>\n  ${template}\n</template>\n`;
}
export function generateVueLibrary(output = path.join(root, 'generated/libraries/vue')) {
  const library = loadLibrary();
  const {models} = library;
  for (const kind of [...NODE_KINDS, ...EXPRESSION_KINDS, ...OPERATION_KINDS]) if (!kind) throw new Error('invalid algebra kind');
  fs.rmSync(output, {recursive:true, force:true}); fs.mkdirSync(path.join(output,'components'), {recursive:true});
  const entries = [];
  const compoundPaths = [];
  for (const model of models) {
    const source = emitComponent(model, library); const file = `components/${model.component}.vue`;
    fs.writeFileSync(path.join(output,file), source);
    const graph = model.composition?.compoundExports;
    const partImports = new Map();
    for (const item of graph?.paths ?? []) {
      const partName = `${model.component}.${item.path.split('.').map(segment => segment.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()).join('.')}`;
      const partFile = `components/${partName}.vue`;
      const partDeclaration = `components/${partName}.d.ts`;
      const symbol = `${id(graph.canonicalRoot)}${item.path.split('.').map(pascal).join('')}`;
      const partSource = compoundPartSource(item.path);
      fs.writeFileSync(path.join(output,partFile), partSource);
      fs.writeFileSync(path.join(output,partDeclaration), `// @generated by src/kumo/emitters/vue/index.mjs; do not edit\nimport type { DefineComponent } from 'vue';\ndeclare const component: DefineComponent<Record<string, unknown>>;\nexport default component;\n`);
      partImports.set(item.path, symbol);
      compoundPaths.push({root:graph.canonicalRoot,path:item.path,binding:`${graph.canonicalRoot}.${item.path}`,symbol,file:partFile,types:partDeclaration,sha256:sha(partSource),vectorIds:item.vectorIds});
    }
    const declaration = `// @generated by src/kumo/emitters/vue/index.mjs; do not edit\nimport type { DefineComponent } from 'vue';\nexport interface ${model.public.symbol}Props { [key: string]: unknown }\ndeclare const component: DefineComponent<${model.public.symbol}Props>;\nexport default component;\nexport declare const modelDigest: ${JSON.stringify(model.modelDigest)};\n`;
    fs.writeFileSync(path.join(output,`components/${model.component}.d.ts`), declaration);
    entries.push({component:model.component,symbol:model.public.symbol,subpath:model.public.subpath,file,modelDigest:model.modelDigest,contentBindingDigest:model.contentBindings.capabilityDigest,semanticVariants:(model.draftImplementation.semanticVariants ?? []).map(({id,expectationDigest}) => ({id,expectationDigest})),unresolvedSemanticOperations:model.unresolvedSemanticOperations ?? [],sha256:sha(source),exports:model.public.exports,compoundExports:graph ? {canonicalRoot:graph.canonicalRoot,tree:graph.tree,paths:graph.paths.map(item => item.path)} : undefined,partImports});
  }
  const indexLines = [];
  const declarationLines = [];
  for (const entry of entries) {
    if (!entry.compoundExports) {
      indexLines.push(`export { default as ${id(entry.symbol)} } from './${entry.file}'`);
      declarationLines.push(`export { default as ${id(entry.symbol)} } from './${entry.file}'`);
      continue;
    }
    indexLines.push(`import Root${id(entry.symbol)} from './${entry.file}'`);
    declarationLines.push(`import Root${id(entry.symbol)} from './${entry.file}'`);
    for (const [partPath, symbol] of entry.partImports) {
      const part = compoundPaths.find(item => item.root === entry.compoundExports.canonicalRoot && item.path === partPath);
      indexLines.push(`import ${symbol} from './${part.file}'`);
      declarationLines.push(`import ${symbol} from './${part.file}'`);
    }
    const bindingGraph = {...entry.compoundExports, paths:entry.compoundExports.paths.map(path => ({path}))};
    const binding = compoundBindingSource(bindingGraph, entry.partImports).replace('RootComponent', `Root${id(entry.symbol)}`);
    indexLines.push(binding);
    declarationLines.push(binding);
  }
  fs.writeFileSync(path.join(output,'index.ts'),'// @generated by src/kumo/emitters/vue/index.mjs; do not edit\n'+indexLines.join('\n')+'\n');
  fs.writeFileSync(path.join(output,'index.d.ts'),'// @generated by src/kumo/emitters/vue/index.mjs; do not edit\n'+declarationLines.join('\n')+'\n');
  const exports = Object.fromEntries(entries.map(e => [`./components/${e.component}`,{vue:`./${e.file}`,types:`./components/${e.component}.d.ts`,canonicalSubpath:e.subpath}])) ;
  for (const part of compoundPaths) exports[`./${part.file.slice(0,-4)}`] = {vue:`./${part.file}`,types:`./${part.types}`,binding:part.binding};
  const components = entries.map(({partImports,compoundExports,...entry}) => ({...entry,...(compoundExports ? {compoundExports} : {})}));
  const manifest = {schemaVersion:'kumo.vue-library/v1',algebraVersion:'kumo.component-algebra/v1',candidate:true,count:entries.length,components,compoundPaths,exports:{'.':{vue:'./index.ts',types:'./index.d.ts'},...exports}};
  fs.writeFileSync(path.join(output,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
  return manifest;
}
if (process.argv[1] === fileURLToPath(import.meta.url)) process.stdout.write(canonicalJSON(generateVueLibrary())+'\n');
