import { Hono } from 'hono';
import { serve } from '@hono/node-server';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
const app=new Hono(),root=resolve(import.meta.dirname,'..'),frameworks=new Set(['react','vue','svelte','solid']);
const css=readFileSync(resolve(root,'public/styles.css'),'utf8');
const cases=[{label:'Extra small',size:'xs',placeholder:'Choose fruit'},{label:'Small',size:'sm',value:'Apple'},{label:'Base',size:'base',placeholder:'Choose fruit',description:'Choose the closest region.'},{label:'Large',size:'lg',value:'Cherry'},{label:'Loading',loading:true,placeholder:'Loading…'},{label:'Hidden label',hideLabel:true,placeholder:'Hidden label'},{label:'Disabled',disabled:true,placeholder:'Unavailable'},{label:'Error',placeholder:'Select an option',error:'Selection required'}];
function Select(p){const id=p.label.toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-listbox';return React.createElement('div',{className:'kumo-field'},React.createElement('label',{htmlFor:id+'-trigger',className:p.hideLabel?'sr-only':undefined},p.label),React.createElement('button',{type:'button',role:'combobox',id:id+'-trigger','aria-controls':id,'aria-expanded':'false','aria-haspopup':'listbox','aria-busy':p.loading||undefined,'aria-invalid':p.error?true:undefined,disabled:p.disabled||p.loading,className:`kumo-trigger ${p.size||'base'}`},React.createElement('span',null,p.value||p.placeholder),React.createElement('svg',{'aria-hidden':'true',width:16,height:16,viewBox:'0 0 16 16'},React.createElement('path',{fill:'currentColor',d:'m4 6 4 4 4-4z'}))),p.error?React.createElement('p',{className:'error'},p.error):p.description?React.createElement('p',{className:'description'},p.description):null)}
const canonical=renderToStaticMarkup(React.createElement('main',{className:'shell'},React.createElement('h1',{className:'title'},'Select'),React.createElement('section',{className:'matrix'},cases.map((p,i)=>React.createElement(Select,{...p,key:i})) )));
const reactPage=`<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Select React</title><style>${css}</style></head><body><div id="app">${canonical}</div><script type="module" src="/select/react/assets/react-select.js"></script></body></html>`;
app.get('/select/react',c=>c.html(reactPage));
for(const f of frameworks)app.get(`/select/${f}`,c=>c.html(readFileSync(resolve(root,`runtime/${f}/public-runtime/index.html`),'utf8')));
app.get('/select/:framework/assets/:file',c=>{const{framework,file}=c.req.param();if(!frameworks.has(framework)||!/^[\w.-]+$/.test(file))return c.notFound();const body=readFileSync(resolve(root,`runtime/${framework}/public-runtime/assets/${file}`));return c.body(body,200,{'Content-Type':file.endsWith('.css')?'text/css':'text/javascript'});});
app.get('/select/compare',c=>c.html(`<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Select runtime comparison</title><style>*{box-sizing:border-box}body{margin:0;padding:28px;background:#f3f4f6;color:#111827;font-family:Arial,sans-serif}header{max-width:1840px;margin:0 auto 20px}h1{margin:0 0 6px;font-size:28px}header p{margin:0;color:#6b7280}.compare{max-width:1840px;margin:auto;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.panel{overflow:hidden;border:1px solid #d1d5db;border-radius:12px;background:white;box-shadow:0 2px 8px #00000012}.panel h2{height:42px;margin:0;padding:12px 16px;border-bottom:1px solid #e5e7eb;background:#fafafa;font-size:14px;text-transform:capitalize}.panel iframe{display:block;width:100%;height:600px;border:0;background:white}@media(max-width:1000px){.compare{grid-template-columns:1fr}}</style></head><body><header><h1>Select runtime comparison</h1><p>Kumo 2.5.2 · React, Vue, Svelte, and Solid generated runtimes</p></header><main class="compare">${['react','vue','svelte','solid'].map(f=>`<section class="panel"><h2>${f}</h2><iframe title="${f} Select runtime" src="/select/${f}"></iframe></section>`).join('')}</main></body></html>`));
const buttonCases=[{label:'Primary',variant:'primary'},{label:'Secondary',variant:'secondary'},{label:'Outline',variant:'outline'},{label:'Danger',variant:'danger'},{label:'Ghost',variant:'ghost'},{label:'Extra small',size:'xs'},{label:'Small',size:'sm'},{label:'Large',size:'lg'},{label:'Disabled',disabled:true},{label:'Saving',loading:true},{label:'Add item',iconOnly:true},{label:'Submit',type:'submit'}];
function Button(p){return React.createElement('button',{type:p.type||'button',className:`kumo-button ${p.variant||'primary'} ${p.size||'base'}`,disabled:p.disabled||p.loading,'aria-disabled':p.disabled||undefined,'aria-busy':p.loading||undefined,'aria-label':p.iconOnly?p.label:undefined},p.loading?'Loading…':p.iconOnly?'+':p.label)}
const buttonMarkup=renderToStaticMarkup(React.createElement('main',{className:'button-shell'},React.createElement('h1',null,'Button'),React.createElement('section',{className:'button-matrix'},buttonCases.map((p,i)=>React.createElement(Button,{...p,key:i})) )));
const buttonCss=readFileSync(resolve(root,'public/button.css'),'utf8');
app.get('/button/react',c=>c.html(`<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><title>Button React</title><style>${buttonCss}</style></head><body><div id="app">${buttonMarkup}</div><script type="module" src="/button/react/assets/react-button.js"></script></body></html>`));
for(const f of frameworks)if(f!=='react')app.get(`/button/${f}`,c=>c.html(readFileSync(resolve(root,`runtime/button/${f}/public-runtime/index.html`),'utf8')));
app.get('/button/:framework/assets/:file',c=>{const{framework,file}=c.req.param();if(!frameworks.has(framework)||!/^[\w.-]+$/.test(file))return c.notFound();const body=readFileSync(resolve(root,`runtime/button/${framework}/public-runtime/assets/${file}`));return c.body(body,200,{'Content-Type':file.endsWith('.css')?'text/css':'text/javascript'});});
app.get('/button/compare',c=>c.html(`<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Button runtime comparison</title><style>*{box-sizing:border-box}body{margin:0;padding:28px;background:#f3f4f6;font-family:Arial}h1{margin:0 0 20px}.compare{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.panel{overflow:hidden;border:1px solid #d1d5db;border-radius:12px;background:white}.panel h2{margin:0;padding:12px 16px;border-bottom:1px solid #ddd;font-size:14px;text-transform:capitalize}.panel iframe{display:block;width:100%;height:500px;border:0}@media(max-width:1000px){.compare{grid-template-columns:1fr}}</style></head><body><h1>Button runtime comparison</h1><main class="compare">${[...frameworks].map(f=>`<section class="panel"><h2>${f}</h2><iframe title="${f} Button runtime" src="/button/${f}"></iframe></section>`).join('')}</main></body></html>`));
for(const f of frameworks)app.get(`/dialog/${f}`,c=>c.html(readFileSync(resolve(root,`runtime/dialog/${f}/public-runtime/index.html`),'utf8')));
app.get('/dialog/:framework/assets/:file',c=>{const{framework,file}=c.req.param();if(!frameworks.has(framework)||!/^[\w.-]+$/.test(file))return c.notFound();const body=readFileSync(resolve(root,`runtime/dialog/${framework}/public-runtime/assets/${file}`));return c.body(body,200,{'Content-Type':file.endsWith('.css')?'text/css':'text/javascript'});});
app.get('/dialog/compare',c=>c.html(`<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><title>Dialog runtime comparison</title><style>*{box-sizing:border-box}body{margin:0;padding:24px;background:#f3f4f6;font-family:Arial}h1{margin-top:0}.compare{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.panel{background:white;border:1px solid #ddd;border-radius:10px;overflow:hidden}.panel h2{margin:0;padding:10px 14px;font-size:14px;text-transform:capitalize}.panel iframe{display:block;width:100%;height:760px;border:0}@media(max-width:1000px){.compare{grid-template-columns:1fr}}</style></head><body><h1>Dialog runtime comparison</h1><main class="compare">${[...frameworks].map(f=>`<section class="panel"><h2>${f}</h2><iframe title="${f} Dialog runtime" src="/dialog/${f}"></iframe></section>`).join('')}</main></body></html>`));
serve({fetch:app.fetch,port:Number(process.env.PORT||4260)},({port})=>console.log(`review server http://localhost:${port}/select/compare`));
