import {IR_SCHEMA_VERSION, type Behavior, type ComponentIR, type ElementNode, type InteractionPolicy, type Node} from './schema.js';
const t=(value:string):Node=>({kind:'text',value});
const e=(tag:string,attrs:Record<string,string|number|boolean>={},children:Node[]=[]):ElementNode=>({kind:'element',tag,attrs,children});
const migrated:Record<string,{name:string;body:ElementNode}>={
 badge:{name:'Badge',body:e('span',{class:'badge'},[t('PRO')])},
 banner:{name:'Banner',body:e('div',{class:'banner',role:'status'},[e('span',{class:'badge'},[t('NEW')]),e('strong',{},[t('Edge data is current.')])])},
 surface:{name:'Surface',body:e('section',{class:'surface'},[e('h2',{},[t('Account surface')]),e('p',{},[t('Content on a bounded surface.')])])},
 'layer-card':{name:'LayerCard',body:e('article',{class:'layer-card'},[e('h2',{},[t('Production zone')]),e('p',{},[t('Layered account details.')])])},
 grid:{name:'Grid',body:e('div',{class:'grid'},['Analytics','Workers','DNS'].map(x=>e('div',{class:'grid-item'},[t(x)])))},
 'grid-item':{name:'GridItem',body:e('div',{class:'grid-item'},[e('strong',{},[t('Requests')]),e('p',{},[t('12,480 today')])])},
 loader:{name:'Loader',body:e('span',{class:'loader',role:'status','aria-label':'Loading'})},
 meter:{name:'Meter',body:e('div',{},[e('label',{for:'usage'},[t('Usage')]),e('meter',{id:'usage',min:0,max:100,value:68},[t('68%')])])},
 empty:{name:'Empty',body:e('section',{class:'empty'},[e('strong',{},[t('No events yet')]),e('p',{},[t('Events appear here when available.')])])},
 label:{name:'Label',body:e('p',{class:'label'},[t('ACCOUNT')])}, link:{name:'Link',body:e('a',{href:'#details'},[t('Read details →')])},
 text:{name:'Text',body:e('p',{class:'text'},[t('Presentational primitives compose without client-only markup.')])},
 'cloudflare-logo':{name:'CloudflareLogo',body:e('div',{class:'logo',role:'img','aria-label':'Cloudflare'},[t('☁ Cloudflare')])},
 code:{name:'Code',body:e('code',{},[t("cache.status === 'HIT'")])},
 table:{name:'Table',body:e('table',{},[e('caption',{},[t('Request summary')]),e('thead',{},[e('tr',{},[e('th',{scope:'col'},[t('Colo')]),e('th',{scope:'col'},[t('Requests')])])]),e('tbody',{},[['SJC','12,480'],['AMS','9,201']].map(r=>e('tr',{},r.map(x=>e('td',{},[t(x)])))))])}
};
const forms:Record<string,{name:string;body:ElementNode;behavior?:Behavior}>={
 field:{name:'Field',body:e('div',{class:'field'},[e('label',{for:'field-value'},[t('Project name')]),e('input',{class:'control',id:'field-value',value:'Kumo'}),e('small',{},[t('Visible to your team.')])])},
 input:{name:'Input',body:e('label',{class:'field',for:'email'},[e('span',{},[t('Email address')]),e('input',{class:'control',id:'email',type:'email',placeholder:'you@example.com'})])},
 'input-group':{name:'InputGroup',body:e('label',{class:'field',for:'domain'},[e('span',{},[t('Domain')]),e('span',{class:'group'},[e('span',{},[t('https://')]),e('input',{id:'domain',value:'example.com'})])])},
 'input-area':{name:'InputArea',body:e('label',{class:'field',for:'notes'},[e('span',{},[t('Notes')]),e('textarea',{class:'control',id:'notes'},[t('Compiler proof')])])},
 'sensitive-input':{name:'SensitiveInput',body:e('label',{class:'field',for:'secret'},[e('span',{},[t('API token')]),e('span',{class:'row'},[e('input',{class:'control',id:'secret',type:'password',value:'secret-123'}),e('button',{class:'action reveal',type:'button','aria-pressed':'false'},[t('Show')])])]),behavior:{kind:'sensitive-toggle',inputId:'secret',buttonClass:'reveal'}},
 'clipboard-text':{name:'ClipboardText',body:e('div',{class:'field'},[e('label',{for:'copy-value'},[t('Install command')]),e('span',{class:'row'},[e('input',{class:'control',id:'copy-value',readonly:true,value:'npm i kumo'}),e('button',{class:'action copy',type:'button'},[t('Copy')])]),e('p',{class:'status',role:'status'})]),behavior:{kind:'clipboard-copy',inputId:'copy-value',buttonClass:'copy',statusClass:'status',message:'Copied npm i kumo'}}
};
const interactivePolicy=(state:string[],events:string[],keyboard:string[],aria:string[]):InteractionPolicy=>({state,events,keyboard,aria,hydration:'ssr-identical'});
const native:Record<string,{name:string;body:ElementNode;behavior:Behavior;policy:InteractionPolicy}>={
 checkbox:{name:'Checkbox',body:e('section',{class:'native-matrix'},[['accept','Accept terms',false,false],['updates','Email updates',true,false],['disabled','Disabled',false,true],['required','Required',false,false]].map(([id,label,checked,disabled])=>e('label',{class:'native-control checkbox'},[e('input',{id:String(id),type:'checkbox',checked:Boolean(checked),disabled:Boolean(disabled),required:id==='required'}),e('span',{class:'indicator','aria-hidden':'true'}),e('span',{},[t(String(label))])]))),behavior:{kind:'native-check',inputIds:['accept','updates','disabled','required']},policy:interactivePolicy(['checked'],['change'],['Space'],['native checkbox','label'])},
 switch:{name:'Switch',body:e('section',{class:'native-matrix'},[['airplane','Airplane mode',false,false],['notifications','Notifications',true,false],['switch-disabled','Disabled',false,true],['compact','Compact',false,false]].map(([id,label,checked,disabled])=>e('label',{class:`native-control switch${id==='compact'?' compact':''}`},[e('input',{id:String(id),type:'checkbox',role:'switch',checked:Boolean(checked),disabled:Boolean(disabled)}),e('span',{class:'indicator','aria-hidden':'true'}),e('span',{},[t(String(label))])]))),behavior:{kind:'native-check',inputIds:['airplane','notifications','switch-disabled','compact']},policy:interactivePolicy(['checked'],['change'],['Space'],['switch','aria-checked'])}
};
const navigation:Record<string,{name:string;body:ElementNode;behavior?:Behavior;policy:InteractionPolicy}>={
 tabs:{name:'Tabs',body:e('section',{},[e('div',{class:'tabs',role:'tablist','aria-label':'Account'},['Overview','Activity','Settings'].map((x,i)=>e('button',{role:'tab','aria-selected':i===0,tabindex:i===0?0:-1},[t(x)]))),e('div',{class:'panel',role:'tabpanel'},[t('Overview content')])]),behavior:{kind:'roving',groupRole:'tablist',itemRole:'tab',labels:['Overview','Activity','Settings'],selection:'activation'},policy:interactivePolicy(['active tab'],['click'],['ArrowLeft','ArrowRight','Home','End','Enter','Space'],['tablist','tab','tabpanel','aria-selected'])},
 'menu-bar':{name:'MenuBar',body:e('div',{class:'menubar',role:'menubar','aria-label':'Application'},['File','Edit','View'].map((x,i)=>e('button',{role:'menuitem',tabindex:i===0?0:-1},[t(x)]))),behavior:{kind:'roving',groupRole:'menubar',itemRole:'menuitem',labels:['File','Edit','View'],selection:'focus'},policy:interactivePolicy(['focused item'],['focus','click'],['ArrowLeft','ArrowRight','Home','End'],['menubar','menuitem'])},
 sidebar:{name:'Sidebar',body:e('nav',{class:'sidebar','aria-label':'Workspace'},['Overview','Members','Settings'].map((x,i)=>e('a',{href:`#${x.toLowerCase()}`,...(i===0?{'aria-current':'page'}:{})},[t(x)]))),behavior:{kind:'current-link',current:'page',labels:['Overview','Members','Settings']},policy:interactivePolicy(['current page'],['click'],['Enter'],['nav','aria-current=page'])},
 breadcrumbs:{name:'Breadcrumbs',body:e('nav',{'aria-label':'Breadcrumb'},[e('ol',{class:'crumbs'},[e('li',{},[e('a',{href:'#home'},[t('Home')])]),e('li',{},[e('a',{href:'#docs'},[t('Docs')])]),e('li',{'aria-current':'page'},[t('Navigation')])])]),policy:interactivePolicy([],[],['native link'],['nav','ordered list','aria-current=page'])},
 'table-of-contents':{name:'TableOfContents',body:e('nav',{class:'toc','aria-label':'On this page'},['Overview','Keyboard','Accessibility'].map((x,i)=>e('a',{href:`#${x.toLowerCase()}`,...(i===0?{'aria-current':'location'}:{})},[t(x)]))),behavior:{kind:'current-link',current:'location',labels:['Overview','Keyboard','Accessibility']},policy:interactivePolicy(['current location'],['click'],['Enter'],['nav','aria-current=location'])}
};
const selection:Record<string,{name:string;body:ElementNode;behavior:Behavior;policy:InteractionPolicy}>={
 radio:{name:'Radio',body:e('fieldset',{},[e('legend',{},[t('Plan')]),...['Free','Pro'].map((x,i)=>e('label',{},[e('input',{type:'radio',name:'plan',value:x,checked:i===0}),t(` ${x}`)]))]),behavior:{kind:'selection',mode:'radio',options:['Free','Pro'],initial:'Free'},policy:interactivePolicy(['value'],['change'],['Arrow keys','Space'],['fieldset','radio'])},
 autocomplete:{name:'Autocomplete',body:e('section',{},[e('label',{for:'search'},[t('Fruit')]),e('input',{id:'search',role:'combobox','aria-autocomplete':'list','aria-controls':'fruit-list','aria-expanded':false,placeholder:'Search fruit'}),e('ul',{id:'fruit-list',role:'listbox'},['Apple','Banana','Cherry'].map(x=>e('li',{role:'option',tabindex:-1},[t(x)])))]),behavior:{kind:'selection',mode:'autocomplete',options:['Apple','Banana','Cherry'],initial:''},policy:interactivePolicy(['query','open','active option'],['input','click'],['ArrowDown','ArrowUp','Enter','Escape'],['combobox','listbox','option'])},
 combobox:{name:'Combobox',body:e('section',{},[e('button',{class:'combo',role:'combobox','aria-controls':'region-list','aria-expanded':false},[t('Choose region')]),e('ul',{id:'region-list',role:'listbox'},['North America','Europe'].map(x=>e('li',{role:'option',tabindex:-1},[t(x)])))]),behavior:{kind:'selection',mode:'combobox',options:['North America','Europe'],initial:''},policy:interactivePolicy(['open','value'],['click'],['ArrowDown','ArrowUp','Enter','Escape'],['combobox','listbox','option'])},
 'command-palette':{name:'CommandPalette',body:e('section',{},[e('button',{class:'command','aria-haspopup':'dialog'},[t('Open commands ⌘K')]),e('div',{class:'palette',role:'dialog','aria-modal':true,'aria-label':'Command palette'},[e('input',{'aria-label':'Filter commands'}),e('ul',{role:'listbox'},['Create project','Open settings'].map(x=>e('li',{role:'option',tabindex:-1},[t(x)])))])]),behavior:{kind:'selection',mode:'command',options:['Create project','Open settings'],initial:''},policy:interactivePolicy(['open','query'],['click','input'],['Control/Meta+K','Escape','ArrowDown','ArrowUp'],['dialog','listbox'])},
 'date-picker':{name:'DatePicker',body:e('label',{for:'date'},[t('Deploy date'),e('input',{id:'date',type:'date',value:'2026-06-19'})]),behavior:{kind:'selection',mode:'date',initial:'2026-06-19'},policy:interactivePolicy(['date'],['change'],['native date keyboard'],['label','date input'])},
 'date-range-picker':{name:'DateRangePicker',body:e('section',{},[e('label',{},[t('Start '),e('input',{class:'start',type:'date',value:'2026-06-19'})]),e('label',{},[t('End '),e('input',{class:'end',type:'date',value:'2026-06-26'})])]),behavior:{kind:'selection',mode:'date-range',initial:['2026-06-19','2026-06-26']},policy:interactivePolicy(['start','end'],['change'],['native date keyboard'],['labels','date inputs'])},
 'dropdown-menu':{name:'DropdownMenu',body:e('section',{},[e('button',{class:'menu-button','aria-haspopup':'menu','aria-expanded':false},[t('Actions')]),e('div',{class:'menu',role:'menu'},['Edit','Duplicate','Delete'].map(x=>e('button',{role:'menuitem',tabindex:-1},[t(x)])))]),behavior:{kind:'selection',mode:'menu',options:['Edit','Duplicate','Delete'],initial:''},policy:interactivePolicy(['open','active item'],['click'],['ArrowDown','ArrowUp','Enter','Escape'],['menu','menuitem'])},
 toasty:{name:'Toasty',body:e('section',{},[e('button',{class:'toast-button'},[t('Save changes')]),e('output',{class:'toast',role:'status','aria-live':'polite'},[t('Ready to save')])]),behavior:{kind:'selection',mode:'toast',initial:'Ready to save'},policy:interactivePolicy(['message'],['click'],['Enter','Space'],['status','aria-live=polite'])},
 pagination:{name:'Pagination',body:e('nav',{class:'pagination','aria-label':'Pagination'},[e('button',{'aria-label':'Previous page'},[t('‹')]),...['1','2','3'].map((x,i)=>e('button',{class:'page',...(i===0?{'aria-current':'page'}:{})},[t(x)])),e('button',{'aria-label':'Next page'},[t('›')])]),behavior:{kind:'selection',mode:'pagination',initial:1},policy:interactivePolicy(['page'],['click'],['Enter','Space'],['nav','aria-current=page'])}
};
const rich:Record<string,{name:string;body:ElementNode;behavior:Behavior;policy:InteractionPolicy}>={
 select:{name:'Select',body:e('section',{class:'matrix'},[e('button',{role:'combobox','aria-expanded':false,'aria-controls':'select-options'},[t('Choose fruit')]),e('ul',{id:'select-options',role:'listbox'},['Apple','Banana','Cherry'].map(x=>e('li',{role:'option'},[t(x)])))]),behavior:{kind:'select',options:['Apple','Banana','Cherry'],sizes:['xs','sm','base','lg'],variants:['default','error']},policy:interactivePolicy(['open','active option','object value','loading','disabled'],['click','change','focus'],['ArrowDown','ArrowUp','Home','End','Enter','Space','Escape'],['combobox','listbox','option','aria-expanded','aria-selected'])},
 button:{name:'Button',body:e('section',{class:'button-matrix'},[e('button',{type:'button',class:'kumo-button primary base'},[t('Primary')])]),behavior:{kind:'button',sizes:['xs','sm','base','lg'],variants:['primary','secondary','outline','danger','ghost']},policy:interactivePolicy(['loading','disabled','activation count'],['click','submit'],['Enter','Space'],['button','aria-busy','aria-disabled','aria-label'])},
 dialog:{name:'Dialog',body:e('section',{class:'dialog-matrix'},[e('dialog',{open:true,'aria-labelledby':'dialog-title'},[e('h2',{id:'dialog-title'},[t('Dialog')]),e('button',{},[t('Close')])])]),behavior:{kind:'dialog',sizes:['sm','md','lg','full']},policy:interactivePolicy(['open','modal'],['click','cancel','close'],['Escape','Tab'],['dialog','aria-modal','aria-labelledby','aria-describedby'])},
 popover:{name:'Popover',body:e('section',{class:'popover-matrix'},[e('button',{'aria-haspopup':'dialog','aria-expanded':true},[t('Toggle')]),e('div',{role:'dialog'},[t('Popover content')])]),behavior:{kind:'popover',sides:['top','right','bottom','left'],aligns:['start','center','end']},policy:interactivePolicy(['open','side','align','offset'],['click','focusout'],['Escape','Tab'],['aria-haspopup','aria-expanded','aria-controls','dialog'])}
};
const ids=['select','button','dialog','popover','checkbox','switch','field','input','input-group','input-area','sensitive-input','clipboard-text','tabs','menu-bar','sidebar','breadcrumbs','table-of-contents','badge','banner','surface','layer-card','grid','grid-item','loader','meter','empty','label','link','text','cloudflare-logo','code','table','radio','autocomplete','combobox','command-palette','date-picker','date-range-picker','dropdown-menu','toasty','pagination'];
const title=(id:string)=>id.split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join('');
export const catalog:ComponentIR[]=ids.map(id=>{const richItem=rich[id],x=migrated[id],form=forms[id],control=native[id],nav=navigation[id],choice=selection[id],item=richItem??x??form??control??nav??choice;const family=richItem?'rich':x?'data-presentational':form?'form':control?'native-control':nav?'navigation':choice?'selection-command-date':'legacy';const shell=choice?'family':control?'native-shell':nav?'nav-shell':x?'data-shell':'form-shell';const content=x?e('div',{class:'demo',id:'details'},[item!.body]):form?e('section',{class:'form-grid'},[e('article',{class:'form-card','data-member':id},[item!.body])]):item?.body;const behavior=richItem?.behavior??form?.behavior??control?.behavior??nav?.behavior??choice?.behavior;const policy=richItem?.policy??control?.policy??nav?.policy??choice?.policy;return {schemaVersion:IR_SCHEMA_VERSION,id,name:item?.name??title(id),family,root:item?e('main',{class:shell},[e('h1',{},[t(item.name)]),content!]):null,...(behavior?{behavior}:{}),...(policy?{policy}:{}),source:{kind:'normalized-ir',revision:'4'},migration:{vue:item?'candidate':'pending'}}});
