import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const candidate = path.resolve(here, '..');
const root = path.resolve(candidate, '../..');
const files=['src/index.ts','src/views/native.ts','src/views/react/index.ts','src/views/vue/index.ts','src/views/svelte/Button.svelte','src/views/svelte/Field.svelte','src/views/svelte/Tabs.svelte','src/views/solid/components.tsx'];
const lines=f=>fs.readFileSync(path.join(candidate,f),'utf8').split('\n').filter(x=>x.trim()).length;
const entries=files.map(file=>({file,kind:file==='src/index.ts'||file==='src/views/native.ts'?'shared':'native',loc:lines(file),boundary:file.includes('/views/')&&!file.endsWith('native.ts')?'framework render/reactivity/events':'immutable behavior/ARIA contract'}));
const totals=Object.groupBy(entries,x=>x.kind);
fs.writeFileSync(path.join(root,'proof/bakeoff/shared-core/loc-boundary-ledger.json'),JSON.stringify({entries,totals:{shared:totals.shared.reduce((n,x)=>n+x.loc,0),native:totals.native.reduce((n,x)=>n+x.loc,0)},escapeHatches:{button:[],field:[],tabs:[]},nativeBoundary:['framework element creation/templates','framework reactive state','native event binding'],excludedBoundary:['focus management','portals (not exercised by pilot components)']},null,2)+'\n');
