use serde_json::{json, Value};
use std::{fs, path::PathBuf, process::Command, time::{SystemTime, UNIX_EPOCH}};
fn temp(name:&str)->PathBuf { let p=std::env::temp_dir().join(format!("kumo-rust-{name}-{}-{}",std::process::id(),SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos())); fs::create_dir_all(&p).unwrap(); p }
fn invoke(request:&PathBuf)->(i32,Value) { let out=Command::new(env!("CARGO_BIN_EXE_kumo-rust-planner")).arg(request).output().unwrap(); assert!(out.stderr.is_empty()); (out.status.code().unwrap(),serde_json::from_slice(&out.stdout).unwrap()) }
fn component(id:&str)->Value {json!({"schemaVersion":"kumo.ir/v1","id":id,"root":{}})}
fn request(root:&PathBuf,out:&PathBuf,components:Vec<Value>)->Value { json!({"schemaVersion":"kumo.compiler.request/v1","inputRoot":root,"outputRoot":out,"catalog":{"schemaVersion":"kumo.ir/v1","components":components},"frameworks":["react"]}) }
#[test] fn malformed_request(){let d=temp("malformed");let p=d.join("r");fs::write(&p,"{").unwrap();let (c,r)=invoke(&p);assert_eq!(c,2);assert_eq!(r["diagnostics"][0]["code"],"malformed-request");}
#[test] fn path_traversal(){let d=temp("traversal");let p=d.join("r");let out=d.join("out");fs::write(&p,serde_json::to_vec(&request(&d,&out,vec![component("../bad")])).unwrap()).unwrap();let (c,r)=invoke(&p);assert_eq!(c,3);assert_eq!(r["diagnostics"][0]["code"],"unsafe-component-id");assert!(!out.exists());}
#[test] fn duplicate_ids_no_partial_writes(){let d=temp("duplicate");let p=d.join("r");let out=d.join("out");fs::create_dir(&out).unwrap();fs::write(out.join("existing"),"keep").unwrap();fs::write(&p,serde_json::to_vec(&request(&d,&out,vec![component("a"),component("a")])).unwrap()).unwrap();let (c,r)=invoke(&p);assert_eq!(c,3);assert_eq!(r["diagnostics"][0]["code"],"duplicate-component");assert_eq!(fs::read_to_string(out.join("existing")).unwrap(),"keep");}
#[test] fn deterministic(){let d=temp("determinism");let p1=d.join("r1");let p2=d.join("r2");let o1=d.join("o1");let o2=d.join("o2");fs::write(&p1,serde_json::to_vec(&request(&d,&o1,vec![component("b"),component("a")])).unwrap()).unwrap();fs::write(&p2,serde_json::to_vec(&request(&d,&o2,vec![component("b"),component("a")])).unwrap()).unwrap();let (_,a)=invoke(&p1);let (_,b)=invoke(&p2);assert_eq!(a["plan"],b["plan"]);assert_eq!(a["outputs"],b["outputs"]);}
