#!/usr/bin/env node
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {mkdir,readFile,rm,stat,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import os from 'node:os';import path from 'node:path';import process from 'node:process';
import {digest,validateShootout,FIXTURE_GATES} from '../../../shootout/validate.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),sha=x=>createHash('sha256').update(x).digest('hex'),canonical=x=>Array.isArray(x)?x.map(canonical):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,canonical(x[k])])):x,stable=x=>JSON.stringify(canonical(x));
const dest=path.resolve(process.argv[2]??path.join(root,'benchmarks/shootout/languages/latest.json'));
const workloadPath=path.join(root,'shootout/workloads.json'),workloadBytes=await readFile(workloadPath),workloads=JSON.parse(workloadBytes),catalogSource=JSON.parse(await readFile(path.join(root,'protocol/fixtures/current-catalog.fixture.json'))),baseline=JSON.parse(await readFile(path.join(root,'proof/shootout/baseline/baseline.json')));
const ids=workloads.fixtures.map(x=>x.fixture);if(stable(ids)!==stable(['button','select']))throw Error('Axis A requires exact Button + Select workload');const catalog={schemaVersion:'kumo.ir/v1',components:catalogSource.catalog.components.filter(x=>ids.includes(x.id))};if(catalog.components.length!==2)throw Error('canonical catalog binding incomplete');
const run=(cmd,args,cwd)=>spawnSync(cmd,args,{cwd,encoding:'utf8'}),mustRun=(label,cmd,args,cwd)=>{const p=run(cmd,args,cwd);if(p.status!==0)throw Error(`${label} failed (exit ${p.status}, cwd ${cwd})\nstdout:\n${p.stdout??''}\nstderr:\n${p.stderr??''}\nerror: ${p.error?.message??'none'}`);return p.stdout.trim()},pct=(xs,p)=>[...xs].sort((a,b)=>a-b)[Math.ceil(xs.length*p)-1],variance=xs=>{const m=xs.reduce((a,b)=>a+b,0)/xs.length;return xs.reduce((a,b)=>a+(b-m)**2,0)/xs.length};
const sourceRevision=process.env.SOURCE_REVISION||mustRun('resolve source revision','git',['rev-parse','HEAD'],root),protocolRevision=mustRun('resolve protocol revision','git',['rev-parse',`${sourceRevision}^{commit}`],root);mustRun('verify source revision is available','git',['merge-base','--is-ancestor',sourceRevision,'HEAD'],root);
// The receipt intentionally excludes itself from this source set. That gives the
// committed receipt a stable, post-commit-verifiable digest without claiming that
// a pre-commit revision is the revision which actually produced the evidence.
const relevantPaths=['scripts/shootout/languages/run.mjs','benchmarks/compilers/typescript-adapter.mjs','compilers/go','compilers/rust','compilers/zig','protocol/fixtures/current-catalog.fixture.json','shootout/workloads.json','proof/shootout/baseline/baseline.json','shootout/validate.mjs'];
const sourceTreeDigest=sha(Buffer.from(mustRun('digest relevant source tree','git',['ls-tree','-r',sourceRevision,'--',...relevantPaths],root)));
const buildRoot=await (async()=>{const p=path.join(os.tmpdir(),`kumo-language-build-${process.pid}`);await rm(p,{recursive:true,force:true});await mkdir(p,{recursive:true});return p})();
const binaries={go:path.join(buildRoot,'kumo-go'),rust:path.join(buildRoot,'kumo-rust-planner'),zig:path.join(buildRoot,'kumo-zig')};
const candidates={typescript:{command:process.execPath,args:[path.join(root,'benchmarks/compilers/typescript-adapter.mjs')],binary:process.execPath,version:[process.execPath,'--version'],source:'benchmarks/compilers/typescript-adapter.mjs'},go:{command:binaries.go,args:[],binary:binaries.go,version:['go','version'],source:'compilers/go'},rust:{command:binaries.rust,args:[],binary:binaries.rust,version:['rustc','--version'],source:'compilers/rust'},zig:{command:binaries.zig,args:[],binary:binaries.zig,version:['zig','version'],source:'compilers/zig'}};
const temp=path.join(os.tmpdir(),`kumo-language-${process.pid}`),portableRoot='$REPOSITORY',portableOutput='$OUTPUT';await rm(temp,{recursive:true,force:true});await mkdir(temp,{recursive:true});
const semanticRequest={schemaVersion:'kumo.compiler.request/v1',inputRoot:portableRoot,outputRoot:portableOutput,catalog,frameworks:['react']},semanticDigest=sha(Buffer.from(stable(semanticRequest))),workloadDigest=sha(workloadBytes),runSeed=process.env.KUMO_SHOOTOUT_RUN_ID||stable({sourceRevision,protocolRevision,sourceTreeDigest,workloadDigest,semanticDigest,baseline:digest(baseline)}),runId=`sha256:${/^[a-f0-9]{64}$/.test(runSeed.replace(/^sha256:/,''))?runSeed.replace(/^sha256:/,''):sha(Buffer.from(runSeed))}`;
const results=[];try{
  mustRun('build Go compiler','go',['build','-trimpath','-o',binaries.go,'./cmd/kumo-go'],path.join(root,'compilers/go'));
  mustRun('build Rust compiler','cargo',['build','--locked','--release','--target-dir',path.join(buildRoot,'rust-target'),'--manifest-path',path.join(root,'compilers/rust/Cargo.toml')],root);await writeFile(binaries.rust,await readFile(path.join(buildRoot,'rust-target/release/kumo-rust-planner')));await (await import('node:fs/promises')).chmod(binaries.rust,0o755);
  mustRun('build Zig compiler','zig',['build-exe',path.join(root,'compilers/zig/main.zig'),'-O','ReleaseSafe','-femit-bin='+binaries.zig],root);
  for(const [language,c] of Object.entries(candidates)){let reference;const samples=[];const cwdModes=[root,temp];for(let i=0;i<12;i++){const output=path.join(temp,language,String(i),'out'),request=path.join(temp,language,String(i),'request.json');await mkdir(path.dirname(request),{recursive:true});await writeFile(request,JSON.stringify({...semanticRequest,inputRoot:root,outputRoot:output}));const start=process.hrtime.bigint(),p=run(c.command,[...c.args,request],cwdModes[i%2]),wallMs=Number(process.hrtime.bigint()-start)/1e6;if(p.status!==0)throw Error(`${language} invocation failed (exit ${p.status}, cwd ${cwdModes[i%2]})\nstdout:\n${p.stdout??''}\nstderr:\n${p.stderr??''}\nerror: ${p.error?.message??'none'}`);const receipt=JSON.parse(p.stdout),normalized={schemaVersion:'kumo.language-artifact/v1',status:receipt.status,diagnostics:receipt.diagnostics,plan:receipt.plan,outputs:receipt.outputs.map(x=>({sha256:x.sha256,bytes:x.bytes}))};if(reference&&stable(normalized)!==stable(reference))throw Error(`${language}: nondeterministic artifact across clean output/CWD`);reference=normalized;if(i>=2)samples.push({wallMs,cpuUserMs:null,cpuSystemMs:null,peakRssBytes:null});}
  const sourceFiles=mustRun(`list ${language} sources`,'git',['ls-files',c.source],root).split('\n').filter(Boolean),loc=sourceFiles.reduce((n,f)=>n+Number(mustRun(`count lines in ${f}`,'wc',['-l',path.join(root,f)],root).split(/\s+/)[0]||0),0),binaryBytes=(await stat(c.binary)).size;results.push({language,toolchain:mustRun(`${language} toolchain`,c.version[0],c.version.slice(1),root),request:{schemaVersion:'kumo.compiler.request/v1',semanticDigest,workloadDigest,portableInputRoot:portableRoot,portableOutputRoot:portableOutput},artifact:reference,artifactDigest:sha(Buffer.from(stable(reference))),rawOutput:{files:reference.outputs.length,bytes:reference.outputs.reduce((n,x)=>n+x.bytes,0),digest:sha(Buffer.from(stable(reference.outputs)))},correctness:'passed',performance:{status:'blocked-resource-metrics-unavailable',warmups:2,measured:10,serialized:true,samples,approvedVariance:{wallMs:variance(samples.map(x=>x.wallMs))},summary:{medianWallMs:pct(samples.map(x=>x.wallMs),.5),p95WallMs:pct(samples.map(x=>x.wallMs),.95)}},coldSetupBuild:{status:'built-once-before-measurement'},incremental:{status:'not-applicable-fresh-output-roots'},diagnostics:reference.diagnostics,maintenance:{sourceFiles:sourceFiles.length,loc},distribution:{binaryBytes}})}
  const artifactSchema=results.map(x=>Object.keys(x.artifact).sort().join(','));if(new Set(artifactSchema).size!==1)throw Error('artifact schema mismatch');const planDigest=sha(Buffer.from(stable(results[0].artifact.plan)));for(const r of results)if(sha(Buffer.from(stable(r.artifact.plan)))!==planDigest)throw Error('semantic correctness incomplete');
  const env={platform:os.platform(),arch:os.arch(),release:os.release(),cpu:os.cpus()[0]?.model??'unknown',node:process.version},baselineDigest=digest(baseline),shootoutRecords=results.flatMap(r=>ids.map(component=>({schemaVersion:'shootout/v1',axis:'language',language:r.language,candidateId:`${r.language}-planner`,framework:'react',component,candidateRevision:sourceRevision,frameworkRevision:'react',componentRevision:baseline.ir.catalogSha256,runId:`sha256:${sha(Buffer.from(`${runId}:${r.language}:${component}`))}`,evidenceDigest:r.artifactDigest,environmentManifestDigest:baseline.environmentManifestDigest,baseline:{digest:baselineDigest},gates:Object.fromEntries(FIXTURE_GATES[component].map(g=>[g,'blocked']))})));for(const record of shootoutRecords){const v=validateShootout(record,{baseline});if(!v.valid)throw Error(v.errors.join('; '))}
  const receipt={schemaVersion:'kumo.language-shootout/v2',axis:'language',sourceRevision,protocolRevision,sourceTree:{paths:relevantPaths,digest:sourceTreeDigest},runId,provenance:{workloads:{schemaVersion:workloads.schemaVersion,path:'shootout/workloads.json',sha256:workloadDigest},baseline:{path:'proof/shootout/baseline/baseline.json',digest:baselineDigest},environmentManifestDigest:baseline.environmentManifestDigest},methodology:{correctnessBeforePerformance:true,warmups:2,measured:10,serialized:true,retries:0,cwdModes:['repository-root','external-temporary-directory'],outputRoots:'fresh and removed per invocation',resourceMeasurement:'blocked: portable Node spawn does not expose reliable macOS CPU/peak RSS; do not rank',variancePolicy:'wall variance is measured metadata only',claims:'Axis A planner protocol only; all shootout product gates blocked; no architecture/browser claim; no winner'},environment:env,environmentDigest:sha(Buffer.from(stable(env))),semanticDigest,artifactSchema:'kumo.language-artifact/v1',shootoutRecords,results};await writeFile(dest,JSON.stringify(receipt,null,2)+'\n');console.log(dest);
}finally{await rm(temp,{recursive:true,force:true});await rm(buildRoot,{recursive:true,force:true})}
