#!/usr/bin/env node
import {spawnSync} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
import {mkdir,readFile,rm,stat,writeFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import process from 'node:process';
import {digest,validateShootout,FIXTURE_GATES} from '../../../shootout/validate.mjs';
const root=path.resolve(new URL('../../..',import.meta.url).pathname),sha=x=>createHash('sha256').update(x).digest('hex'),stable=x=>JSON.stringify(x,Object.keys(x).sort());
const dest=path.resolve(process.argv[2]??path.join(root,'benchmarks/shootout/languages/latest.json'));
const workloadPath=path.join(root,'shootout/workloads.json'),workloadBytes=await readFile(workloadPath),workloads=JSON.parse(workloadBytes),catalogSource=JSON.parse(await readFile(path.join(root,'protocol/fixtures/current-catalog.fixture.json'))),baseline=JSON.parse(await readFile(path.join(root,'proof/shootout/baseline/baseline.json')));
const ids=workloads.fixtures.map(x=>x.fixture);if(stable(ids)!==stable(['button','select']))throw Error('Axis A requires exact Button + Select workload');const catalog={schemaVersion:'kumo.ir/v1',components:catalogSource.catalog.components.filter(x=>ids.includes(x.id))};if(catalog.components.length!==2)throw Error('canonical catalog binding incomplete');
const candidates={typescript:{command:process.execPath,args:[path.join(root,'benchmarks/compilers/typescript-adapter.mjs')],binary:process.execPath,version:[process.execPath,'--version'],source:'benchmarks/compilers/typescript-adapter.mjs'},go:{command:process.execPath,args:[path.join(root,'compilers/go/adapter.mjs')],binary:path.join(root,'compilers/go/bin/kumo-go'),version:['go','version'],source:'compilers/go'},rust:{command:process.execPath,args:[path.join(root,'compilers/rust/kumo-rust-planner.mjs')],binary:path.join(root,'compilers/rust/target/release/kumo-rust-planner'),version:['rustc','--version'],source:'compilers/rust'},zig:{command:process.execPath,args:[path.join(root,'benchmarks/compilers/zig-adapter.mjs')],binary:path.join(root,'compilers/zig/zig-out/bin/kumo-zig'),version:['zig','version'],source:'compilers/zig'}};
const run=(cmd,args,cwd)=>spawnSync(cmd,args,{cwd,encoding:'utf8'}),pct=(xs,p)=>[...xs].sort((a,b)=>a-b)[Math.ceil(xs.length*p)-1],variance=xs=>{const m=xs.reduce((a,b)=>a+b,0)/xs.length;return xs.reduce((a,b)=>a+(b-m)**2,0)/xs.length};
const temp=path.join(os.tmpdir(),`kumo-language-${process.pid}`),portableRoot='$REPOSITORY',portableOutput='$OUTPUT';await rm(temp,{recursive:true,force:true});await mkdir(temp,{recursive:true});
const semanticRequest={schemaVersion:'kumo.compiler.request/v1',inputRoot:portableRoot,outputRoot:portableOutput,catalog,frameworks:['react']},semanticDigest=sha(Buffer.from(JSON.stringify(semanticRequest))),workloadDigest=sha(workloadBytes),revision=run('git',['rev-parse','HEAD'],root).stdout.trim();
const results=[];try{for(const [language,c] of Object.entries(candidates)){let reference;const samples=[];const cwdModes=[root,temp];for(let i=0;i<12;i++){const output=path.join(temp,language,String(i),'out'),request=path.join(temp,language,String(i),'request.json');await mkdir(path.dirname(request),{recursive:true});const requestObject={...semanticRequest,inputRoot:root,outputRoot:output},requestBytes=Buffer.from(JSON.stringify(requestObject));await writeFile(request,requestBytes);const start=process.hrtime.bigint(),p=run(c.command,[...c.args,request],cwdModes[i%2]),wallMs=Number(process.hrtime.bigint()-start)/1e6;if(p.status!==0)throw Error(`${language}: ${p.stderr||p.stdout}`);const receipt=JSON.parse(p.stdout),normalized={schemaVersion:'kumo.language-artifact/v1',status:receipt.status,diagnostics:receipt.diagnostics,plan:receipt.plan,outputs:receipt.outputs.map(x=>({sha256:x.sha256,bytes:x.bytes}))};if(reference&&stable(normalized)!==stable(reference))throw Error(`${language}: nondeterministic artifact across clean output/CWD`);reference=normalized;if(i>=2)samples.push({wallMs,cpuUserMs:null,cpuSystemMs:null,peakRssBytes:null});}
const sourceFiles=run('git',['ls-files',c.source],root).stdout.trim().split('\n').filter(Boolean),loc=sourceFiles.reduce((n,f)=>n+Number(run('wc',['-l',path.join(root,f)],root).stdout.trim().split(/\s+/)[0]||0),0),binaryBytes=(await stat(c.binary)).size;results.push({language,toolchain:run(c.version[0],c.version.slice(1),root).stdout.trim(),request:{schemaVersion:'kumo.compiler.request/v1',semanticDigest,workloadDigest,portableInputRoot:portableRoot,portableOutputRoot:portableOutput},artifact:reference,artifactDigest:sha(Buffer.from(JSON.stringify(reference))),rawOutput:{files:reference.outputs.length,bytes:reference.outputs.reduce((n,x)=>n+x.bytes,0),digest:sha(Buffer.from(JSON.stringify(reference.outputs)))},correctness:'passed',performance:{status:'blocked-resource-metrics-unavailable',warmups:2,measured:10,serialized:true,samples,approvedVariance:{wallMs:variance(samples.map(x=>x.wallMs))},summary:{medianWallMs:pct(samples.map(x=>x.wallMs),.5),p95WallMs:pct(samples.map(x=>x.wallMs),.95)}},coldSetupBuild:{status:'not-measured-prebuilt-input'},incremental:{status:'not-applicable-fresh-output-roots'},diagnostics:reference.diagnostics,maintenance:{sourceFiles:sourceFiles.length,loc},distribution:{binaryBytes}})}
const artifactSchema=results.map(x=>Object.keys(x.artifact).sort().join(','));if(new Set(artifactSchema).size!==1)throw Error('artifact schema mismatch');const planDigest=sha(Buffer.from(JSON.stringify(results[0].artifact.plan)));for(const r of results)if(sha(Buffer.from(JSON.stringify(r.artifact.plan)))!==planDigest)throw Error('semantic correctness incomplete');
const env={platform:os.platform(),arch:os.arch(),release:os.release(),cpu:os.cpus()[0]?.model??'unknown',node:process.version},baselineDigest=digest(baseline),shootoutRecords=results.flatMap(r=>ids.map(component=>({schemaVersion:'shootout/v1',axis:'language',language:r.language,candidateId:`${r.language}-planner`,framework:'react',component,candidateRevision:revision,frameworkRevision:'react',componentRevision:baseline.ir.catalogSha256,runId:randomUUID(),evidenceDigest:r.artifactDigest,environmentManifestDigest:baseline.environmentManifestDigest,baseline:{digest:baselineDigest},gates:Object.fromEntries(FIXTURE_GATES[component].map(g=>[g,'blocked']))})));for(const record of shootoutRecords){const v=validateShootout(record,{baseline});if(!v.valid)throw Error(v.errors.join('; '))}
const receipt={schemaVersion:'kumo.language-shootout/v2',axis:'language',revision,runId:randomUUID(),provenance:{workloads:{schemaVersion:workloads.schemaVersion,path:'shootout/workloads.json',sha256:workloadDigest},baseline:{path:'proof/shootout/baseline/baseline.json',digest:baselineDigest},environmentManifestDigest:baseline.environmentManifestDigest},methodology:{correctnessBeforePerformance:true,warmups:2,measured:10,serialized:true,retries:0,cwdModes:['repository-root','external-temporary-directory'],outputRoots:'fresh and removed per invocation',resourceMeasurement:'blocked: portable Node spawn does not expose reliable macOS CPU/peak RSS; do not rank',variancePolicy:'wall variance is measured metadata only',claims:'Axis A planner protocol only; no architecture/browser claim; no winner while shootout gates are blocked'},environment:env,environmentDigest:sha(Buffer.from(JSON.stringify(env))),semanticDigest,artifactSchema:'kumo.language-artifact/v1',shootoutRecords,results};await writeFile(dest,JSON.stringify(receipt,null,2)+'\n');console.log(dest);}finally{await rm(temp,{recursive:true,force:true})}
