#!/usr/bin/env node
import {spawnSync} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
import {mkdir,readFile,rm,stat,writeFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import process from 'node:process';
const root=path.resolve(new URL('../../..',import.meta.url).pathname), sha=x=>createHash('sha256').update(x).digest('hex'), canonical=x=>JSON.stringify(x,Object.keys(x).sort());
const dest=path.resolve(process.argv[2]??path.join(root,'benchmarks/shootout/languages/latest.json')), fixturePath=path.join(root,'benchmarks/shootout/languages/fixtures.json');
const projection=JSON.parse(await readFile(fixturePath,'utf8')), fixtureBytes=Buffer.from(JSON.stringify(projection.catalog)), fixtureDigest=sha(fixtureBytes), revision=spawnSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).stdout.trim(), initialClean=spawnSync('git',['status','--porcelain'],{cwd:root,encoding:'utf8'}).stdout.trim()==='';
const candidates={typescript:{command:process.execPath,args:[path.join(root,'benchmarks/compilers/typescript-adapter.mjs')],binary:process.execPath,version:[process.execPath,'--version']},go:{command:process.execPath,args:[path.join(root,'compilers/go/adapter.mjs')],binary:path.join(root,'compilers/go/bin/kumo-go'),version:['go','version']},rust:{command:process.execPath,args:[path.join(root,'compilers/rust/kumo-rust-planner.mjs')],binary:path.join(root,'compilers/rust/target/release/kumo-rust-planner'),version:['rustc','--version']},zig:{command:process.execPath,args:[path.join(root,'benchmarks/compilers/zig-adapter.mjs')],binary:path.join(root,'compilers/zig/zig-out/bin/kumo-zig'),version:['zig','version']}};
function run(cmd,args,cwd=root){return spawnSync(cmd,args,{cwd,encoding:'utf8'});} function pct(xs,p){return [...xs].sort((a,b)=>a-b)[Math.ceil(xs.length*p)-1]}
await mkdir(path.dirname(dest),{recursive:true});const temp=path.join(os.tmpdir(),`kumo-language-${process.pid}`);await rm(temp,{recursive:true,force:true});await mkdir(temp,{recursive:true});
const common={schemaVersion:'kumo.compiler.request/v1',inputRoot:root,outputRoot:'$OUTPUT',catalog:projection.catalog,frameworks:['react']};const semanticDigest=sha(Buffer.from(JSON.stringify({...common,outputRoot:'$OUTPUT'})));
const results=[];try{for(const [language,c] of Object.entries(candidates)){const samples=[];let normalized,outputDigest;for(let i=0;i<12;i++){const output=path.join(temp,language,String(i),'out'),request=path.join(temp,language,String(i),'request.json');await mkdir(path.dirname(request),{recursive:true});const bytes=Buffer.from(JSON.stringify({...common,outputRoot:output}));await writeFile(request,bytes);const start=process.hrtime.bigint(),p=run(c.command,[...c.args,request]),wallMs=Number(process.hrtime.bigint()-start)/1e6;if(p.status!==0)throw new Error(`${language}: ${p.stderr||p.stdout}`);const r=JSON.parse(p.stdout), n={status:r.status,diagnostics:r.diagnostics,plan:r.plan,outputs:r.outputs.map(x=>({sha256:x.sha256,bytes:x.bytes}))};const d=sha(Buffer.from(JSON.stringify(n)));if(normalized&&canonical(n)!==canonical(normalized))throw new Error(`${language}: nondeterministic normalized receipt`);normalized=n;outputDigest=d;if(i>=2)samples.push({wallMs,cpuUserMs:(p.resourceUsage?.userCPUTime??0)/1000,cpuSystemMs:(p.resourceUsage?.systemCPUTime??0)/1000,peakRssBytes:p.resourceUsage?.maxRSS?Math.round(p.resourceUsage.maxRSS*1024):null});}
const bstat=await stat(c.binary),tool=run(c.version[0],c.version.slice(1)).stdout.trim(),metricsAvailable=samples.every(x=>x.peakRssBytes!==null&&(x.cpuUserMs+x.cpuSystemMs)>0);results.push({language,toolchain:tool,binaryBytes:bstat.size,measurementStatus:metricsAvailable?'complete':'blocked-runtime-resource-usage-unavailable',request:{semanticDigest,fixtureDigest},inventory:normalized.plan,normalized:{schemaVersion:'kumo.language-plan/v1',status:normalized.status,diagnostics:normalized.diagnostics,targets:normalized.plan},output:{files:normalized.outputs.length,bytes:normalized.outputs.reduce((a,x)=>a+x.bytes,0),digest:outputDigest},samples,summary:{medianWallMs:pct(samples.map(x=>x.wallMs),.5),p95WallMs:pct(samples.map(x=>x.wallMs),.95)}})}
const env={platform:os.platform(),arch:os.arch(),release:os.release(),cpu:os.cpus()[0]?.model??'unknown'},inventoryDigest=sha(Buffer.from(JSON.stringify(results[0].inventory)));for(const r of results)if(sha(Buffer.from(JSON.stringify(r.inventory)))!==inventoryDigest)throw new Error('planned target inventory mismatch');const receipt={schemaVersion:'kumo.language-shootout/v1',axis:'language',revision,runId:randomUUID(),fixture:{projection:'temporary canonical catalog projection; rebind to shootout/v1 workloads when merged',path:'benchmarks/shootout/languages/fixtures.json',digest:fixtureDigest,components:['button','select'],frameworks:['react']},methodology:{warmups:2,measured:10,retries:0,retryPolicy:'infrastructure failures only',measurement:'Node spawnSync resourceUsage for all candidates; fresh output root each invocation',setupBuild:'excluded and recorded separately by benchmark producer; candidates must already be built',cwd:root,cleanState:initialClean},environment:env,environmentDigest:sha(Buffer.from(JSON.stringify(env))),inventoryDigest,results};await writeFile(dest,JSON.stringify(receipt,null,2)+'\n');console.log(dest);}finally{await rm(temp,{recursive:true,force:true})}
