import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {loadContracts,validateExpectation} from './observable-contracts.mjs';

const decode=s=>s.replace(/&(?:amp|lt|gt|quot|#x27);/g,x=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&#x27;':"'"}[x]));
function element(markup){const m=markup.match(/^<([a-z][\w-]*)([^>]*)>([\s\S]*)<\/\1>$/i);if(!m)throw Error('runner: expected one element root');const attrs={};for(const a of m[2].matchAll(/\s([:\w-]+)(?:="([^"]*)")?/g))attrs[a[1]]=decode(a[2]??'');return {tag:m[1].toLowerCase(),attrs,inner:m[3],text:decode(m[3].replace(/<[^>]*>/g,''))};}
function descendants(markup,selector){const out=[];const tag=selector.startsWith('.')||selector.startsWith('#')?'[a-z][\\w-]*':selector;const re=new RegExp(`<(${tag})([^>]*)>([\\s\\S]*?)<\\/\\1>`,'gi');for(const m of markup.matchAll(re)){const e=element(m[0]);const match=selector.startsWith('.')?(e.attrs.class||'').split(/\s+/).includes(selector.slice(1)):selector.startsWith('#')?e.attrs.id===selector.slice(1):e.tag===selector;if(match)out.push(e);}return out;}
function checkNode(actual,expected,where){if(expected.tag!==undefined&&actual.tag!==expected.tag)throw Error(`${where}: tag expected ${expected.tag}, got ${actual.tag}`);if(expected.text!==undefined&&actual.text!==expected.text)throw Error(`${where}: text expected ${expected.text}, got ${actual.text}`);const classes=(actual.attrs.class||'').split(/\s+/).filter(Boolean);if(expected.classes?.exact&&!same(classes,expected.classes.exact))throw Error(`${where}: exact classes mismatch`);for(const c of expected.classes?.includes||[])if(!classes.includes(c))throw Error(`${where}: missing class ${c}`);if(expected.attributes?.exact){const attrs={...actual.attrs};delete attrs.class;if(!sameObject(attrs,expected.attributes.exact))throw Error(`${where}: exact attributes mismatch`);}for(const [k,v] of Object.entries(expected.attributes?.includes||{}))if(actual.attrs[k]!==v)throw Error(`${where}: attribute ${k} mismatch`);}
const same=(a,b)=>a.length===b.length&&a.every((x,i)=>x===b[i]);
const sameObject=(a,b)=>JSON.stringify(Object.keys(a).sort().map(k=>[k,a[k]]))===JSON.stringify(Object.keys(b).sort().map(k=>[k,b[k]]));
export function compareMarkup(markup,expectation){validateExpectation(expectation);const root=element(markup);checkNode(root,expectation.root,'root');for(const d of expectation.descendants||[]){const found=descendants(root.inner,d.selector);if(found.length!==d.count)throw Error(`descendant ${d.selector}: count expected ${d.count}, got ${found.length}`);found.forEach((x,i)=>checkNode(x,d,`descendant ${d.selector}[${i}]`));}if(expectation.state!==undefined)throw Error('state snapshots require browser adapter');if(expectation.events?.length||expectation.focus!==undefined)throw Error('events/focus require browser adapter');return true;}
function fixtureElement(kind,module,Component,props){
 if(kind==='breadcrumbs'){const B=Component;return React.createElement(B,props,React.createElement(B.Link,{href:'/home'},'Home'),React.createElement(B.Separator),React.createElement(B.Current,null,'Here'));}
 if(kind==='layer-card'){const C=Component;return React.createElement(C,props,React.createElement(C.Secondary,null,'Top'),React.createElement(C.Primary,null,'Main'));}
 if(kind==='table'){const T=Component;if(props.layout==='fixed')return React.createElement(T,props,React.createElement(T.Body,null,React.createElement(T.Row,null,React.createElement(T.Cell,{sticky:'left'},'Pinned'))));return React.createElement(T,props,React.createElement(T.Header,null,React.createElement(T.Row,null,React.createElement(T.Head,null,'Name'))),React.createElement(T.Body,null,React.createElement(T.Row,null,React.createElement(T.Cell,{className:'bg-kumo-tint'},'Kumo'))));}
 throw Error(`runner: unknown canonical fixture ${kind}`);
}
export async function runCanonicalVectors(contracts=loadContracts(),adapter={}){const results=[];for(const c of contracts){const module=await import(c.canonical.exportPath.replace('./','@cloudflare/kumo/'));const Component=module[c.publicApi.exports[0]];if(typeof Component!=='function'&&typeof Component!=='object')throw Error(`${c.component}: canonical export missing`);for(const v of c.vectors){if(v.actions?.length){if(!adapter.run)throw Error(`${c.component}/${v.id}: interactive vectors require browser adapter`);results.push(await adapter.run({contract:c,vector:v,Component,compareMarkup}));}else{const node=v.fixture?fixtureElement(v.fixture.kind,module,Component,v.props):React.createElement(Component,v.props);const markup=renderToStaticMarkup(node);compareMarkup(markup,v.expected);results.push({component:c.component,id:v.id,markup});}}}return results;}
if(import.meta.url===`file://${process.argv[1]}`){const r=await runCanonicalVectors();console.log(`executed ${r.length} canonical vectors`);}
