// Transport-agnostic trusted-CDP observation driver.
// Both the local-Chrome runner and the cloud (Cloudflare Browser Rendering) runner
// build identical fixtures and call this exact driver, so observations are produced
// by one shared trusted protocol regardless of where Chrome physically runs.
const sleep = n => new Promise(r => setTimeout(r, n));
const timeout = (promise, ms, label) => { let t; return Promise.race([promise, new Promise((_, j) => { t = setTimeout(() => j(Error(label + ' timed out after ' + ms + 'ms')), ms); t.unref?.(); })]).finally(() => clearTimeout(t)); };

// `send(method, params, sessionId)` performs one CDP command and resolves its result.
// `diagnostics` is the live array the transport appends unfiltered console/network/exception events to.
// Returns the full observation result identical to the legacy runner.
export async function driveObservableSession({ send, diagnostics, vectors, runVector, ready = '!!globalThis.__ready', vectorTimeoutMs = 20000, telemetry }) {
  await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false });
  const evaluate = async expression => { const x = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true }); if (x.exceptionDetails) throw Error(x.exceptionDetails.exception?.description || x.exceptionDetails.text); return x.result.value; };
  for (let i = 0; i < 200 && !(await evaluate(ready)); i++) await sleep(25);
  await sleep(100);
  const hydration = await evaluate(`(()=>{let app=document.querySelector('#app'),roots=[...app.children],vectors=[...document.querySelectorAll('#app > [id^=v]')];return{appCount:document.querySelectorAll('#app').length,rootCount:roots.length,vectorCount:vectors.length,uniqueIds:new Set(vectors.map(x=>x.id)).size,connected:vectors.every(x=>x.isConnected&&x.parentElement===app),extras:roots.filter(x=>!x.id?.startsWith('v')).map(x=>x.tagName)}})()`);
  if (hydration.appCount !== 1 || hydration.vectorCount !== vectors.length || hydration.uniqueIds !== vectors.length || !hydration.connected || hydration.extras.some(tag => !['STYLE', 'LINK'].includes(tag))) throw Error(`one-tree hydration failed: ${JSON.stringify(hydration)}; diagnostics=${JSON.stringify(diagnostics)}`);
  await evaluate(`[...document.querySelectorAll('#app > [id^=v]')].forEach((x,i)=>x.dataset.observableIdentity=String(i))`);
  const target = async (i, selector, n = 0, scope = 'vector') => { const { root } = await send('DOM.getDocument', { depth: -1, pierce: true }), query = scope === 'document' ? selector : `#v${i} ${selector}`, { nodeIds } = await send('DOM.querySelectorAll', { nodeId: root.nodeId, selector: query }); if (!nodeIds[n]) throw Error(`${vectors[i].id}: target ${selector}[${n}]`); return nodeIds[n]; };
  const scroll = async nodeId => { await send('DOM.scrollIntoViewIfNeeded', { nodeId }); await sleep(50); };
  const focus = async nodeId => { await scroll(nodeId); await send('DOM.focus', { nodeId }); };
  const hit = async (nodeId, x, y) => { const { object } = await send('DOM.resolveNode', { nodeId }), r = await send('Runtime.callFunctionOn', { objectId: object.objectId, functionDeclaration: 'function(x,y){let h=document.elementFromPoint(x,y);return{matches:!!h&&(h===this||this.contains(h)),hit:h?{tag:h.tagName,id:h.id,role:h.getAttribute(\'role\'),outerHTML:h.outerHTML.slice(0,300)}:null,target:{tag:this.tagName,id:this.id,role:this.getAttribute(\'role\')}}}', arguments: [{ value: x }, { value: y }], returnByValue: true }); return r.result.value; };
  const point = async nodeId => { await scroll(nodeId); const { model } = await send('DOM.getBoxModel', { nodeId }), q = model.content, rect = await hit(nodeId, -1, -1).then(async () => { const { object } = await send('DOM.resolveNode', { nodeId }), r = await send('Runtime.callFunctionOn', { objectId: object.objectId, functionDeclaration: 'function(){let r=this.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}}', returnByValue: true }); return r.result.value; }), x = (q[0] + q[2] + q[4] + q[6]) / 4, y = (q[1] + q[3] + q[5] + q[7]) / 4, viewport = await evaluate(`({offsetLeft:visualViewport?.offsetLeft||0,offsetTop:visualViewport?.offsetTop||0,pageLeft:visualViewport?.pageLeft||scrollX,pageTop:visualViewport?.pageTop||scrollY,scrollX,scrollY})`), direct = await hit(nodeId, x, y); if (direct.matches) return { x, y, coordinateSpace: 'viewport', hit: direct }; const candidates = [{ space: 'dom-rect', x: rect.x + rect.width / 2, y: rect.y + rect.height / 2 }, { space: 'document-scroll', x: x - viewport.scrollX, y: y - viewport.scrollY }, { space: 'visual-page', x: x - viewport.pageLeft, y: y - viewport.pageTop }, { space: 'visual-offset', x: x - viewport.offsetLeft, y: y - viewport.offsetTop }]; for (const c of candidates) { const h = await hit(nodeId, c.x, c.y); if (h.matches) return { x: c.x, y: c.y, coordinateSpace: c.space, hit: h }; } throw Error(`click point missed target: ${JSON.stringify({ quad: q, rect, center: { x, y }, direct, viewport, candidates })}`); };
  const click = async nodeId => { const { x, y } = await point(nodeId); for (const type of ['mouseMoved', 'mousePressed', 'mouseReleased']) await send('Input.dispatchMouseEvent', { type, x, y, ...type === 'mouseMoved' ? {} : { button: 'left', clickCount: 1 } }); };
  const key = async (nodeId, k) => { await focus(nodeId); const key = k === 'Space' ? ' ' : k, code = k === 'Space' ? 'Space' : k, virtual = { Enter: 13, Space: 32, ArrowLeft: 37, ArrowUp: 38, ArrowRight: 39, ArrowDown: 40, Home: 36, End: 35, PageUp: 33, PageDown: 34, Escape: 27, Tab: 9 }[k], meta = virtual ? { windowsVirtualKeyCode: virtual, nativeVirtualKeyCode: virtual } : {}; await send('Input.dispatchKeyEvent', { type: 'keyDown', key, code, ...meta, ...k === 'Enter' ? { text: '\r', unmodifiedText: '\r' } : {} }); if (key.length === 1) await send('Input.dispatchKeyEvent', { type: 'char', text: key, key, code, ...meta }); await send('Input.dispatchKeyEvent', { type: 'keyUp', key, code, ...meta }); };
  const type = async (nodeId, text, { replace = false } = {}) => { await focus(nodeId); const { object } = await send('DOM.resolveNode', { nodeId }); await send('Runtime.callFunctionOn', { objectId: object.objectId, functionDeclaration: replace ? 'function(){this.select()}' : 'function(){let n=this.value.length;this.setSelectionRange(n,n)}' }); for (const c of text) { const code = /^[a-z]$/i.test(c) ? `Key${c.toUpperCase()}` : /^[0-9]$/.test(c) ? `Digit${c}` : '', v = c.toUpperCase().charCodeAt(0); await send('Input.dispatchKeyEvent', { type: 'keyDown', key: c, code, text: c, unmodifiedText: c, windowsVirtualKeyCode: v, nativeVirtualKeyCode: v }); await send('Input.dispatchKeyEvent', { type: 'keyUp', key: c, code, windowsVirtualKeyCode: v, nativeVirtualKeyCode: v }); } };
  const action = async (i, a) => { if (a.type === 'wait') { await sleep(a.ms); return; } if (a.type === 'viewport') { await send('Emulation.setDeviceMetricsOverride', { width: a.width, height: a.height, deviceScaleFactor: 1, mobile: false }); return; } let node; if (a.scope === 'active') { const active = await send('Runtime.evaluate', { expression: 'document.activeElement', objectGroup: 'observable-active' }), requested = await send('DOM.requestNode', { objectId: active.result.objectId }); node = requested.nodeId; } else node = await target(i, a.selector || 'input,textarea,button,[role]', a.target || 0, a.scope ?? 'vector'); if (a.type === 'scroll') await scroll(node); else if (a.type === 'click' || a.type === 'outside-pointer') await click(node); else if (a.type === 'focus') await focus(node); else if (a.type === 'blur') { await focus(node); await key(node, 'Tab'); } else if (a.type === 'key') await key(node, a.key); else if (a.type === 'type') await type(node, a.text, { replace: a.editMode === 'replace' }); else if (a.type === 'type-replace') await type(node, a.text, { replace: true }); else if (a.type === 'select') { await focus(node); await key(node, a.value); } else throw Error(`unsupported trusted action ${a.type}`); await sleep(a.wait ?? 30); };
  const api = { send, evaluate, target, scroll, focus, click, key, type, action, sleep };
  const now = () => Number(process.hrtime.bigint()) / 1e6;
  const results = [];
  for (let i = 0; i < vectors.length; i++) { const t = now(); try { const identity = await evaluate(`document.querySelector('#v${i}')?.dataset.observableIdentity`); if (identity !== String(i)) throw Error('hydrated vector root identity was replaced'); results.push(await timeout(runVector(api, vectors[i], i), vectorTimeoutMs, vectors[i].component + '/' + vectors[i].id)); } catch (error) { const snapshot = await evaluate(`(()=>{let b=document.querySelector('#v${i}');return{html:b?.innerHTML,active:document.activeElement?.outerHTML}})()`); throw Error(`${vectors[i].component}/${vectors[i].id} failed: ${error.message}; snapshot=${JSON.stringify(snapshot)}; diagnostics=${JSON.stringify(diagnostics)}`); } finally { telemetry?.vectors.push({ component: vectors[i].component, id: vectors[i].id, ms: now() - t }); } }
  await sleep(100);
  if (diagnostics.length) throw Error(`browser diagnostics: ${JSON.stringify(diagnostics)}`);
  return { results, browserCells: results.length, diagnostics, telemetry, capabilities: ['trusted-cdp', 'native-focus', 'native-edit', 'clipboard-boundary', 'hydration'] };
}
