#!/usr/bin/env node
import path from 'node:path';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { PACKAGE,FRAMEWORKS,contained,diffInventories,extractTarball,fetchVersion,inventory,inventorySummary,sha,stable,writeImmutable } from './upstream/lib.mjs';

const ROOT=path.resolve(new URL('..',import.meta.url).pathname);
const PROVENANCE_PATHS=['workflow.json','src/kumo','scripts/compiler-protocol'];
export function parseArgs(argv){const o={scenario:'real',calibrationComponent:'button'};for(let i=0;i<argv.length;i++){const k=argv[i];if(!['--from','--to','--scenario','--out','--calibration-component'].includes(k))throw new Error(`unknown argument: ${k}`);if(!argv[i+1]||argv[i+1].startsWith('--'))throw new Error(`missing value: ${k}`);o[k.slice(2).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=argv[++i];}if(!o.from||!o.to)throw new Error('--from and --to are required');if(!['real','synthetic-export-break'].includes(o.scenario))throw new Error(`unknown scenario: ${o.scenario}`);return o;}
export async function run(opts){
 const workspace=await mkdtemp(path.join(tmpdir(),'kumo-upstream-check-')); const requested=opts.out?path.resolve(process.cwd(),opts.out):path.join(workspace,'result');
 const operatorWorkspace=process.env.KUMO_UPSTREAM_OPERATOR_WORKSPACE&&path.resolve(process.env.KUMO_UPSTREAM_OPERATOR_WORKSPACE);
 if(!contained(ROOT,requested)&&!contained(workspace,requested)&&!(operatorWorkspace&&contained(operatorWorkspace,requested)))throw new Error('--out must be inside the repository or isolated workspace');
 const cleanBefore=gitStatus();
 try{const oldFetched=await fetchVersion(opts.from),newFetched=await fetchVersion(opts.to);const oldDir=path.join(workspace,'old'),newDir=path.join(workspace,'new');await extractTarball(oldFetched.body,oldDir);await extractTarball(newFetched.body,newDir);const oldInv=await inventory(oldDir),newInv=await inventory(newDir);
  if(oldInv.package.name!==PACKAGE||oldInv.package.version!==opts.from||newInv.package.name!==PACKAGE||newInv.package.version!==opts.to)throw new Error('extracted package identity mismatch');
  if(opts.scenario==='synthetic-export-break'){const pkgPath=path.join(newDir,'package.json'),pkg=JSON.parse(await readFile(pkgPath,'utf8'));if(typeof pkg.exports==='object'&&pkg.exports){const keys=Object.keys(pkg.exports).sort(),key=keys.find(x=>x.startsWith('./components/'))??keys[0];if(!key)throw new Error('fixture has no export to mutate');delete pkg.exports[key];}else delete pkg.main;await writeFile(pkgPath,JSON.stringify(pkg,null,2)+'\n');Object.assign(newInv,await inventory(newDir));}
  const changes=diffInventories(oldInv,newInv),mapping=await componentMapping(),mapped=new Set(),unknown=[];
  for(const c of changes){const id=mapChange(c.path,mapping);if(id)mapped.add(id);else if(c.path.startsWith('exports.')||c.path.startsWith('declarations.'))unknown.push(c.path);}
  const affected=[...mapped].sort(),globalReview=unknown.length>0;
  if(!mapping.has(opts.calibrationComponent))throw new Error(`unknown calibration component: ${opts.calibrationComponent}`);
  let generation={componentId:opts.calibrationComponent,status:'not-run',reason:'global review blocks calibration',cells:[]};
  if(!globalReview)generation=await generateCells(workspace,opts.calibrationComponent);
  const cells=[];for(const componentId of affected)for(const framework of FRAMEWORKS){const generated=generation.cells.find(x=>x.componentId===componentId&&x.framework===framework);cells.push({componentId,framework,status:generated?.status??'blocked',reason:generated?.reason??'affected non-calibration component was not attempted',attempted:Boolean(generated),outputManifest:generated?.outputManifest??[]});}
  if(globalReview)for(const framework of FRAMEWORKS)cells.push({componentId:null,framework,status:'blocked',reason:'unknown public API change requires global review',attempted:false,outputManifest:[]});
  const sourceTree=gitSourceTree(),source={revision:gitRevision(),sourceTree,provenancePaths:PROVENANCE_PATHS};
  const core={schemaVersion:'kumo.upstream.receipt/v3',runId:sha(stable({sourceTree,package:PACKAGE,from:opts.from,to:opts.to,scenario:opts.scenario})),scenario:opts.scenario,status:changes.some(c=>c.impact==='breaking')||globalReview?'blocked':'passed',source,clean:{before:cleanBefore==='',after:null},package:PACKAGE,baseline:pkgRecord(oldFetched),candidate:pkgRecord(newFetched),inventories:{baseline:inventorySummary(oldInv),candidate:inventorySummary(newInv)},diff:{changes,affectedComponentIds:affected,unknownApiChanges:unknown},authority:{status:globalReview||affected.length?'failed':'passed',failClosed:true,selectedAuthorityMutated:false,staleDecision:globalReview?'blocked-global-review':affected.length?'blocked-affected-cells':'no-authority-impact',cells},targets:cells,generation,behavior:{status:'not-run',reason:'no explicit behavior vector selected'},dom:{status:'not-run',reason:'no explicit DOM vector selected'},commands:[`node scripts/upstream-check.mjs --from ${opts.from} --to ${opts.to} --scenario ${opts.scenario}`]};
  const cleanAfter=gitStatus();core.clean.after=cleanAfter==='';if(cleanAfter!==cleanBefore)throw new Error('main worktree changed during isolated run');const receipt={...core,receiptSha256:sha(stable(core))};await mkdir(requested,{recursive:true});await writeImmutable(path.join(requested,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');return {receipt,out:requested};
 }finally{if(!opts.out)await rm(workspace,{recursive:true,force:true});}
}
async function componentMapping(){const c=JSON.parse(await readFile(path.join(ROOT,'generated/canonical-react-catalog.json'),'utf8'));const m=new Map;for(const [id,x] of Object.entries(c.components)){m.set(id,id);m.set(x.symbol,id);m.set(x.exportPath,id);m.set(x.exportPath.replace('@cloudflare/kumo/','./'),id);}return m;}
function mapChange(value,m){const raw=value.replace(/^(exports|declarations)\./,'');if(m.has(raw))return m.get(raw);for(const [key,id] of m)if(raw===key||raw.endsWith('/'+key)||raw.endsWith('.'+key))return id;return null;}
async function generateCells(workspace,componentId){const stage=path.join(workspace,'compiler'),out=path.join(stage,'output');await mkdir(stage,{recursive:true});const sourceFiles=['src/kumo/catalog.ts','src/kumo/schema.ts','src/kumo/validate.ts','src/kumo/compiler.ts','src/kumo/solid-compiler.ts','src/kumo/svelte-compiler.ts','generated/catalog.ir.json','generated/canonical-react-catalog.json','scripts/generate-canonical-react-runtimes.mjs','public/styles.css','public/button.css','public/dialog.css','public/popover.css','public/form.css','public/native-control.css','public/navigation.css','public/selection-command-date.css'];for(const rel of sourceFiles){const dest=path.join(stage,rel);await mkdir(path.dirname(dest),{recursive:true});await writeFile(dest,await readFile(path.join(ROOT,rel)));}await writeFile(path.join(stage,'package.json'),'{"type":"module"}\n');await writeFile(path.join(stage,'tsconfig.json'),JSON.stringify({compilerOptions:{target:'ES2022',module:'NodeNext',moduleResolution:'NodeNext',rootDir:'src/kumo',outDir:'dist/kumo',strict:true,skipLibCheck:true,typeRoots:[path.join(ROOT,'node_modules/@types')]},include:['src/kumo/**/*.ts']})+'\n');
 const commands={react:['scripts/generate-canonical-react-runtimes.mjs'],vue:['dist/kumo/compiler.js'],solid:['dist/kumo/solid-compiler.js'],svelte:['dist/kumo/svelte-compiler.js']},cells=[];execFileSync(path.join(ROOT,'node_modules/.bin/tsc'),['-p','tsconfig.json'],{cwd:stage,stdio:'pipe'});
 for(const framework of FRAMEWORKS){const command=commands[framework];let status='failed',reason='compiler command failed',manifest=[];try{execFileSync(process.execPath,command,{cwd:stage,stdio:'pipe'});const generated=path.join(stage,framework==='react'?'runtime-canonical':'runtime',componentId,...(framework==='react'?[]:[framework]));const cellRoot=path.join(out,componentId,framework);await copyFiles(generated,cellRoot);manifest=await hashFiles(cellRoot,out);status='passed';reason='real compiler generation completed in isolated minimal workspace';}catch(e){reason=String(e.message).split('\n')[0];}cells.push({componentId,framework,status,reason,command:['node',...command],outputManifest:manifest});}
 return {componentId,status:cells.every(x=>x.status==='passed')?'passed':'failed',reason:'bounded real compiler generation',cells};}
async function copyFiles(from,to){const {readdir,lstat}=await import('node:fs/promises');await mkdir(to,{recursive:true});for(const n of (await readdir(from)).sort()){const src=path.join(from,n),dest=path.join(to,n),s=await lstat(src);if(s.isSymbolicLink())throw Error('generated symlink forbidden');if(s.isDirectory())await copyFiles(src,dest);else await writeFile(dest,await readFile(src));}}
async function hashFiles(dir,root){const {readdir,lstat}=await import('node:fs/promises');const out=[];async function walk(d){for(const n of (await readdir(d)).sort()){const f=path.join(d,n),s=await lstat(f);if(s.isSymbolicLink())throw Error('generated symlink forbidden');if(s.isDirectory())await walk(f);else out.push({path:path.relative(root,f).split(path.sep).join('/'),sha256:sha(await readFile(f))});}}await walk(dir);return out;}
function pkgRecord(x){return {version:x.metadata.version,resolved:x.metadata.dist.tarball,integrity:x.metadata.dist.integrity,tarballSha256:x.sha256};}
function gitRevision(){try{return execFileSync('git',['rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8'}).trim()}catch{return 'unknown'}}
function gitStatus(){try{return execFileSync('git',['status','--porcelain=v1','--untracked-files=no'],{cwd:ROOT,encoding:'utf8'})}catch{return ''}}
function gitSourceTree(){const listing=execFileSync('git',['ls-tree','-r','HEAD','--',...PROVENANCE_PATHS],{cwd:ROOT,encoding:'utf8'});return sha(listing);}
if(import.meta.url===new URL(`file://${process.argv[1]}`).href){try{const r=await run(parseArgs(process.argv.slice(2)));console.log(JSON.stringify({status:r.receipt.status,out:r.out,receiptSha256:r.receipt.receiptSha256}));if(r.receipt.status!=='passed')process.exitCode=2;}catch(e){console.error(e.message);process.exitCode=1;}}
