import {createHash} from 'node:crypto';
import {readFile,writeFile,mkdir,rm} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {resolve} from 'node:path';
import sharp from '../astro/node_modules/sharp/lib/index.js';
const root=resolve(import.meta.dirname,'..'),origin=process.env.KUMO_SMOKE_ORIGIN||'http://127.0.0.1:4321',chrome=process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),catalog=JSON.parse(await readFile(resolve(root,'generated/catalog.ir.json'),'utf8')),components=catalog.components.map(x=>x.id).sort(),viewports=[1440];
async function open(){const profile=`/tmp/kumo-visual-${process.pid}-${Date.now()}`,child=spawn(chrome,['--headless=new','--no-first-run','--disable-extensions','--disable-background-networking',`--user-data-dir=${profile}`,'--remote-debugging-port=0','about:blank'],{stdio:'ignore'});let port;for(let i=0;i<100;i++){try{port=(await readFile(`${profile}/DevToolsActivePort`,'utf8')).split(/\s/)[0];break}catch{await sleep(50)}}const pages=await fetch(`http://127.0.0.1:${port}/json`).then(r=>r.json()),ws=new WebSocket(pages.find(x=>x.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map(),diagnostics=[];ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id);return}if(m.method==='Runtime.exceptionThrown')diagnostics.push({kind:'exception',text:m.params.exceptionDetails?.text});if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')diagnostics.push({kind:'console',text:m.params.args.map(x=>x.value??x.description).join(' ')});if(m.method==='Network.loadingFailed')diagnostics.push({kind:'network',text:m.params.errorText});if(m.method==='Network.responseReceived'&&m.params.response.status>=400)diagnostics.push({kind:'http',status:m.params.response.status,url:m.params.response.url})};const send=(method,params={})=>new Promise((ok,no)=>{const n=++id;pending.set(n,m=>m.error?no(Error(m.error.message)):ok(m.result));ws.send(JSON.stringify({id:n,method,params}))});await send('Runtime.enable');await send('Network.enable');await send('Page.enable');return{child,ws,send,diagnostics}}
const val=(send,expression)=>send('Runtime.evaluate',{expression,returnByValue:true}).then(x=>x.result.value);
async function shot(b,url,selector,width,file){await b.send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:false});await b.send('Page.navigate',{url});await sleep(350);const rect=await val(b.send,`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)return null;const r=e.getBoundingClientRect();return{x:Math.max(0,r.x),y:Math.max(0,r.y),width:Math.max(1,Math.min(r.width,${width})),height:Math.max(1,Math.min(r.height,850)),tag:e.tagName,html:e.outerHTML.slice(0,240)}})()`);if(!rect)return{failure:'missing-root'};const data=await b.send('Page.captureScreenshot',{format:'png',clip:{x:rect.x,y:rect.y,width:rect.width,height:rect.height,scale:1},captureBeyondViewport:true});await writeFile(file,Buffer.from(data.data,'base64'));return rect}
async function compare(a,b,diff){const bytesA=await readFile(a),bytesB=await readFile(b),sha256=bytes=>createHash('sha256').update(bytes).digest('hex'),ma=await sharp(bytesA).metadata(),mb=await sharp(bytesB).metadata();if(ma.width!==mb.width||ma.height!==mb.height)return{equal:false,widthA:ma.width,heightA:ma.height,widthB:mb.width,heightB:mb.height,differingPixels:null,reactSha256:sha256(bytesA),nativeSha256:sha256(bytesB)};const ra=await sharp(a).ensureAlpha().raw().toBuffer(),rb=await sharp(b).ensureAlpha().raw().toBuffer();let differing=0;const out=Buffer.alloc(ra.length);for(let i=0;i<ra.length;i+=4){let pixel=false;for(let c=0;c<4;c++){const d=Math.abs(ra[i+c]-rb[i+c]);out[i+c]=d;pixel ||= d!==0}out[i+3]=255;if(pixel)differing++}const diffBytes=await sharp(out,{raw:{width:ma.width,height:ma.height,channels:4}}).png().toBuffer();await writeFile(diff,diffBytes);return{equal:differing===0,widthA:ma.width,heightA:ma.height,widthB:mb.width,heightB:mb.height,differingPixels:differing,totalPixels:ma.width*ma.height,reactSha256:sha256(bytesA),nativeSha256:sha256(bytesB),diffSha256:sha256(diffBytes)}}
export async function audit(){const dir=resolve(root,'proof/visual-parity'),shots=resolve(dir,'screens');await rm(shots,{recursive:true,force:true});await mkdir(shots,{recursive:true});const b=await open(),cells=[];try{for(const width of viewports)for(const component of components){const react=resolve(shots,`${component}.react.${width}.png`),reactRect=await shot(b,`${origin}/${component}/react`,`[data-canonical-component="${component}"] > *`,width,react);for(const framework of ['vue','svelte','solid']){const native=resolve(shots,`${component}.${framework}.${width}.png`),diff=resolve(shots,`${component}.${framework}.${width}.diff.png`),nativeRect=await shot(b,`${origin}/library-gallery/${framework}/?component=${component}`,`[data-native-fixture="${component}"] > *`,width,native);const result=reactRect.failure||native.failure?{equal:false,failure:reactRect.failure||native.failure}:await compare(react,native,diff);cells.push({component,framework,width,state:'default',reactRect,nativeRect,...result})}}}finally{b.ws.close();b.child.kill()}const failed=cells.filter(x=>!x.equal),report={schemaVersion:'kumo.visual-parity/v1',environment:{chrome:'system-headless',deviceScaleFactor:1,viewports,states:['default']},scope:{components:41,frameworks:3,cells:cells.length},cells,diagnostics:b.diagnostics,status:failed.length===0&&b.diagnostics.length===0?'passed':'failed',counts:{passed:cells.length-failed.length,failed:failed.length}};await mkdir(dir,{recursive:true});await writeFile(resolve(dir,'latest.json'),JSON.stringify(report,null,2)+'\n');return report}
if(import.meta.url===`file://${process.argv[1]}`)audit().then(r=>{console.log(`Visual parity: ${r.status}; ${r.counts.passed}/${r.scope.cells}; diagnostics=${r.diagnostics.length}`);for(const c of r.cells.filter(x=>!x.equal).slice(0,50))console.log(`${c.component}/${c.framework}@${c.width}: ${c.failure??`${c.differingPixels??'size'} pixels differ (${c.widthA}x${c.heightA} vs ${c.widthB}x${c.heightB})`}`);if(r.status!=='passed')process.exit(1)}).catch(e=>{console.error(e.stack);process.exit(1)});
