import path from'node:path';
import{fileURLToPath}from'node:url';
import{runObservableBrowser}from'../../../../scripts/observable-browser-runner.mjs';
import{scheduleObservableBrowser}from'../../../../scripts/observable-browser-scheduler.mjs';
import{executeTogglePlan}from'../shared/toggle-executor.mjs';
import{compareMarkup}from'../../../../scripts/observable-runner.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../..'),ids=new Set(['disabled-click','loading-click','enabled-click','submit-form']),json=JSON.stringify;


export async function runSolidButtonBrowser({consumer,vectors,ssrRenders}){const specs=vectors.filter(v=>v.provenance.vector.startsWith('button/')&&ids.has(v.provenance.vector.split('/')[1])).map(v=>({...v,component:'button',id:v.provenance.vector.split('/')[1]}));if(specs.length!==4||ssrRenders.length!==4)throw Error('Solid Button browser slice requires exactly four vectors');const results=[],diagnostics=[],telemetry=[];for(let i=0;i<4;i++){const spec=specs[i],data={id:spec.id,props:spec.fixture.props,children:spec.fixture.children.map(n=>n.value??'').join('')};const source=`import{hydrate}from'solid-js/web';import{Button}from'@acoyfellow/kumo-solid/button';const S=${json(data)};document.body.dataset.events='[]';document.body.dataset.clicks='0';document.body.dataset.submits='0';function click(){document.body.dataset.clicks=String(+document.body.dataset.clicks+1);let e=JSON.parse(document.body.dataset.events);e.push('click');document.body.dataset.events=JSON.stringify(e)}function submit(e){e.preventDefault();document.body.dataset.submits=String(+document.body.dataset.submits+1);let x=JSON.parse(document.body.dataset.events);x.push('submit');document.body.dataset.events=JSON.stringify(x)}function App(){return S.id==='submit-form'?<section id="v0"><form onSubmit={submit}><Button {...S.props} onClick={click}>{S.children}</Button></form></section>:<section id="v0"><Button {...S.props} onClick={click}>{S.children}</Button></section>}hydrate(()=> <App/>,document.querySelector('#app'),{renderId:'kumo-'});document.body.dataset.events='[]';document.body.dataset.clicks='0';document.body.dataset.submits='0';queueMicrotask(()=>globalThis.__ready=true);`;const run=await runObservableBrowser({name:'solid-packed-button-'+spec.id,entrySource:source,entryFilename:'client.jsx',viteConfig:path.join(root,'proof/dx/conformance/shared/solid-vite.config.mjs'),buildEnv:{KUMO_CONSUMER:consumer},cssPath:path.join(consumer,'node_modules/@acoyfellow/kumo-solid/package/styles.css'),html:ssrRenders[i].html,beforeAppHtml:ssrRenders[i].hydrationScript,vectors:[spec],runVector:async(api,current)=>{for(const action of current.actions)await api.action(0,{...action,selector:'button'});const got=await api.evaluate(`(()=>{const button=document.querySelector('#v0 button');return{html:button.outerHTML,clicks:+document.body.dataset.clicks,submits:+document.body.dataset.submits,events:JSON.parse(document.body.dataset.events),focus:document.activeElement===button?'root':'none',svg:button.querySelectorAll('svg').length}})()`);compareMarkup(got.html,{root:current.expected.root,descendants:current.expected.descendants});return{component:'button',id:current.id,passed:true,ssr:'passed',hydration:'passed',nodeIdentity:'preserved',observation:got}}});results.push(...run.results);diagnostics.push(...run.diagnostics);telemetry.push(run.telemetry)}return{results,browserCells:results.length,diagnostics,telemetry,capabilities:['trusted-cdp','native-focus','hydration','isolated-vector-batches']}}

export async function runSolidToggleBrowser({consumer,plans,ssrRenders}){
 if(plans.length!==10||ssrRenders.length!==10)throw Error(`Solid toggle adapter requires all ten shared plans: plans=${plans.length} ssr=${ssrRenders.length}`);
 const results=[],diagnostics=[],telemetry=[];
 for(let batch=0;batch<plans.length;batch++){
  const plan=plans[batch],vectors=[plan];
  const source=`import{createSignal,For}from'solid-js';import{hydrate}from'solid-js/web';import{Checkbox}from'@acoyfellow/kumo-solid/checkbox';import{Switch}from'@acoyfellow/kumo-solid/switch';const P=${json([plan])};document.body.dataset.events='[]';const record=x=>{const e=JSON.parse(document.body.dataset.events);e.push(x);document.body.dataset.events=JSON.stringify(e)};function Single(p){const C=p.plan.component==='checkbox'?Checkbox:Switch,[checked,setChecked]=createSignal(p.plan.setup[0].initial),controlled=p.plan.setup[0].mode==='controlled',change=next=>{setChecked(next);if(p.plan.setup.some(x=>x.kind==='event-recorder'))record('checked:'+next)},props=()=>({...p.plan.fixture.props,...controlled?{checked:checked()}: {},onCheckedChange:change});return <C {...props()}/>}function Group(p){const payload=p.plan.fixture.payload,[values,setValues]=createSignal(payload.defaultValue??[]),checkbox=p.plan.component==='checkbox';return <fieldset><legend>{payload.legend}</legend><div role={checkbox?'group':undefined}><For each={payload.items}>{(item,i)=>{const change=next=>{if(checkbox){const value=item.value,nextValues=next?[...new Set([...values(),value])]:values().filter(x=>x!==value);setValues(nextValues);record('value:'+nextValues.join(','))}else record('item'+i()+':'+next)};return <label>{checkbox?<Checkbox aria-label={item.label} defaultChecked={payload.defaultValue?.includes(item.value)} disabled={item.disabled} onCheckedChange={change}/>:<Switch aria-label={item.label} disabled={item.disabled} onCheckedChange={change}/>} {item.label}</label>}}</For></div></fieldset>}function Fixture(p){return p.plan.fixture.kind==='family-fixture'?<Group plan={p.plan}/>:<Single plan={p.plan}/>}function App(){return <section id="v0"><Fixture plan={P[0]}/></section>}const before=[...document.querySelectorAll('#v0 [role=checkbox],#v0 [role=switch]')];hydrate(()=> <App/>,document.querySelector('#app'),{renderId:'kumo-'});document.body.dataset.events='[]';queueMicrotask(()=>{globalThis.__toggleRoots=before;globalThis.__ready=true});`;
  const run=await scheduleObservableBrowser(()=>runObservableBrowser({name:`solid-packed-toggle-${plan.component}-${plan.vector}`,entrySource:source,entryFilename:'client.jsx',viteConfig:path.join(root,'proof/dx/conformance/shared/solid-vite.config.mjs'),buildEnv:{KUMO_CONSUMER:consumer},cssPath:path.join(consumer,'node_modules/@acoyfellow/kumo-solid/package/styles.css'),html:ssrRenders[batch].html,headHtml:'<style>[role="checkbox"]{display:inline-block;inline-size:16px;block-size:16px}</style>',beforeAppHtml:ssrRenders[batch].hydrationScript??'',vectors,runVector:async(api,current)=>{let target=0,beforeEvents=0;const result=await executeTogglePlan({setup:async()=>{},action:action=>{target=action.target??0;return api.action(0,{...action,selector:'[role=checkbox],[role=switch]',target})},probe:async probe=>{const value=await api.evaluate(`(()=>{const section=document.querySelector('#v0'),controls=[...section.querySelectorAll('[role=checkbox],[role=switch]')],node=controls[${target}],root=${current.fixture.kind==='family-fixture'?"section.querySelector('[role=group]')||section.querySelector('fieldset')":'node'},attrs=Object.fromEntries([...root.attributes].map(x=>[x.name,x.value])),checked=controls.map(x=>x.getAttribute('aria-checked')==='true'),events=JSON.parse(document.body.dataset.events);return{dom:{tag:root.tagName.toLowerCase(),attributes:{includes:attrs},classes:{includes:[...root.classList]}},aria:{includes:Object.fromEntries(Object.entries(attrs).filter(([k])=>k==='role'||k.startsWith('aria-')||k==='disabled'))},state:{checked:${current.fixture.kind==='family-fixture'?'checked':'checked[0]'}},events:events.slice(${beforeEvents}),focus:document.activeElement===node?'root':'none',identity:globalThis.__toggleRoots[${target}]===node}})()`);if(probe.kind==='dom')return value.dom;if(probe.kind==='aria')return value.aria;if(probe.kind==='state')return value.state;if(probe.kind==='events'){beforeEvents+=value.events.length;return value.events}if(probe.kind==='focus')return value.focus;if(probe.kind==='node-identity')return value.identity?'preserved':'replaced'}},current);return{component:current.component,id:current.vector,passed:true,ssr:'passed',hydration:'passed',nodeIdentity:'preserved',observation:result.probes}}}),{label:`Solid toggle ${plan.component}/${plan.vector}`});
  results.push(...run.results);diagnostics.push(...run.diagnostics);telemetry.push({id:`${plan.component}/${plan.vector}`,...run.telemetry});
 }
 return{results,browserCells:results.length,diagnostics,telemetry,capabilities:['trusted-cdp','native-focus','hydration','shared-toggle-plans','isolated-vector-batches','direct-root-identity']};
}
