import path from'node:path';
import{fileURLToPath}from'node:url';
import{runObservableBrowser}from'../../../../scripts/observable-browser-runner.mjs';
import{scheduleObservableBrowser}from'../../../../scripts/observable-browser-scheduler.mjs';
import{executeTogglePlan}from'../shared/toggle-executor.mjs';
export{runSolidButtonBrowser}from'./button-browser-adapter.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../..'),json=JSON.stringify;

export async function runSolidToggleBrowser({consumer,plans,ssrRenders}){
 if(plans.length!==10||ssrRenders.length!==10)throw Error('Solid toggle adapter requires all ten shared plans');
 const vectors=plans.map((plan,id)=>({...plan,id:String(id)}));
 const source=`import{createSignal,For}from'solid-js';import{hydrate}from'solid-js/web';import{Checkbox}from'@acoyfellow/kumo-solid/checkbox';import{Switch}from'@acoyfellow/kumo-solid/switch';const P=${json(plans)};document.body.dataset.events='[]';const record=x=>{const e=JSON.parse(document.body.dataset.events);e.push(x);document.body.dataset.events=JSON.stringify(e)};function Single(p){const C=p.plan.component==='checkbox'?Checkbox:Switch,[checked,setChecked]=createSignal(p.plan.setup[0].initial),controlled=p.plan.setup[0].mode==='controlled',change=next=>{setChecked(next);if(p.plan.setup.some(x=>x.kind==='event-recorder'))record('checked:'+next)},props=()=>({...p.plan.fixture.props,...controlled?{checked:checked()}: {},onCheckedChange:change});return <C {...props()}/>}function Group(p){const payload=p.plan.fixture.payload,[values,setValues]=createSignal(payload.defaultValue??[]),checkbox=p.plan.component==='checkbox';return <fieldset><legend>{payload.legend}</legend><div role={checkbox?'group':undefined}><For each={payload.items}>{(item,i)=>{const change=next=>{if(checkbox){const value=item.value,nextValues=next?[...values(),value]:values().filter(x=>x!==value);setValues(nextValues);record('value:'+nextValues.join(','))}else record('item'+i()+':'+next)};return <label>{checkbox?<Checkbox aria-label={item.label} defaultChecked={payload.defaultValue?.includes(item.value)} disabled={item.disabled} onCheckedChange={change}/>:<Switch aria-label={item.label} disabled={item.disabled} onCheckedChange={change}/>} {item.label}</label>}}</For></div></fieldset>}function Fixture(p){return p.plan.fixture.kind==='family-fixture'?<Group plan={p.plan}/>:<Single plan={p.plan}/>}function App(){return <For each={P}>{(plan,i)=><section id={'v'+i()}><Fixture plan={plan}/></section>}</For>}const before=P.map((_,i)=>document.querySelector('#v'+i)?.firstElementChild);hydrate(()=> <App/>,document.querySelector('#app'),{renderId:'kumo-'});document.body.dataset.events='[]';queueMicrotask(()=>{globalThis.__toggleRoots=before;globalThis.__ready=true});`;
 return scheduleObservableBrowser(()=>runObservableBrowser({name:'solid-packed-toggles',entrySource:source,entryFilename:'client.jsx',viteConfig:path.join(root,'proof/dx/conformance/shared/solid-vite.config.mjs'),buildEnv:{KUMO_CONSUMER:consumer},cssPath:path.join(consumer,'node_modules/@acoyfellow/kumo-solid/package/styles.css'),html:ssrRenders.map(x=>x.html).join(''),beforeAppHtml:ssrRenders[0]?.hydrationScript??'',vectors,runVector:async(api,plan,index)=>{let beforeEvents=[];const result=await executeTogglePlan({setup:async()=>{},action:action=>api.action(index,{...action,selector:'[role=checkbox],[role=switch]'}),probe:async probe=>{const value=await api.evaluate(`(()=>{const section=document.querySelector('#v${index}'),controls=[...section.querySelectorAll('[role=checkbox],[role=switch]')],root=${plan.fixture.kind==='family-fixture'?"section.querySelector('[role=group]')||section.querySelector('fieldset')":'controls[0]'},attrs=Object.fromEntries([...root.attributes].map(x=>[x.name,x.value])),checked=controls.map(x=>x.getAttribute('aria-checked')==='true');return{dom:{tag:root.tagName.toLowerCase(),attributes:{includes:attrs},classes:{includes:[...root.classList]}},aria:{includes:attrs},state:{checked:${plan.fixture.kind==='family-fixture'?'checked':'checked[0]'}},events:JSON.parse(document.body.dataset.events).slice(${beforeEvents.length}),focus:document.activeElement&&controls.includes(document.activeElement)?'root':'none',identity:globalThis.__toggleRoots[${index}]===section.firstElementChild}})()`);if(probe.kind==='dom')return value.dom;if(probe.kind==='aria')return value.aria;if(probe.kind==='state')return value.state;if(probe.kind==='events'){beforeEvents=value.events;return value.events}if(probe.kind==='focus')return value.focus;if(probe.kind==='node-identity')return value.identity?'preserved':'replaced'}} ,plan);return{component:plan.component,id:plan.vector,passed:true,ssr:'passed',hydration:'passed',nodeIdentity:'preserved',observation:result.probes}}),{label:'Solid packed toggle conformance'});
}
