import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../..');
const TYPES=new Set(['click','focus','blur','key','type','wait']);
const literal=x=>x===null||['string','number','boolean'].includes(typeof x)||Array.isArray(x)&&x.every(literal)||x&&Object.getPrototypeOf(x)===Object.prototype&&Object.values(x).every(literal);
export const stable=x=>Array.isArray(x)?x.map(stable):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])])):x;
export const digest=x=>crypto.createHash('sha256').update(typeof x==='string'?x:JSON.stringify(stable(x))).digest('hex');
function fail(ok,msg){if(!ok)throw Error(msg)}
export function validatePlan(p){fail(p&&p.schemaVersion==='kumo.packed-fixture/v1','invalid packed fixture schema');fail(literal(p),'plan must be strict JSON');fail(!/(?:<\/?[A-Za-z]|<!doctype|dispatchEvent|new Event|new MouseEvent|new KeyboardEvent)/.test(JSON.stringify(p)),'source, HTML, or synthetic events forbidden');fail(Array.isArray(p.vectors)&&p.vectors.length===p.inventory.total,'inventory mismatch');let ids=p.vectors.map(v=>v.provenance.vector);fail(new Set(ids).size===ids.length,'duplicate vector');for(const v of p.vectors){fail(v.import&&v.import.export,'missing export');fail(v.node?.kind==='component','missing component node');for(const a of v.actions)fail(TYPES.has(a.type)&&a.trustedRunner==='scripts/observable-browser-runner.mjs','untrusted action')}return p}
function compileContract(c,source){fail(c.schemaVersion==='kumo.observable/v1','bad contract schema');fail(c.component&&c.canonical?.exportPath&&Array.isArray(c.publicApi?.exports)&&c.publicApi.exports.length,'invalid contract API');const exp=c.publicApi.exports.find(x=>x.toLowerCase().replaceAll('-','')===c.component.replaceAll('-',''))||c.publicApi.exports.find(x=>/^[A-Z]/.test(x));fail(exp,'no component export');return c.vectors.map(v=>{fail(v.id&&literal(v.props||{})&&literal(v.expected||{}),'non-serializable vector');const actions=(v.actions||[]).map(a=>{fail(TYPES.has(a.type),`unsupported action ${a.type}`);return{...a,trustedRunner:'scripts/observable-browser-runner.mjs'}});const expected=v.expected||{},events=expected.events||[],state=expected.state||{};return{provenance:{contract:`contracts/kumo.observable/v1/components/${c.component}.json`,contractDigest:digest(source),vector:`${c.component}/${v.id}`},import:{path:c.canonical.exportPath,export:exp,compoundExports:c.publicApi.exports.filter(x=>x!==exp&&x.startsWith(exp+'.'))},node:{kind:'component',ref:exp,props:v.props||{},defaultLiterals:c.publicApi.defaults||{},children:'children'in(v.props||{})?[{kind:'text',value:v.props.children}]:[],slots:[]},setup:{state,eventLog:events.length?{probe:'ordered',initial:[]}:null,callbacks:events.map(name=>({event:name,append:name}))},probes:{callbacks:events,controlledState:Object.keys(state),model:Object.keys(state).filter(k=>/value|open|checked|selected/i.test(k))},actions,assertions:[{scope:'vector',checkpoint:'final',expected},...actions.filter(a=>a.checkpoint).map((a,i)=>({scope:a.scope||'vector',checkpoint:`action-${i}`,expected:a.checkpoint}))],requirements:{portal:actions.some(a=>a.scope==='document'),focus:'focus'in expected,nodeIdentity:'preserve-hydrated-root',ssr:'supported',hydration:'identical'}}})}
export function compile({contractsDir=path.join(root,'contracts/kumo.observable/v1/components')}={}){const files=fs.readdirSync(contractsDir).filter(x=>x.endsWith('.json')).sort(),vectors=[],capabilityFrequency={};for(const file of files){const source=fs.readFileSync(path.join(contractsDir,file),'utf8');try{vectors.push(...compileContract(JSON.parse(source),source))}catch(e){capabilityFrequency[e.message]=(capabilityFrequency[e.message]||0)+1}}const contractDigest=digest(files.map(f=>fs.readFileSync(path.join(contractsDir,f),'utf8')).join('\0')),plan={schemaVersion:'kumo.packed-fixture/v1',contract:{schemaVersion:'kumo.observable/v1',provenanceDigest:contractDigest},inventory:{contracts:files.length,total:vectors.length},policy:{frameworkNeutral:true,browserLifecycle:'adapter-owned',trustedActionDsl:'scripts/observable-browser-runner.mjs',sourceStrings:false,html:false,syntheticEvents:false,exceptions:false},vectors};plan.digest=digest(plan);const manifest={schemaVersion:'kumo.packed-fixture-manifest/v1',ready:vectors.length===124&&Object.keys(capabilityFrequency).length===0,expectedVectors:124,compiledVectors:vectors.length,capabilityFrequency,provenanceDigest:contractDigest,planDigest:plan.digest};return{plan:validatePlan(plan),manifest}}
