import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import{fileURLToPath}from'node:url';
import{FIXTURE_PLAN_VERSION,fixturePlanDigest,validateFixturePlan}from'./fixture-plan.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../..');
const TYPES=new Set(['click','focus','blur','key','type','wait']);
const FAMILY_KINDS=new Set(['checkbox-group','radio-group','switch-group']);
const ACTION_FIELDS=new Set(['type','selector','target','scope','checkpoint','text','editMode','key','ms']);
const FAMILY_FIELDS=new Set(['kind','legend','items','defaultValue','value','disabled']);
const literal=x=>x===null||['string','number','boolean'].includes(typeof x)||Array.isArray(x)&&x.every(literal)||x&&Object.getPrototypeOf(x)===Object.prototype&&Object.values(x).every(literal);
export const stable=x=>Array.isArray(x)?x.map(stable):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])])):x;
export const digest=x=>crypto.createHash('sha256').update(typeof x==='string'?x:JSON.stringify(stable(x))).digest('hex');
const clone=x=>JSON.parse(JSON.stringify(x));
function fail(ok,msg){if(!ok)throw Error(msg)}
function canonicalExport(c){return c.publicApi.exports.find(x=>x.toLowerCase().replaceAll('-','')===c.component.replaceAll('-',''))||c.publicApi.exports.find(x=>/^[A-Z]/.test(x))}
function resolveRef(ref,canonical,exports){fail(typeof ref==='string','fixture export must be a string');if(ref==='root')return canonical;if(ref.startsWith('.')){fail(/^\.[A-Za-z][A-Za-z0-9]*(?:\.[A-Za-z][A-Za-z0-9]*)*$/.test(ref),`invalid compound export ${ref}`);return canonical+ref}fail(exports.includes(ref),`unknown public export ${ref}`);return ref}
function compileNode(node,c,canonical,rootProps={},isRoot=false){fail(node&&Object.getPrototypeOf(node)===Object.prototype,'invalid fixture node');if('text'in node){fail(Object.keys(node).length===1&&typeof node.text==='string','invalid text node');return{kind:'text',value:node.text}}fail(Object.keys(node).every(k=>['export','props','children'].includes(k)),'unsupported fixture field');fail(Object.hasOwn(node,'export')&&Object.hasOwn(node,'props')&&Object.hasOwn(node,'children'),'incomplete fixture node');fail(literal(node.props)&&Array.isArray(node.children),'invalid fixture node payload');return{kind:'component',ref:resolveRef(node.export,canonical,c.publicApi.exports),props:clone(isRoot&&node.export==='root'?{...rootProps,...node.props}:node.props),children:node.children.map(x=>compileNode(x,c,canonical,{},false))}}
function compileFixture(v,c,canonical){if(!v.fixture){const props=clone(v.props);let children=[];if(Object.hasOwn(props,'children')){fail(typeof props.children==='string','root props.children must be text');children=[{kind:'text',value:props.children}]}return{kind:'component',ref:canonical,props,children}}if(v.fixture.kind){fail(FAMILY_KINDS.has(v.fixture.kind),`unsupported fixture kind ${v.fixture.kind}`);fail(Object.keys(v.fixture).every(k=>FAMILY_FIELDS.has(k)),'unsupported family fixture field');fail(literal(v.fixture),'non-serializable family fixture');return{kind:'family-fixture',family:v.fixture.kind,adapterRequirement:`${v.fixture.kind}-adapter`,payload:clone(v.fixture)}}return compileNode(v.fixture,c,canonical,v.props??{},true)}
function sourceFixture(v,c,canonical){return compileFixture(v,c,canonical)}
function validateLossless(v,p,c,canonical){fail(JSON.stringify(p.fixture)===JSON.stringify(sourceFixture(v,c,canonical)),'fixture compilation is lossy');fail(JSON.stringify(p.actions.map(({trustedRunner,...a})=>a))===JSON.stringify(v.actions||[]),'actions compilation is lossy');fail(JSON.stringify(p.setup)===JSON.stringify(v.setup||{}),'setup compilation is lossy');fail(JSON.stringify(p.expected)===JSON.stringify(v.expected||{}),'expected compilation is lossy')}
function compileContract(c,source){fail(c.schemaVersion==='kumo.observable/v1','bad contract schema');fail(c.component&&c.canonical?.exportPath&&Array.isArray(c.publicApi?.exports)&&c.publicApi.exports.length,'invalid contract API');const exp=canonicalExport(c);fail(exp,'no component export');return c.vectors.map(v=>{fail(v.id&&literal(v.props)&&literal(v.expected||{})&&literal(v.setup||{}),'non-serializable vector');const actions=(v.actions||[]).map(a=>{fail(literal(a)&&Object.keys(a).every(k=>ACTION_FIELDS.has(k)),`unsupported action field in ${a.type}`);fail(TYPES.has(a.type),`unsupported action ${a.type}`);return{...clone(a),trustedRunner:'scripts/observable-browser-runner.mjs'}});const setup=clone(v.setup||{}),expected=clone(v.expected||{}),callback=setup.callback;fail(callback===undefined||typeof callback==='string','invalid callback setup');const plan={provenance:{contract:`contracts/kumo.observable/v1/components/${c.component}.json`,contractDigest:digest(source),vector:`${c.component}/${v.id}`},import:{path:c.canonical.exportPath,export:exp,publicExports:clone(c.publicApi.exports)},fixture:compileFixture(v,c,exp),setup,probes:{callbacks:callback===undefined?[]:[callback]},actions,expected,assertions:clone(expected)};validateLossless(v,plan,c,exp);return plan})}
export function validatePlan(p){fail(p&&p.schemaVersion==='kumo.packed-fixture/v1','invalid packed fixture schema');fail(literal(p),'plan must be strict JSON');fail(!/(?:<\/?[A-Za-z]|<!doctype|dispatchEvent|new Event|new MouseEvent|new KeyboardEvent)/.test(JSON.stringify(p)),'source, HTML, or synthetic events forbidden');fail(p.policy?.browserLifecycle==='shared-runner-owned','browser lifecycle must be shared-runner-owned');fail(Array.isArray(p.vectors)&&p.vectors.length===p.inventory.total,'inventory mismatch');const ids=p.vectors.map(v=>v.provenance.vector);fail(new Set(ids).size===ids.length,'duplicate vector');for(const v of p.vectors){fail(v.import&&v.import.export&&Array.isArray(v.import.publicExports)&&v.import.publicExports.includes(v.import.export),'missing export');const check=n=>{if(n.kind==='text'){fail(typeof n.value==='string','invalid text');return}if(n.kind==='family-fixture'){fail(FAMILY_KINDS.has(n.family)&&n.adapterRequirement===`${n.family}-adapter`&&n.payload.kind===n.family,'invalid family fixture');return}fail(n.kind==='component','invalid component node');fail(v.import.publicExports.includes(n.ref)||n.ref.startsWith(v.import.export+'.'),`unowned export ${n.ref}`);for(const child of n.children)check(child)};check(v.fixture);for(const a of v.actions)fail(TYPES.has(a.type)&&a.trustedRunner==='scripts/observable-browser-runner.mjs','untrusted action')}return p}
const TOGGLES=new Set(['checkbox','switch']);
const bundle={entry:'client.js',viteConfig:'vite.config.mjs',files:{},headHtml:'',beforeAppHtml:'',buildEnv:{}};
const toggleSetup=v=>{const controlled=v.setup?.mode==='controlled'||Object.hasOwn(v.props??{},'checked');const out=[{kind:controlled?'controlled-state':'uncontrolled-state',mode:controlled?'controlled':'uncontrolled',initial:v.props?.checked??false}];if(v.setup?.callback)out.push({kind:'event-recorder',callback:v.setup.callback});else if((v.expected?.events??[]).length)out.push({kind:'event-recorder'});return out};
const toggleProbes=expected=>{const out=[];if(expected.root)out.push({kind:'dom',path:'root'});if(expected.root?.attributes)out.push({kind:'aria',path:'root'});if(expected.state)out.push({kind:'state',path:'state'});if(Object.hasOwn(expected,'events'))out.push({kind:'events',path:'events'});if(Object.hasOwn(expected,'focus'))out.push({kind:'focus',path:'focus'});out.push({kind:'node-identity',path:'root'});return out};
const toggleAssertions=(expected,probes)=>probes.filter(p=>p.kind!=='node-identity').map(p=>({kind:p.kind==='events'?'sequence':p.kind==='dom'?'includes':'equals',probe:p.kind,expected:p.kind==='dom'?expected.root:p.kind==='aria'?expected.root.attributes:p.kind==='state'?expected.state:p.kind==='events'?expected.events:expected.focus})).concat({kind:'identity',probe:'node-identity',expected:'preserved'});
function compileToggleContract(c,source){const canonical=canonicalExport(c),contractSha=digest(source);return c.vectors.map(v=>{const expected=clone(v.expected),probes=toggleProbes(expected);const plan={schemaVersion:FIXTURE_PLAN_VERSION,component:c.component,vector:v.id,contract:{schemaVersion:c.schemaVersion,path:`contracts/kumo.observable/v1/components/${c.component}.json`,sha256:contractSha,vectorSha256:digest(v)},fixture:compileFixture(v,c,canonical),setup:toggleSetup(v),actions:clone(v.actions??[]),probes,assertions:toggleAssertions(expected,probes),capabilities:[`${c.component}-fixture`,...(v.fixture?.kind?[`${v.fixture.kind}-adapter`]:[]),'trusted-actions','dom-probes','aria-probes','state-probes','event-probes','focus-probes','node-identity'],bundle:clone(bundle)};plan.digest=fixturePlanDigest(plan);return validateFixturePlan(plan)})}
export function compileToggleFixtures({contractsDir=path.join(root,'contracts/kumo.observable/v1/components')}={}){const plans=[];for(const component of [...TOGGLES].sort()){const source=fs.readFileSync(path.join(contractsDir,`${component}.json`),'utf8');plans.push(...compileToggleContract(JSON.parse(source),source))}const result={schemaVersion:'kumo.toggle-fixtures/v1',plans};result.digest=digest(result);return result}
export function compile({contractsDir=path.join(root,'contracts/kumo.observable/v1/components')}={}){const files=fs.readdirSync(contractsDir).filter(x=>x.endsWith('.json')).sort(),vectors=[],capabilityFrequency={};for(const file of files){const source=fs.readFileSync(path.join(contractsDir,file),'utf8');try{vectors.push(...compileContract(JSON.parse(source),source))}catch(e){capabilityFrequency[e.message]=(capabilityFrequency[e.message]||0)+1}}const contractDigest=digest(files.map(f=>fs.readFileSync(path.join(contractsDir,f),'utf8')).join('\0')),plan={schemaVersion:'kumo.packed-fixture/v1',contract:{schemaVersion:'kumo.observable/v1',provenanceDigest:contractDigest},inventory:{contracts:files.length,total:vectors.length},policy:{frameworkNeutral:true,browserLifecycle:'shared-runner-owned',trustedActionDsl:'scripts/observable-browser-runner.mjs',sourceStrings:false,html:false,syntheticEvents:false,exceptions:false},vectors};plan.digest=digest(plan);let valid=true;try{validatePlan(plan)}catch(e){valid=false;capabilityFrequency[e.message]=(capabilityFrequency[e.message]||0)+1}const manifest={schemaVersion:'kumo.packed-fixture-manifest/v1',ready:valid&&vectors.length===124&&Object.keys(capabilityFrequency).length===0,expectedVectors:124,compiledVectors:vectors.length,capabilityFrequency,provenanceDigest:contractDigest,planDigest:plan.digest};return{plan,manifest}}
