import { readFile, mkdir, writeFile } from 'node:fs/promises';
const spec=JSON.parse(await readFile(new URL('../specs/select.json',import.meta.url),'utf8'));
const trigger='kumo-trigger';
const icon='<svg aria-hidden="true" width="16" height="16" viewBox="0 0 16 16"><path fill="currentColor" d="m4 6 4 4 4-4z"/></svg>';
const options=['Apple','Banana','Cherry'];
const vue=`<script setup>\nimport {ref} from 'vue'; const p=defineProps({label:String,disabled:Boolean,value:String,placeholder:String,error:String,description:String}); const options=['Apple','Banana','Cherry']; const open=ref(false), selected=ref(p.value||''); const id=(p.label||'select').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-listbox'; function key(e){if(['ArrowDown','Enter',' '].includes(e.key)){e.preventDefault();open.value=true}else if(e.key==='Escape')open.value=false} function choose(v){selected.value=v;open.value=false}\n</script>\n<template><div class="kumo-field"><label>{{p.label}}</label><button type="button" role="combobox" :id="id+'-trigger'" :aria-controls="id" :aria-expanded="open" aria-haspopup="listbox" :disabled="p.disabled" @click="open=!open" @keydown="key" class="${trigger}"><span>{{selected||p.placeholder}}</span>${icon}</button><ul v-if="open" :id="id" role="listbox"><li v-for="o in options" role="option" :aria-selected="selected===o" tabindex="-1" @click="choose(o)">{{o}}</li></ul><p v-if="p.error" class="error">{{p.error}}</p><p v-else-if="p.description" class="description">{{p.description}}</p></div></template>\n`;
const svelte=`<script>export let label='';export let disabled=false;export let value='';export let placeholder='';export let error='';export let description='';let open=false;let selected=value;$: id=(label||'select').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-listbox';const options=${JSON.stringify(options)};function key(e){if(['ArrowDown','Enter',' '].includes(e.key)){e.preventDefault();open=true}else if(e.key==='Escape')open=false}function choose(v){selected=v;open=false}</script>\n<div class="kumo-field"><label for={id+'-trigger'}>{label}</label><button type="button" role="combobox" id={id+'-trigger'} aria-controls={id} aria-expanded={open} aria-haspopup="listbox" {disabled} onclick={()=>open=!open} onkeydown={key} class="${trigger}"><span>{selected||placeholder}</span>${icon}</button>{#if open}<ul id={id} role="listbox">{#each options as o}<li role="option" aria-selected={selected===o} tabindex="-1" onclick={()=>choose(o)} onkeydown={(e)=>['Enter',' '].includes(e.key)&&choose(o)}>{o}</li>{/each}</ul>{/if}{#if error}<p class="error">{error}</p>{:else if description}<p class="description">{description}</p>{/if}</div>\n`;
const solid=`import {createSignal} from 'solid-js'; export default function Select(p){const [open,setOpen]=createSignal(false),[selected,setSelected]=createSignal(p.value||'');const id=()=> (p.label||'select').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-listbox';const key=e=>{if(['ArrowDown','Enter',' '].includes(e.key)){e.preventDefault();setOpen(true)}else if(e.key==='Escape')setOpen(false)};const choose=o=>{setSelected(o);setOpen(false)};return <div class="kumo-field"><label>{p.label}</label><button type="button" role="combobox" id={id()+'-trigger'} aria-controls={id()} aria-expanded={open()} aria-haspopup="listbox" disabled={p.disabled} onClick={()=>setOpen(!open())} onKeyDown={key} class="${trigger}"><span>{selected()||p.placeholder}</span>${icon}</button>{open()&&<ul id={id()} role="listbox">{${JSON.stringify(options)}.map(o=><li role="option" aria-selected={selected()===o} tabIndex="-1" onClick={()=>choose(o)}>{o}</li>)}</ul>}{p.error?<p class="error">{p.error}</p>:p.description?<p class="description">{p.description}</p>:null}</div>}\n`;
for(const f of ['vue','svelte','solid'])await mkdir(`runtime/${f}/src`,{recursive:true});await writeFile('runtime/vue/src/Select.vue',vue);await writeFile('runtime/svelte/src/Select.svelte',svelte);await writeFile('runtime/solid/src/Select.tsx',solid);console.log(`generated ${spec.name} runtime sources for vue/svelte/solid`);
