import { readFile, mkdir, writeFile } from 'node:fs/promises';

const spec = JSON.parse(await readFile(new URL('../specs/select.json', import.meta.url), 'utf8'));
const triggerClass = 'group flex w-max shrink-0 items-center select-none border-0 shadow-xs focus:outline-none focus-visible:ring-2 focus-visible:ring-kumo-brand cursor-pointer disabled:cursor-not-allowed disabled:text-kumo-subtle bg-kumo-base !text-kumo-default ring not-disabled:hover:bg-kumo-tint disabled:bg-kumo-base/50 disabled:!text-kumo-default/70 ring-kumo-line data-[state=open]:bg-kumo-base h-9 gap-1.5 rounded-lg px-3 text-base justify-between font-normal focus:opacity-100 focus:ring-kumo-focus/50 focus-visible:ring-inset *:in-focus:opacity-100';
const fieldClass = 'grid gap-2 has-[input[type=checkbox]]:grid-cols-[auto_1fr] has-[input[type=checkbox]]:items-center has-[[role=switch]]:grid-cols-[auto_1fr] has-[[role=switch]]:items-center';
const icon = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 256 256" class="fill-current"><path d="M181.66,170.34a8,8,0,0,1,0,11.32l-48,48a8,8,0,0,1-11.32,0l-48-48a8,8,0,0,1,11.32-11.32L128,212.69l42.34-42.35A8,8,0,0,1,181.66,170.34Zm-96-84.68L128,43.31l42.34,42.35a8,8,0,0,0,11.32-11.32l-48-48a8,8,0,0,0-11.32,0l-48,48A8,8,0,0,0,85.66,85.66Z"></path></svg>';

const vue = `<script setup>\nconst p = defineProps({ label:String, disabled:Boolean, value:String, placeholder:String, error:String, description:String })\n</script>\n<template><div class="${fieldClass}"><div class="m-0 select-none text-base font-medium text-kumo-default"><span class="inline-flex items-center gap-1">{{p.label}}</span></div><button type="button" role="combobox" aria-expanded="false" aria-haspopup="listbox" data-kumo-component="Select" data-kumo-part="trigger" :disabled="p.disabled" :aria-label="p.label" :class="['${triggerClass}', p.error && '!ring-kumo-danger focus:ring-kumo-danger/50 focus:ring-[1.5px]']"><span data-placeholder class="min-w-0 truncate data-[placeholder]:text-kumo-placeholder">{{p.value || p.placeholder}}</span><span aria-hidden="true" class="flex shrink-0 items-center text-kumo-subtle">${icon}</span></button><p v-if="p.error" class="text-sm text-kumo-danger col-span-full">{{p.error}}</p><p v-else-if="p.description" class="text-sm leading-snug text-kumo-subtle col-span-full">{{p.description}}</p></div></template>\n`;
const svelte = `<script>export let label=''; export let disabled=false; export let value=''; export let placeholder=''; export let error=''; export let description='';</script>\n<div class="${fieldClass}"><div class="m-0 select-none text-base font-medium text-kumo-default"><span class="inline-flex items-center gap-1">{label}</span></div><button type="button" role="combobox" aria-expanded="false" aria-haspopup="listbox" data-kumo-component="Select" data-kumo-part="trigger" {disabled} aria-label={label} class="${triggerClass} {error ? '!ring-kumo-danger focus:ring-kumo-danger/50 focus:ring-[1.5px]' : ''}" ><span data-placeholder class="min-w-0 truncate data-[placeholder]:text-kumo-placeholder">{value || placeholder}</span><span aria-hidden="true" class="flex shrink-0 items-center text-kumo-subtle">${icon}</span></button>{#if error}<p class="text-sm text-kumo-danger col-span-full">{error}</p>{:else if description}<p class="text-sm leading-snug text-kumo-subtle col-span-full">{description}</p>{/if}</div>\n`;
const solid = `export default function Select(p) { return <div class="${fieldClass}"><div class="m-0 select-none text-base font-medium text-kumo-default"><span class="inline-flex items-center gap-1">{p.label}</span></div><button type="button" role="combobox" aria-expanded="false" aria-haspopup="listbox" data-kumo-component="Select" data-kumo-part="trigger" disabled={p.disabled} aria-label={p.label} class={'${triggerClass} ' + (p.error ? '!ring-kumo-danger focus:ring-kumo-danger/50 focus:ring-[1.5px]' : '')} ><span data-placeholder class="min-w-0 truncate data-[placeholder]:text-kumo-placeholder">{p.value || p.placeholder}</span><span aria-hidden="true" class="flex shrink-0 items-center text-kumo-subtle">${icon}</span></button>{p.error ? <p class="text-sm text-kumo-danger col-span-full">{p.error}</p> : p.description ? <p class="text-sm leading-snug text-kumo-subtle col-span-full">{p.description}</p> : null}</div>; }\n`;

for (const framework of ['vue', 'svelte', 'solid']) await mkdir(`runtime/${framework}/src`, { recursive: true });
await writeFile('runtime/vue/src/Select.vue', vue);
await writeFile('runtime/svelte/src/Select.svelte', svelte);
await writeFile('runtime/solid/src/Select.tsx', solid);
console.log(`generated ${spec.name} runtime sources for vue/svelte/solid`);
